### ISSUE TITLE
Support for power mock test notification without up-front determined test methods or test methods that are named differently

### ISSUE THREAD

**Issue by Vampire** [powermock/powermock#1003]
The current power mock test notification mechanism requires that the test methods
- are known up-front and
- that the name of the method matches the name of the test and
- that the test methods are annotated with `@Test` or `@Theory`.

All these are too strict requirements if you want to support more advanced JUnit runners, like for example Spock.
I added `@RunWith(PowerMockRunner)` to one of my spock test (and via AST transformation automatically `@PowerMockRunnerDelegate(Sputnik)` too.
This resulted immediately in getting the exception provided below.

The problem is, for example with Spock but maybe also with other runners:
- the test methods are not annotated with `@Test` (actually they are annotated with `@FeatureMetadata` when PowerMock sees them)
- Even if `@FeatureMetadata` annotated methods would be considered test methods, the names of the actual methods are never identical to the reported tests
- For data-driven tests (with where-block), one feature method can be executed mutliple times as iterations and if you chose to "unroll" the method, each iteration is reported as single executed test, but resulting from the same test method
- The iterations of a test if it is unrolled cannot be provided up-front in any way, not even their name, or amount. Iterations (amount as well as possibly name) depend on data providers, which can be consume-once iterators, so they can only be consumed when the iterations are actually calculated, executed and sent to the notifier and not up-front.

Currently this only results in cluttered output, as for each feature method (or actually for each iteration) this stacktrace is printed.
This results in the test methods array in the suite notification methods being empty and the test method in the test notification methods being `null`.
But at least the shipped implementations of the listener do not consider these parameters anyway, so there is currently not much harm besides the cluttered output.

If not changing the implementation to properly support such situations, it might at least make sense to provide a way to suppress this stacktrace being printed and possibly enable this suppression automatically if tests are run with Spock. Also in this case or generally it might make sense to document in the interface that the array might be empty and the method might be `null` so that implementers might think about it.

```
java.lang.IllegalArgumentException: Unable to determine method-name from description=bar(net.kautler.command.api.CommandHandlerTest); - ignored
	at org.powermock.modules.junit4.internal.impl.NotificationBuilder.determineTestMethod(NotificationBuilder.java:157)
	at org.powermock.modules.junit4.internal.impl.NotificationBuilder.access$000(NotificationBuilder.java:38)
	at org.powermock.modules.junit4.internal.impl.NotificationBuilder$OngoingTestRun.<init>(NotificationBuilder.java:86)
	at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testStartHasBeenFired(NotificationBuilder.java:233)
	at org.powermock.modules.junit4.internal.impl.PowerMockRunNotifier.fireTestStarted(PowerMockRunNotifier.java:112)
	at org.spockframework.runtime.JUnitSupervisor.beforeFeature(JUnitSupervisor.java:62)
	at org.spockframework.runtime.BaseSpecRunner.runFeature(BaseSpecRunner.java:234)
	at org.spockframework.runtime.BaseSpecRunner.runFeatures(BaseSpecRunner.java:185)
	at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:95)
	at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:81)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:484)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:73)
	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:64)
	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$2.call(DelegatingPowerMockRunner.java:149)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$2.call(DelegatingPowerMockRunner.java:141)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.withContextClassLoader(DelegatingPowerMockRunner.java:132)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.run(DelegatingPowerMockRunner.java:141)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Vampire** [comment]
Btw. in case of Spock one could probably develop some Spock extension that properly triggers the PowerMock lifecycle with having more information like the feature method that an iteration originates from instead of using a JUnit rule, but the points mentioned here would still be valid.

**Comment by Vampire** [comment]
Btw. this is with PowerMock 2.0.2 and Spock 1.3-groovy-2.5
