### ISSUE TITLE
Byte code manipulation and behaviour detection for PowerMock test notification does not work properly for Spock tests

### ISSUE THREAD

**Issue by Vampire** [powermock/powermock#1004]
With PowerMock 2.0.2 and Spock 1.3-groovy-2.5 the byte code manipulation to inject PowerMock test notification calls does not work properly.

With one specification with two test features, with the specification annotated with `@RunWith(PowerMockRunner)` and `@PowerMockRunnerDelegate(Sputnik)`, I get this sequence of events in the `NotificationBuilder`:

```
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testSuiteStarted(NotificationBuilder.java:208)
class net.kautler.command.api.CommandHandlerTest
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@12a977f7
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testStartHasBeenFired(NotificationBuilder.java:216)
foo(net.kautler.command.api.CommandHandlerTest)
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@7ba3d8db
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.failure(NotificationBuilder.java:293)
foo(net.kautler.command.api.CommandHandlerTest): 

[Ljava.lang.Object;@7325ba3e
The class net.kautler.command.api.CommandHandlerTest$TestCommandHandler not prepared for test.

Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testFinished(NotificationBuilder.java:297)
foo(net.kautler.command.api.CommandHandlerTest)
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testStartHasBeenFired(NotificationBuilder.java:216)
bar(net.kautler.command.api.CommandHandlerTest)
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@57d74d5
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.failure(NotificationBuilder.java:293)
bar(net.kautler.command.api.CommandHandlerTest): Condition not satisfied:

TestCommandHandler.initialized
|                  |
|                  null
class net.kautler.command.api.CommandHandlerTest$TestCommandHandler

Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testFinished(NotificationBuilder.java:297)
bar(net.kautler.command.api.CommandHandlerTest)
```

So it looks like three times `testInstanceCreated` is triggered for two tests and it seems like `START_FIRES_FIRST` should be determined, but due to the additional `testInstanceCreated`, the opposite `TEST_INSTANCE_CREATED_FIRST` is determined instead.

---

Adding `@PrepareForTest(...)` to the test class even makes things worse.
Now suddenly `testInstanceCreated` is called four times for each instance, which results in the `ALL_TESTINSTANCES_ARE_CREATED_FIRST` behaviour being detected falsely and a lot of `Notifications are not supported when all test-instances are created first!` and `Notifications are not supported for behaviour ALL_TESTINSTANCES_ARE_CREATED_FIRST` messages spammed to stderr:

```
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testSuiteStarted(NotificationBuilder.java:208)
class net.kautler.command.api.CommandHandlerTest
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@5b037f49
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@5b037f49
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@5b037f49
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@5b037f49
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testStartHasBeenFired(NotificationBuilder.java:216)
foo(net.kautler.command.api.CommandHandlerTest)
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@37cf569a
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@37cf569a
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@37cf569a
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@37cf569a
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.failure(NotificationBuilder.java:293)
foo(net.kautler.command.api.CommandHandlerTest): Condition not satisfied:

TestCommandHandler.initialized
|                  |
|                  null
class net.kautler.command.api.CommandHandlerTest$TestCommandHandler

Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testFinished(NotificationBuilder.java:297)
foo(net.kautler.command.api.CommandHandlerTest)
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testStartHasBeenFired(NotificationBuilder.java:216)
bar(net.kautler.command.api.CommandHandlerTest)
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@1a698cc6
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@1a698cc6
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@1a698cc6
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testInstanceCreated(NotificationBuilder.java:246)
net.kautler.command.api.CommandHandlerTest@1a698cc6
Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.failure(NotificationBuilder.java:293)
bar(net.kautler.command.api.CommandHandlerTest): Condition not satisfied:

TestCommandHandler.initialized
|                  |
|                  null
class net.kautler.command.api.CommandHandlerTest$TestCommandHandler

Breakpoint reached at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testFinished(NotificationBuilder.java:297)
bar(net.kautler.command.api.CommandHandlerTest)
```

**Comment by Vampire** [comment]
Attaching `@PrepareForTest` to a feature method instead of the class also does not work, then I get again the method not found from #1003 and then a `NullPointerException` at:
```
java.lang.NullPointerException
	at org.powermock.modules.junit4.internal.impl.NotificationBuilder$OngoingTestRun.testClass(NotificationBuilder.java:101)
	at org.powermock.modules.junit4.internal.impl.NotificationBuilder$OngoingTestRun.<init>(NotificationBuilder.java:88)
	at org.powermock.modules.junit4.internal.impl.NotificationBuilder.testStartHasBeenFired(NotificationBuilder.java:233)
	at org.powermock.modules.junit4.internal.impl.PowerMockRunNotifier.fireTestStarted(PowerMockRunNotifier.java:112)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$2.call(DelegatingPowerMockRunner.java:149)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$2.call(DelegatingPowerMockRunner.java:141)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.withContextClassLoader(DelegatingPowerMockRunner.java:132)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.run(DelegatingPowerMockRunner.java:141)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```
