### ISSUE TITLE
PowerMockRunner does not support "Stream.of" in Java 11

### ISSUE THREAD

**Issue by RhuanKrum** [powermock/powermock#1006]
I have been working in migrating things from Java 8 to Java 11, and during this process I updated the `PowerMock` version to latest (2.0.2), which broke existent unit tests that are using `Stream.of` with `@RunWith(PowerMockRunner.class)`. Here are the details about the issue:

**What steps will reproduce the problem?**
Just run the following class (PowerMock 2.0.2, JUnit 4.12, JDK 11):

```
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.modules.junit4.PowerMockRunner;

import java.util.stream.Stream;

@RunWith(PowerMockRunner.class)
public class TestStreamOf {

	@Test
	public void testStreamOf() {
		Stream<String> values = Stream.of("a", "b", "c");
		Assert.assertEquals(3, values.count());
	}
}
```

**What is the expected output?**
The `Stream.of` to be handled normally.

**What do you see instead?**
The exception of type `IncompatibleClassChangeError` is thrown when we try using `Stream.of` with `@RunWith(PowerMockRunner.class)`.

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.powermock.reflect.internal.WhiteboxImpl (file:/C:/.../powermock-easymock-2.0.2-full.jar) to method java.lang.Object.clone()
> WARNING: Please consider reporting this to the maintainers of org.powermock.reflect.internal.WhiteboxImpl
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> 
> **java.lang.IncompatibleClassChangeError: Method 'java.util.stream.Stream java.util.stream.Stream.of(java.lang.Object[])' must be InterfaceMethodref constant**
> 
> 	at TestStreamOf.testStreamOf(TestStreamOf.java:13)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
> 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
> 	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
> 	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
> 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
> 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
> 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
> 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
> 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
> 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
> 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
> 	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
> 	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
> 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
> 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
> 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
> 	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
> 	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
> 	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
> 	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
> 	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
> 	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**What version of the product are you using?**
I am using PowerMock 2.0.2 with JUnit 4.12 in a Windows 10 machine running on JDK 11.0.4.
I also tried every other 2.x version of `PowerMock`, but all of them are failing.

**Comment by fpoyer** [comment]
I know the issue is very old and Powermock is pretty much dead, but any chance you finally found a solution for this?
