### ISSUE TITLE
Mocking system classes does not work from dynamic Groovy test

### ISSUE THREAD

**Issue by Vampire** [powermock/powermock#1008]
If you write your tests in Groovy (no matter whether it is a Spock or plain JUnit test), and try to mock a system class call, it does not work, but you get the error:

```
org.mockito.exceptions.misusing.MissingMethodInvocationException: 
when() requires an argument which has to be 'a method call on a mock'.
For example:
    when(mock.getArticles()).thenReturn(articles);
```

If you use `@CompileStatic` on the specification / test class (if possible) or the feature method / test method (if possible) or on a helper method that you then call from your test, it works. So this seems to be an incompatibility with the dynamic language features of Groovy.

Hopefully this can be fixed in PowerMock, or at least be mentioned in the docs.

**Comment by kriegaex** [comment]
I can confirm this for static system methods (have not tried non-static ones yet). Here is an [MCVE](https://stackoverflow.com/help/mcve):

```java
package de.scrum_master.powermock;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Collections;
import java.util.List;
import java.util.UUID;

public class ClassCallingStaticSystemMethods {
  public String genUUID() {
    return UUID.randomUUID().toString();
  }

  public Date genDate(String date) {
    return Date.valueOf(date);
  }

  public void shuffleCollection(List<?> list) {
    Collections.shuffle(list);
  }

  public Timestamp genTimestamp(String timestamp) {
    return Timestamp.valueOf(timestamp);
  }
}
```

Here is a Java JUnit test stubbing and verifying system class static methods via PowerMockito:

```java
package de.scrum_master.powermock;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.stubbing.Answer;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import java.lang.reflect.Method;
import java.sql.Date;
import java.sql.DriverManager;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.anyString;
import static org.mockito.Mockito.times;
import static org.powermock.api.mockito.PowerMockito.*;

@RunWith(PowerMockRunner.class)
@PrepareForTest({ ClassCallingStaticSystemMethods.class })
public class PowermockStaticMockJUnitTest {
  @Test
  public void mySqlDateTest_whenThenReturn() {
    Date mockDate = new Date(1971 - 1900, 5 - 1, 8);
    mockStatic(Date.class);
    when(Date.valueOf(anyString())).thenReturn(mockDate);
    Date date = new ClassCallingStaticSystemMethods().genDate("1998-12-20");
    // Static mocking works for system (JDK, JRE) classes if the class *using* the
    // system class is present in @PrepareForTest instead of the system class itself
    assertEquals(mockDate, date);
    // Static verification works with system (JDK, JRE) classes, too
    verifyStatic(Date.class, times(1));
    Date.valueOf(anyString());
  }

  @Test
  public void mySqlDateTest_whenThenAnswer() {
    Date mockDate = new Date(1971 - 1900, 5 - 1, 8);
    mockStatic(Date.class);
    when(Date.valueOf(anyString())).thenAnswer((Answer<Date>) invocation -> {
      Object[] args = invocation.getArguments();
      Method method = invocation.getMethod();
      System.out.println(method.toString() + " called with arguments: " + Arrays.toString(args));
      return mockDate;
    });
    Date date = new ClassCallingStaticSystemMethods().genDate("1998-12-20");
    // Static mocking works for system (JDK, JRE) classes if the class *using* the
    // system class is present in @PrepareForTest instead of the system class itself
    assertEquals(mockDate, date);
    // Static verification works with system (JDK, JRE) classes, too
    verifyStatic(Date.class, times(1));
    Date.valueOf(anyString());
  }

  @Test
  public void testDriverManager() throws Exception {
    mockStatic(DriverManager.class);
    when(DriverManager.getLoginTimeout()).thenReturn(111);
    assertEquals(111, DriverManager.getLoginTimeout());
    verifyStatic(DriverManager.class, times(1));
    DriverManager.getLoginTimeout();
  }

  @Test
  public void assertThatMockingOfCollectionsWork() throws Exception {
    List<?> list = new LinkedList<Object>();
    mockStatic(Collections.class);

    Collections.shuffle(list);
    new ClassCallingStaticSystemMethods().shuffleCollection(list);

    verifyStatic(Collections.class, times(2));
    Collections.shuffle(list);
  }
}
```

This works as expected. Now here is the very same class copied into a Groovy class and adjusted to compile:

```groovy
package de.scrum_master.powermock

import groovy.transform.CompileStatic
import org.junit.Test
import org.junit.runner.RunWith
import org.mockito.invocation.InvocationOnMock
import org.mockito.stubbing.Answer
import org.powermock.core.classloader.annotations.PrepareForTest
import org.powermock.modules.junit4.PowerMockRunner
import spock.lang.Specification

import java.lang.reflect.Method
import java.sql.Date
import java.sql.DriverManager
import java.sql.Timestamp

import static org.junit.Assert.assertEquals
import static org.mockito.ArgumentMatchers.anyString
import static org.mockito.Mockito.times
import static org.powermock.api.mockito.PowerMockito.*

@RunWith(PowerMockRunner)
@PrepareForTest([ClassCallingStaticSystemMethods])
@CompileStatic
class PowermockStaticMockJUnitGroovyTest extends Specification {
  @Test
  void mySqlDateTest_whenThenReturn() {
    Date mockDate = new Date(1971 - 1900, 5 - 1, 8)
    mockStatic(Date.class)
    when(Date.valueOf(anyString())).thenReturn(mockDate)
    Date date = new ClassCallingStaticSystemMethods().genDate("1998-12-20")
    // Static mocking works for system (JDK, JRE) classes if the class *using* the
    // system class is present in @PrepareForTest instead of the system class itself
    assertEquals(mockDate, date)
    // Static verification works with system (JDK, JRE) classes, too
    verifyStatic(Date.class, times(1))
    Date.valueOf(anyString())
  }

  @Test
  void mySqlDateTest_whenThenAnswer() {
    Date mockDate = new Date(1971 - 1900, 5 - 1, 8)
    mockStatic(Date.class)
    when(Date.valueOf(anyString())).thenAnswer(new Answer<Date>() {
      @Override
      Date answer(InvocationOnMock invocation) throws Throwable {
        Object[] args = invocation.getArguments()
        Method method = invocation.getMethod()
        System.out.println(method.toString() + " called with arguments: " + Arrays.toString(args))
        return mockDate
      }
    })
    Date date = new ClassCallingStaticSystemMethods().genDate("1998-12-20")
    // Static mocking works for system (JDK, JRE) classes if the class *using* the
    // system class is present in @PrepareForTest instead of the system class itself
    assertEquals(mockDate, date)
    // Static verification works with system (JDK, JRE) classes, too
    verifyStatic(Date.class, times(1))
    Date.valueOf(anyString())
  }

  @Test
  void mySqlTimeStampTest() {
    Timestamp mockTimestamp = new Timestamp(1971 - 1900, 5 - 1, 8, 11, 15, 0, 0)
    mockStatic(Timestamp.class)
    when(Timestamp.valueOf(anyString())).thenReturn(mockTimestamp)
//    stub(method(Timestamp, "valueOf", String)).toReturn(mockTimestamp)
    Timestamp timestamp = new ClassCallingStaticSystemMethods().genTimestamp("1998-12-20")
    // Static mocking works for system (JDK, JRE) classes if the class *using* the
    // system class is present in @PrepareForTest instead of the system class itself
    assertEquals(mockTimestamp, timestamp)
    // Static verification works with system (JDK, JRE) classes, too
    verifyStatic(Timestamp.class, times(1))
    Timestamp.valueOf(anyString())
  }

  @Test
  void assertThatMockingOfCollectionsWork() throws Exception {
    List<?> list = new LinkedList<Object>()
    mockStatic(Collections.class)

    Collections.shuffle(list)
    new ClassCallingStaticSystemMethods().shuffleCollection(list)

    verifyStatic(Collections.class, times(2))
    Collections.shuffle(list)
  }

  @Test
  void testDriverManager() throws Exception {
    mockStatic(DriverManager.class)
    when(DriverManager.getLoginTimeout()).thenReturn(111)
    assertEquals(111, DriverManager.getLoginTimeout())
    verifyStatic(DriverManager.class, times(1))
    DriverManager.getLoginTimeout()
  }
}
```

This also works, but no longer if you remove the `@CompileStatic` annotation from the class. Just comment it out and it yields errors such as:

```none
java.lang.IllegalArgumentException
	at java.sql.Date.valueOf(Date.java:143)
	at java_sql_Date$valueOf.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at de.scrum_master.powermock.PowermockStaticMockJUnitGroovyTest.mySqlDateTest_whenThenReturn(PowermockStaticMockJUnitGroovyTest.groovy:30)
```

As you can see, inside of `when(Date.valueOf(anyString()))` the **real** static method is suddenly executed with an unexpected parameter `anyString()` which of course cannot be converted to any meaningful SQL date.

In **Spock** it gets even worse because due to the dynamic nature of the Spock testing DSL it is impossible to use `@CompileStatic` for the whole class or even a single feature (test) method. There for each case I need a pair of helper `@CompileStatic` methods, one to set up static mocking and one to verify the interactions. This is ugly and tedious:

```groovy
package de.scrum_master.powermock

import groovy.transform.CompileStatic
import org.junit.runner.RunWith
import org.powermock.core.classloader.annotations.PrepareForTest
import org.powermock.modules.junit4.PowerMockRunner
import org.powermock.modules.junit4.PowerMockRunnerDelegate
import org.spockframework.runtime.Sputnik
import spock.lang.Specification

import java.sql.Date

import static org.mockito.ArgumentMatchers.anyString
import static org.mockito.Mockito.times
import static org.powermock.api.mockito.PowerMockito.*
import static org.powermock.api.support.membermodification.MemberMatcher.method
import static org.powermock.api.support.membermodification.MemberModifier.stub

@RunWith(PowerMockRunner)
@PowerMockRunnerDelegate(Sputnik)
@PrepareForTest(ClassCallingStaticSystemMethods)
class PowermockStaticMockSpockTest extends Specification {

  def testUUID() {
    given:
    def id = "493410b3-dd0b-4b78-97bf-289f50f6e74f"
    UUID uuid = UUID.fromString(id)
    stub(method(UUID, "randomUUID")).toReturn(uuid)

    expect:
    new ClassCallingStaticSystemMethods().genUUID() == id
  }

  def testSQLDate() {
    given:
    def mockDate = new Date(1971 - 1900, 5 - 1, 8)

    when:
    testSQLDate_mockStatic(mockDate)
    def date = new ClassCallingStaticSystemMethods().genDate("1998-12-20")

    then:
    testSQLDate_verifyStatic()
    mockDate == date
  }

  @CompileStatic
  def testSQLDate_mockStatic(Date mockDate) {
    mockStatic(Date)
    when(Date.valueOf(anyString())).thenReturn(mockDate)
  }

  @CompileStatic
  def testSQLDate_verifyStatic() {
    verifyStatic(Date, times(1))
    Date.valueOf(anyString())
    true
  }
}
```

The first method works because I am using `stub(method(UUID, "randomUUID")).toReturn(uuid)` without any of `mockStatic` and `verifyStatic`. But the second method does need the two helper methods as shown above in order to pass. If I inline them I am getting the same error as above in the JUnit (not Spock) Groovy case.

---

**Update:** If I want to avoid using `@CompileStatic` for each helper method, of course I can also move those helper methods into a static inner class, basically creating a namespace, importing them all statically and using them like that. Now one `@CompileStatic` annotation for the inner class is enough, but still we need two methods per case which is no less annoying than before.

```groovy
package de.scrum_master.powermock

import groovy.transform.CompileStatic
import org.junit.runner.RunWith
import org.powermock.core.classloader.annotations.PrepareForTest
import org.powermock.modules.junit4.PowerMockRunner
import org.powermock.modules.junit4.PowerMockRunnerDelegate
import org.spockframework.runtime.Sputnik
import spock.lang.Specification

import java.sql.Date

import static de.scrum_master.powermock.PowermockStaticMockSpockTest.PowerMockHelper.*
import static org.mockito.ArgumentMatchers.anyString
import static org.mockito.Mockito.times
import static org.powermock.api.mockito.PowerMockito.*
import static org.powermock.api.support.membermodification.MemberMatcher.method
import static org.powermock.api.support.membermodification.MemberModifier.stub

@RunWith(PowerMockRunner)
@PowerMockRunnerDelegate(Sputnik)
@PrepareForTest(ClassCallingStaticSystemMethods)
class PowermockStaticMockSpockTest extends Specification {
  def testUUID() {
    given:
    def id = "493410b3-dd0b-4b78-97bf-289f50f6e74f"
    UUID uuid = UUID.fromString(id)
    stub(method(UUID, "randomUUID")).toReturn(uuid)

    expect:
    new ClassCallingStaticSystemMethods().genUUID() == id
  }

  def testSQLDate() {
    given:
    def mockDate = new Date(1971 - 1900, 5 - 1, 8)

    when:
    testSQLDate_mockStatic(mockDate)
    def date = new ClassCallingStaticSystemMethods().genDate("1998-12-20")

    then:
    testSQLDate_verifyStatic()
    mockDate == date
  }

  @CompileStatic
  static class PowerMockHelper {
    def static testSQLDate_mockStatic(Date mockDate) {
      mockStatic(Date)
      when(Date.valueOf(anyString())).thenReturn(mockDate)
    }

    def static testSQLDate_verifyStatic() {
      verifyStatic(Date, times(1))
      Date.valueOf(anyString())
      true
    }
  }
}
```

**Comment by kriegaex** [comment]
New information: One of the Spock/Groovy guys explained why it does not work with PowerMock. Basically it is because of Groovy's dynamic language features as I already guessed. He suggests to add explicit Groovy support to PowerMock, see [this comment](https://github.com/spockframework/spock/issues/1014#issuecomment-538918380).

**Comment by Vampire** [comment]
@kriegaex some points:
- "New information": it is not new information, this is exactly what this ticket is about
- "One of the Spock/Groovy guys": Please don't confuse `Member` and `Contributor`, you become labelled `Contributor` by GitHub as soon as any commit from you is merged even if it is just a typo-fix, I'm just a user like you and not affiliated with Spock more than that I love it and contributed some code
- "Basically it is because of Groovy's dynamic language features as I already guessed." I am the one you refer to in that comment and I am also the one that opened this issue and the information is already present in the initial post, I assumed I don't need to explain the PowerMock guys how their own code works, so it has of course less detail than the comment where I explained it to you
- "He suggests to add explicit Groovy support to PowerMock, see this comment." Yes, that's why "he" opened this issue. o_O



But to add some really valuable information to the topic, as the main problem here is, that the test class is instrumented on byte-code level and this does not work due to the Groovy dynamicness, an appropriate way to support this would probably be to add an AST transformation that instruments the code before the compiler actually compiles it, either before the Spock transformations are done or after, but I think PowerMock transformations maybe need to be done before.
This way if test are written in Groovy with PowerMock on the compile classpath, the transformations are automatically done before the compiler is run.

**Comment by kriegaex** [comment]
* Sorry for not realising that you are the exact same person who wrote the comment in the other ticket. I could have noticed that but didn't, which is why I called you "he" or "him". Please accept my apology.
* I neither called you a contributor nor a member or maintainer, I kept it fuzzy by calling you "Spock/Groovy guy" in order to avoid false claims.
* Additional detail IMO is new information.
* "Groovy's dynamic language features as I already guessed" refers to the Spock ticket I created and in which I said before your answer and before finding this ticket here: "I assume the problem is related to Groovy code transformations taking place in Spock tests or maybe something about delegates, meta classes or how methods are discovered and called in general. The whole area of Groovy delegates, meta classes etc. is not my area of expertise, so I am asking, sorry." So I did guess in that very direction before you confirmed it to me. (I am happy you did, you clearly know much much more about Groovy than I do.)
