### ISSUE TITLE
mock  java.sql.DriverManager will throw ClassNotPreparedException in jdk 11

### ISSUE THREAD

**Issue by yew1eb** [powermock/powermock#1012]
test class 
```
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import static org.mockito.ArgumentMatchers.nullable;
import static org.powermock.api.mockito.PowerMockito.doNothing;
import static org.powermock.api.mockito.PowerMockito.mock;
import static org.powermock.api.mockito.PowerMockito.mockStatic;
import static org.powermock.api.mockito.PowerMockito.when;

@RunWith(PowerMockRunner.class)
@PrepareForTest({DriverManager.class})
public class DriverManagerTest
{

    @Test
    public void test()
            throws SQLException
    {
        Statement statement = mock(Statement.class);

        Connection mysqlConn = mock(Connection.class);
        mockStatic(DriverManager.class);

        when(mysqlConn.createStatement()).thenReturn(statement);

        when(DriverManager.getConnection(nullable(String.class))).thenReturn(mysqlConn);

        when(statement.execute(nullable(String.class))).thenReturn(true);
        doNothing().when(statement).close();
        doNothing().when(mysqlConn).close();
    }
}

```
dependencies:
[INFO] Used declared dependencies found:
[INFO]    org.powermock:powermock-module-junit4:jar:2.0.2:compile
[INFO]    org.powermock:powermock-api-mockito2:jar:2.0.2:test
[INFO]    org.mockito:mockito-core:jar:2.23.4:test
[INFO]    junit:junit:jar:4.12:test

in jdk11, not work, detail error message:
```

org.powermock.api.mockito.ClassNotPreparedException: 

[Ljava.lang.Object;@76c7beb3
The class java.sql.DriverManager not prepared for test.

	at org.powermock.api.mockito.expectation.reporter.MockitoPowerMockReporter.classNotPrepared(MockitoPowerMockReporter.java:29)
	at org.powermock.api.mockito.internal.mockcreation.MockTypeValidatorFactory$DefaultMockTypeValidator.validate(MockTypeValidatorFactory.java:37)
	at org.powermock.api.mockito.internal.mockcreation.AbstractMockCreator.validateType(AbstractMockCreator.java:10)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMock(DefaultMockCreator.java:49)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.mock(DefaultMockCreator.java:40)
	at org.powermock.api.mockito.PowerMockito.mockStatic(PowerMockito.java:62)
	at DriverManagerTest.test(DriverManagerTest.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

but in jdk8, work well.

**Comment by rrhodes** [comment]
Replicated this issue also. Any updates?

**Comment by TymeFly** [comment]
I'm trying to migrate a code base from Java 8 to Java 11 and am seeing exactly the same problem. The code worked perfectly before the upgrade, but fails under Java 11 with this exact error.

Do we know what is causing this? Is there a fix or a workaround?

**Comment by SaiNikhilYandamuri** [comment]
Even I am facing the same issue. I am trying to upgrade from Java 8 to Java 11. After upgrade when I run my tests it is failing with the same Issue.

**Comment by shobana2** [comment]
Yes I am also facing the same issue. Using junit4 in jdk 11. Powermockito.mockstatic throws this error even @preparefortest is declared at class. Please give me solution for this

**Comment by exceting** [comment]
I‘m also facing the same issue, hope to be solved

**Comment by TerryHuang91** [comment]
same issue

**Comment by zhoutt96** [comment]
same issue

**Comment by MarioAugustin** [comment]
same issue

**Comment by sushma3690** [comment]
Same issue. Any updates on this?

Did anyone apply a workaround? Kindly comment here the workaround, if any.

Thanks :)

**Comment by achakila** [comment]
+1 on this issue

**Comment by gyoga99** [comment]
Same issue, did anyone resolve this?

**Comment by sameer2800** [comment]
+1 on this issue

**Comment by chinmaytotekar** [comment]
+1 We also got same issue. Not able to find any workaround.

**Comment by sanjayprab** [comment]
any update on this issue??

**Comment by kcshettar** [comment]
+1 - same issue

**Comment by kcshettar** [comment]
### This is the work around

Remove the below lines:
`@PrepareForTest({DriverManager.class})`
`mockStatic(DriverManager.class);`
`when(DriverManager.getConnection(nullable(String.class))).thenReturn(mysqlConn);`

Add this line:
`PowerMockito.stub(PowerMockito.method(DriverManager.class, "getConnection", String.class, String.class, String.class)).toReturn(mysqlConn);`
OR
`PowerMockito.stub(PowerMockito.method(DriverManager.class, "getConnection", String.class)).toReturn(mysqlConn);`
