### ISSUE TITLE
java.lang.VerifyError: Expecting a stackmap frame at branch target 38 Exception Details:   Location:     org/easymock/EasyMockSupport.replayAll()V @16: ifeq on using PowerMock Rule to mock new instance creation.

### ISSUE THREAD

**Issue by TahaSaber** [powermock/powermock#1024]
Exception details:
java.lang.VerifyError: Expecting a stackmap frame at branch target 38
Exception Details:
  Location:
    org/easymock/EasyMockSupport.replayAll()V @16: ifeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ab4 0016 b900 7201 004c 2bb9 0078 0100
    0x0000010: 9900 162b b900 7c01 00c0 0021 4d2c b900
    0x0000020: 7f01 00a7 ffe7 b1                      

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.powermock.api.easymock.EasyMockConfiguration.initReallyEasyMock(EasyMockConfiguration.java:53)
	at org.powermock.api.easymock.EasyMockConfiguration.<init>(EasyMockConfiguration.java:34)
	at org.powermock.api.easymock.EasyMockConfiguration.<clinit>(EasyMockConfiguration.java:27)
	at org.powermock.api.extension.listener.AnnotationEnabler.beforeTestMethod(AnnotationEnabler.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1854)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:706)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:415)
	at org.powermock.modules.junit4.rule.PowerMockStatement.injectMocksUsingAnnotationEnabler(PowerMockRule.java:125)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:71)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

**Comment by Vampire** [comment]
Probably fixed by #1043

**Comment by Ipuvi** [comment]
I'm also getting same error. Which should I use to incorporate the latest merged changes?

**Comment by Vampire** [comment]
2.0.7
