### ISSUE TITLE
ConstructorNotFoundException when the constructor is in fact defined

### ISSUE THREAD

**Issue by rchavezt** [powermock/powermock#1031]
Having an own defined exception with multiple constructors, Powermock signs parameter enum types different than standard.

Steps to reproduce:
Have an own defined exception class, and one constructor needs to have an enum as parameter:

```
public class IWSException extends ProtocolException {
    public IWSException( final ErrorCodeEnum errorCode, final String reason, final Throwable cause ){
   
   public IWSException( final ErrorCodeEnum errorCode, final String reason ){
      super(reason);
      this.errorCode = errorCode;
   }
   
   public IWSException( final ErrorCodeEnum errorCode ){
      super("System Error. " + errorCode);
      this.errorCode = errorCode;
   }

   public IWSException( final String reason ){
      super(reason);
      this.errorCode = ErrorCodeEnum.SYS;
   }
   
   public IWSException(Exception cause) {
      super(cause.getMessage(), cause);
      this.errorCode = ErrorCodeEnum.SYS;
   }
}

public enum ErrorCodeEnum {
   CONFIG,
   AUTH, 
   FIELD, 
   SYS
}
```

When throwing the exception:

```
public static boolean validateSuppressedDeal(Deal deal) {
      if (null == deal) {
            throw new IWSException(ErrorCodeEnum.FIELD, "Deal can't be null");
         }
      }
      return true;
   }
```

ConstructorNotFoundException exception is thrown by PowerMock

**Analysis**

getConstructor from WhiteboxImpl get's parameterTypes as:

```
0 = {Class@3430} "class com.exceptions.ErrorCodeEnum"
1 = {Class@576} "class java.lang.String"
```

But when reaches getConstructor0 from Class.java, the static method arrayContentsEq returns

```
0 = {Class@3453} "class com.exceptions.ErrorCodeEnum"
1 = {Class@576} "class java.lang.String"
```

The object for class ErrorCodeEnum is not the same, which throws NoSuchMethodException and ends on a ConstructorNotFoundException

**Comment by rchavezt** [comment]
Stack trace:

```
org.powermock.reflect.exceptions.ConstructorNotFoundException: Failed to lookup constructor with parameter types [ com.iridium.exceptions.ErrorCodeEnum, java.lang.String ] in class com.iridium.exceptions.IWSException.

	at com.iridium.brm.utilties.DealIWSUtil.validateSuppressedDeal(DealIWSUtil.java:123)
	at com.iridium.brm.utilties.DealIWSUtilTest.validateSuppressedDeal(DealIWSUtilTest.java:167)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.NoSuchMethodException: com.iridium.exceptions.IWSException.<init>(com.iridium.exceptions.ErrorCodeEnum, java.lang.String)
	at java.base/java.lang.Class.getConstructor0(Class.java:3350)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2554)
	at org.powermock.reflect.internal.WhiteboxImpl.getConstructor(WhiteboxImpl.java:279)
	at org.powermock.core.MockGateway.newInstanceCall(MockGateway.java:86)
	at com.iridium.brm.utilties.DealIWSUtil.validateSuppressedDeal(DealIWSUtil.java:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.powermock.api.mockito.invocation.InvocationFactory$1.call(InvocationFactory.java:55)
	at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
	at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:152)
	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:43)
	at org.mockito.Answers.answer(Answers.java:100)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:35)
	at org.powermock.api.mockito.invocation.MockHandlerAdaptor.performIntercept(MockHandlerAdaptor.java:64)
	at org.powermock.api.mockito.invocation.MockitoMethodInvocationControl.invoke(MockitoMethodInvocationControl.java:94)
	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:186)
	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:168)
	at org.powermock.core.MockGateway.methodCall(MockGateway.java:145)
	at com.iridium.brm.utilties.DealIWSUtil.validateSuppressedDeal(DealIWSUtil.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1862)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:824)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:689)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at com.iridium.brm.utilties.DealIWSUtilTest.validateSuppressedDeal(DealIWSUtilTest.java:167)
	at com.iridium.brm.utilties.DealIWSUtilTest_$$_jvst7f4_0._d13validateSuppressedDeal(DealIWSUtilTest_$$_jvst7f4_0.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.powermock.modules.testng.internal.PowerMockTestNGMethodHandler.invoke(PowerMockTestNGMethodHandler.java:50)
	at com.iridium.brm.utilties.DealIWSUtilTest_$$_jvst7f4_0.validateSuppressedDeal(DealIWSUtilTest_$$_jvst7f4_0.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by rchavezt** [comment]
To test it:
Converter spiedConverterUnderTest = spy(new Converter());
Whitebox.invokeMethod(spiedConverterUnderTest, "validateSuppressedDeal", null);
