### ISSUE TITLE
Deadlock in tests after upgrading to Powermock 2.0.5

### ISSUE THREAD

**Issue by filpano** [powermock/powermock#1039]
We are using Spring Boot (`2.1.x`) and Powermock (`1.7.4`), and Mockito (`2.28.2`) together. Other environment dependencies include:

* Gradle `5.4.1` (built using `--parallel --max-workers=3`)
* OpenJDK `1.8.0_242`
* Ubuntu Xenial `16.04.6 LTS`

After upgrading from Powermock `1.7.4` to `2.0.5`, we are getting the following deadlock situation while testing (Thread dump):

	Found one Java-level deadlock:
	=============================
	"Thread-7":
	  waiting to lock monitor 0x00007fe088004958 (object 0x00000000f89ab6a0, a java.lang.Object),
	  which is held by "Test worker"
	"Test worker":
	  waiting to lock monitor 0x00007fe088004b68 (object 0x00000000e002adc8, a org.powermock.core.classloader.javassist.JavassistMockClassLoader),
	  which is held by "Thread-7"

	Java stack information for the threads listed above:
	===================================================
	"Thread-7":
		at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:95)
		- waiting to lock <0x00000000f89ab6a0> (a java.lang.Object)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
		at org.powermock.core.classloader.javassist.JavassistMockClassLoader.loadUnmockedClass(JavassistMockClassLoader.java:90)
		at org.powermock.core.classloader.MockClassLoader.loadClassByThisClassLoader(MockClassLoader.java:104)
		at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:147)
		at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:98)
		- locked <0x00000000f8b7b8f8> (a java.lang.Object)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
		at org.powermock.core.classloader.javassist.JavassistMockClassLoader.loadUnmockedClass(JavassistMockClassLoader.java:90)
		at org.powermock.core.classloader.MockClassLoader.loadClassByThisClassLoader(MockClassLoader.java:104)
		at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:147)
		at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:98)
		- locked <0x00000000f8a97258> (a java.lang.Object)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
		at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition$ClassNameFilter.forName(FilteringSpringBootCondition.java:140)
		at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition$ClassNameFilter.isPresent(FilteringSpringBootCondition.java:129)
		at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition$ClassNameFilter$2.matches(FilteringSpringBootCondition.java:117)
		at org.springframework.boot.autoconfigure.condition.OnClassCondition$StandardOutcomesResolver.getOutcome(OnClassCondition.java:234)
		at org.springframework.boot.autoconfigure.condition.OnClassCondition$StandardOutcomesResolver.getOutcome(OnClassCondition.java:220)
		at org.springframework.boot.autoconfigure.condition.OnClassCondition$StandardOutcomesResolver.getOutcomes(OnClassCondition.java:206)
		at org.springframework.boot.autoconfigure.condition.OnClassCondition$StandardOutcomesResolver.resolveOutcomes(OnClassCondition.java:193)
		at org.springframework.boot.autoconfigure.condition.OnClassCondition$ThreadedOutcomesResolver.lambda$new$0(OnClassCondition.java:152)
		at org.springframework.boot.autoconfigure.condition.OnClassCondition$ThreadedOutcomesResolver$$Lambda$240/707413796.run(Unknown Source)
		at java.lang.Thread.run(Thread.java:748)
	"Test worker":
		at java.lang.ClassLoader.checkCerts(ClassLoader.java:881)
		- waiting to lock <0x00000000e002adc8> (a org.powermock.core.classloader.javassist.JavassistMockClassLoader)
		at java.lang.ClassLoader.preDefineClass(ClassLoader.java:662)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:755)
		at org.powermock.core.classloader.javassist.JavassistMockClassLoader.loadUnmockedClass(JavassistMockClassLoader.java:90)
		at org.powermock.core.classloader.MockClassLoader.loadClassByThisClassLoader(MockClassLoader.java:104)
		at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:147)
		at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:98)
		- locked <0x00000000f89ab6a0> (a java.lang.Object)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
		at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition$ClassNameFilter.forName(FilteringSpringBootCondition.java:140)
		at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition$ClassNameFilter.isPresent(FilteringSpringBootCondition.java:129)
		at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition$ClassNameFilter$2.matches(FilteringSpringBootCondition.java:117)
		at org.springframework.boot.autoconfigure.condition.OnClassCondition$StandardOutcomesResolver.getOutcome(OnClassCondition.java:234)
		at org.springframework.boot.autoconfigure.condition.OnClassCondition$StandardOutcomesResolver.getOutcome(OnClassCondition.java:220)
		at org.springframework.boot.autoconfigure.condition.OnClassCondition$StandardOutcomesResolver.getOutcomes(OnClassCondition.java:206)
		at org.springframework.boot.autoconfigure.condition.OnClassCondition$StandardOutcomesResolver.resolveOutcomes(OnClassCondition.java:193)
		at org.springframework.boot.autoconfigure.condition.OnClassCondition.getOutcomes(OnClassCondition.java:58)
		at org.springframework.boot.autoconfigure.condition.FilteringSpringBootCondition.match(FilteringSpringBootCondition.java:51)
		at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.filter(AutoConfigurationImportSelector.java:262)
		at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:125)
		at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:420)
		at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:878)
		at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:804)
		at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:774)
		at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:185)
		at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:315)
		at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
		at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
		at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
		at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
		- locked <0x00000000feb4e640> (a java.lang.Object)
		at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
		at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
		at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
		at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:127)
		at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
		at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
		- locked <0x00000000e0b33760> (a org.springframework.test.context.cache.DefaultContextCache)
		at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
		at de.vectron.cloud.framework.listener.EmbeddedPostgresExecutionListener.beforeTestClass(EmbeddedPostgresExecutionListener.java:20)
		at org.springframework.test.context.TestContextManager.beforeTestClass(TestContextManager.java:215)
		at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:60)
		at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
		at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$2.call(DelegatingPowerMockRunner.java:149)
		at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$2.call(DelegatingPowerMockRunner.java:141)
		at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.withContextClassLoader(DelegatingPowerMockRunner.java:132)
		at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.run(DelegatingPowerMockRunner.java:141)
		at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
		at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
		at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
		at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
		at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
		at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
		at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
		at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
		at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
		at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
		at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
		at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
		at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
		at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
		at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
		at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
		at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
		at java.lang.Thread.run(Thread.java:748)

	Found 1 deadlock.

Of note is that the Spring Boot call stack portion does not seem to be doing anything especially odd, merely delegating to the Powermock `DeferSupportingClassLoader` / `JavassistMockClassLoader`. Additionally, since there is zero user code in the stacktraces, I am inclined to believe that the issue does not lie within the application itself. 

Previously, we were using Powermock `1.7.4` but required an upgrade for some of the new features. We did not experience this deadlock at the time. 

As apparent from the thread dump, it seems that the issue is the following method:

        // DeferSupportingClassLoader:94
        @Override
        protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
            synchronized (getClassLoadingLock(name)) {     // <----------------
                Class<?> clazz = findLoadedClass1(name);
                if (clazz == null) {
                    clazz = loadClass1(name, resolve);
                }
                return clazz;
            }
        }

Whereupon basically both threads seem to be deadlocked by waiting on - essentially, `this`.

Unfortunately, I cannot reproduce the issue locally - the build completes without issue. However, almost every build on our CI pipeline has had the deadlock issue - possibly because the resource contention might be much higher and some synchronized block runtimes being longer or shorter.

Has anyone had this problem before? It sounds *very* similar to what had once been reported in `mockito` (https://github.com/mockito/mockito/issues/1067). However, that bug seems to have been fixed long ago. 

I am currently downgrading the Powermock version we use in an attempt to find where the bug may have been introduced (if my assumption of Powermock being the cause is true). I will update this issue with more information as I get it.

**Comment by filpano** [comment]
Currently, the only way to prevent this issue seems to be downgrading to Powermock `1.7.4` together with Mockito `2.28.2`. The few projects that *do* require the new features have an explicit dependency on the newer Powermock version. 

Since our projects are build in Parallel using Gradle, it seems that this configuration does not trigger the deadlock situation (it is very likely still present, but I could no longer reproduce it).

I have not found any other solution. Unfortunately, I am too unfamiliar with the Powermock code itself to attempt to ascertain the root cause of the issue, and will need feedback to proceed with identifying the cause.

**Comment by orangedy** [comment]
we have the same problem and  it seems to have happened randomly.
