### ISSUE TITLE
PowerMockito.verifyStatic Missing method call for verify(mock) here

### ISSUE THREAD

**Issue by HelloIrisIzurich** [powermock/powermock#1054]
**version:**
powermock-module-junit4:2.0.4
powermock-api-mockito2:2.0.4
mockito-core:3.0.0
junit:4.12

**code**
```
@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(SpringRunner.class)
@PowerMockIgnore({"javax.*.*", "com.sun.*","org.w3c.*", "org.xml.*","javax.management.*", "javax.net.ssl.*"})
@ContextConfiguration(classes= MyUnit.class)
@PrepareForTest({Mystatic.class})
public class MyUnitTest {
    @Autowired
    private MyUnit myUnit;

    @Test
    public void doExecute() throws Exception {
        PowerMockito.mockStatic(Mystatic.class);
        PowerMockito.doReturn("{\"2\":\"1\"}")
            .when(Mystatic.class, "getProperty",any());

        myUnit.doExecute(); // called the static method "getProperty" of "Mystatic" inner the method
        PowerMockito.verifyStatic(MyUnit.class, Mockito.times(1));
    }
}
```

**error**
```
Missing method call for verify(mock) here:
-> at xxxxxxxxxxxxxxxxx

Example of correct verification:
    verify(mock).doSomething()

Also, this error might show up because you verify either of: final/private/equals()/hashCode() methods.
Those methods *cannot* be stubbed/verified.
Mocking methods declared on non-public parent classes is not supported.

org.mockito.exceptions.misusing.UnfinishedVerificationException: 
Missing method call for verify(mock) here:
-> at xxxxxxx

Example of correct verification:
    verify(mock).doSomething()

Also, this error might show up because you verify either of: final/private/equals()/hashCode() methods.
Those methods *cannot* be stubbed/verified.
Mocking methods declared on non-public parent classes is not supported.

	at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:56)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:190)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:187)
	at org.junit.internal.runners.model.EachTestNotifier.fireTestFinished(EachTestNotifier.java:38)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:331)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:364)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by RajendarKumar** [comment]
has anyone found any solution for this issue?

**Comment by ghost** [comment]
it should be PowerMockito.verifyStatic(Mystatic.class, Mockito.times(1));
You verify that the static method was called by providing the static class

**Comment by AllanNobre** [comment]
Same problem here ;-;

**Comment by dattebayorob** [comment]
:-/

**Comment by skalster** [comment]
I have the same problem, after debbuging with a colleague, we suspect the bug is related to the invocationContainer not been added to invocations. So when the MissingInvocationChecker.checkMissingInvocation is always zero.
If you need more information I can post more details to find the bug.

**Comment by Aitozi** [comment]
It seems need to add declare below 

```
Mystatic.getProperty(any())
```

full case 

```
     @Test
    public void mockStatic() {
        PowerMockito.mockStatic(StringUtils.class);
        StringUtils.split("");
        PowerMockito.verifyStatic(StringUtils.class, Mockito.times(1));
        // Declare method to be verify
        StringUtils.split(anyString());
    }
```

**Comment by skalster** [comment]
I tested your suggestion and now I get the error saying wanted but not invoked exactly when the debugger calls the static method.
If I use the evaluate expression from IntelliJ, the first invocation I get the same error. The second invocation goes fine and the test case passes. I'm almost sure this is a bug.

**Comment by Aitozi** [comment]
@skalster I can pass this ok

![image](https://user-images.githubusercontent.com/9486140/127657956-47434d42-320f-4392-b39a-c93c1bfae2fb.png)

**Comment by skalster** [comment]
@Aitozi I don't doubt you, but I don't have the same behaviour. See screenshot:

![Powemorck-problem](https://user-images.githubusercontent.com/9378886/127978281-36de369f-fdb3-4190-9ed8-9e0ac15e11f8.PNG)

**Comment by parthgoyal14** [comment]
> @skalster I can pass this ok
> 
> ![image](https://user-images.githubusercontent.com/9486140/127657956-47434d42-320f-4392-b39a-c93c1bfae2fb.png)

Thanks, this worked for me as well!

**Comment by skalster** [comment]
@parthgoyal14 I'm glad that works for you, but the issue is there for me. My guess is that maybe the system or the configuration makes an impact? You seems using OSX and I use Windows.

**Comment by parthgoyal14** [comment]
> @parthgoyal14 I'm glad that works for you, but the issue is there for me. My guess is that maybe the system or the configuration makes an impact? You seems using OSX and I use Windows.

@skalster I am using Windows OS as well

**Comment by rakshitcgupta** [comment]
This issue appears for me also when upgrading to powermock latest versions

**Comment by maxdemaio** [comment]
Hey all, I tried @Aitozi's solution with the following dependencies with success:

- mockito-core `3.0.0`
- powermock-api-mockito2 `2.0.9`
- powermock-module-junit4 `2.0.9`
- junit `4.13.2`

Oddly enough, it actually is declaring a mocked class' static method used in the `when()` at the very end of the test method. If you have any setup methods, make sure to check those too. For example:

```java
    @Test
    public void test_0() {
        PowerMockito.mockStatic(TesterUtils.class);
        Mockito.when(TesterUtils.print(Mockito.anyString())).thenReturn(true);
        PowerMockito.verifyStatic(TesterUtils.class, Mockito.never());

        // **This is the important part**
        TesterUtils.print(anyString());
    }
```

If you want to verify more than 0 interactions, you still need to call that method before that declaration. Try something like the following:

```java
    @Test
    public void test_1() {
        PowerMockito.mockStatic(TesterUtils.class);
        Mockito.when(TesterUtils.print("Hello")).thenReturn(true);

        assertTrue(TesterUtils.print("Hello"));

        PowerMockito.verifyStatic(TesterUtils.class, atLeast(1));
        TesterUtils.print(anyString());
    }
```

Note, annotate the test class with `@RunWith(PowerMockRunner.class)` and `@PrepareForTest(TesterUtils.class)`.

But, going forward if possible you should try and migrate to the newest version of JUnit and Mockito 👍🏻 . It seems there will be no new versions of PowerMock.

**Comment by MagicWang0907** [comment]
okay,the current solution is to call the static method of your mock again after calling PowerMock.verifyStatic (). I guess his principle is similar to mockitio, and the previous logic will be checked only when it is called next time. I want to know is there a more elegant way to solve this problem?
