### ISSUE TITLE
Powermock giving java.lang.IllegalAccessError in Java 11

### ISSUE THREAD

**Issue by pranavgaba11** [powermock/powermock#1061]
**What steps will reproduce the problem?**
The issue can be reproduced when you try to mock the class DatatypeFactory.

@RunWith(PowerMockRunner.class)
@PrepareForTest(DatatypeFactory.class)
@PowerMockIgnore({"com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "org.w3c.*"})
public class TestClass {  
  @Test(expected = SomeException.class)
  public void test_dateTimeToGregorianCalendar_Negative() throws Exception {
    mockStatic(DatatypeFactory.class);
    Mockito.when(DatatypeFactory.newInstance()).thenThrow(DatatypeConfigurationException.class);
    SomeClass.dateTimeToGregorianCalendar(
        LocalDate.now().atStartOfDay(ZoneId.systemDefault()));
  }}

**I have also tried adding this Java Assist dependency:
compile group: 'org.javassist', name: 'javassist', version: '3.27.0-GA'**

**What is the expected output?**

The test should be successfully executed.

**What do you see instead?**
`java.lang.IllegalAccessError: failed to access class javax.xml.datatype.FactoryFinder from class javax.xml.datatype.DatatypeFactory (javax.xml.datatype.FactoryFinder is in module java.xml of loader 'bootstrap'; javax.xml.datatype.DatatypeFactory is in unnamed module of loader org.powermock.core.classloader.javassist.JavassistMockClassLoader @1061ca4f)`

**What version of the product are you using?** 
    powerMockVersion = '2.0.7'
    powerMockAPIVersion= '2.0.7'

**Comment by jingke** [comment]
I encounter same issue, the error looks like below.

**[ERROR] com.nokia.prs.service.ServiceEngineSenderTest.setUp  Time elapsed: 69.679 s  <<< FAILURE!
java.lang.ClassCastException: class oma.xml.rest.netapi.thirdpartycall._1.CallSessionInformation cannot be cast to class oma.xml.rest.netapi.thirdpartycall._1.CallSessionInformation (oma.xml.rest.netapi.thirdpartycall._1.CallSessionInformation is in unnamed module of loader 'app'; oma.xml.rest.netapi.thirdpartycall._1.CallSessionInformation is in unnamed module of loader org.powermock.core.classloader.javassist.JavassistMockClassLoader @5b247367)**

**Comment by jingke** [comment]
> I encounter same issue, the error looks like below.
> 
> **[ERROR] com.nokia.prs.service.ServiceEngineSenderTest.setUp Time elapsed: 69.679 s <<< FAILURE! java.lang.ClassCastException: class oma.xml.rest.netapi.thirdpartycall._1.CallSessionInformation cannot be cast to class oma.xml.rest.netapi.thirdpartycall._1.CallSessionInformation (oma.xml.rest.netapi.thirdpartycall._1.CallSessionInformation is in unnamed module of loader 'app'; oma.xml.rest.netapi.thirdpartycall._1.CallSessionInformation is in unnamed module of loader org.powermock.core.classloader.javassist.JavassistMockClassLoader @5b247367)**

@pranavgaba11 I added "oma.xml.*" in PowerMockIgnore and solved my issue, I checked your PowerMockIgnore, it seems it's missing "*" for "javax.xml.", you can add it and try it again.

@PowerMockIgnore({"com.sun.org.apache.xerces.", "javax.xml.", "org.xml.", "org.w3c."})

**Comment by pranavgaba11** [comment]
@jingke I tried adding @PowerMockIgnore({"com.sun.org.apache.xerces.", "javax.xml.", "org.xml.", "org.w3c."})

I also tried @PowerMockIgnore({"com.sun.org.apache.xerces.*[Asterisk]", "javax.xml.*[Asterisk]", "org.xml.*[Asterisk]", "org.w3c.*[Asterisk]"})

It did not resolve the issue. The issue still persists.

**Comment by lzcjames** [comment]
Hi, I have the same issue in Powermock 2.0.7 and Java 11, by adding 
```
@PowerMockIgnore({"com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "javax.management.*"})
```
it worked.

the another solution is [here](https://github.com/powermock/powermock/issues/864#issuecomment-546324343), but I have not tested.

**Comment by mkemmerz** [comment]
I am not able to fix this issue with the annotations mentioned here (using Java 11, Lombok Plugin @Slf4j + PowerMockito 2.0.4), sadly. Any further ideas?

I am using the following annotation:
 `@PowerMockIgnore({"javax.net.ssl.*", "org.slf4j.*", "javax.parsers.*", "ch.qos.logback.*", "jdk.xml.internal.*", "com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "javax.management.*"})
`
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.powermock.reflect.internal.WhiteboxImpl (file:/C:/Users/<>/.m2/repository/org/powermock/powermock-reflect/2.0.4/powermock-reflect-2.0.4.jar) to method java.lang.Object.clone()
WARNING: Please consider reporting this to the maintainers of org.powermock.reflect.internal.WhiteboxImpl
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

java.lang.IllegalAccessError: class javax.xml.parsers.FactoryFinder (in unnamed module @0x37045b48) cannot access class jdk.xml.internal.SecuritySupport (in module java.xml) because module java.xml does not export jdk.xml.internal to unnamed module @0x37045b48

	at javax.xml.parsers.FactoryFinder.<clinit>(FactoryFinder.java:69)
	at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:219)
	at ch.qos.logback.core.joran.event.SaxEventRecorder.buildSaxParser(SaxEventRecorder.java:79)
	at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SaxEventRecorder.java:57)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:151)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at <>
	at <>
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

**Comment by lzcjames** [comment]
> cannot access class jdk.xml.internal.SecuritySupport

Someone said that the issue is also present in Powermock 2.0.4 and java 11, here is his [solution](https://github.com/powermock/powermock/issues/864#issuecomment-546324343)

**Comment by lzcjames** [comment]
@mkemmerz
Someone said that the issue is also present in Powermock 2.0.4 and java 11, here is his [solution](https://github.com/powermock/powermock/issues/864#issuecomment-546324343)

**Comment by mkemmerz** [comment]
We were able to fix it. We missed 1 class that was using PowerMock so we had to add the annotation there as well, thanks for the help @lzcjames

**Comment by lzcjames** [comment]
@mkemmerz no problem 👍

**Comment by nashikanta** [comment]
I am also facing similar issue. Any body know the exact fix for this

springboot version: 2.5.0,
powermock: 2.0.7

**_code snippet_:** 
        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.add("Authorization", "Bearer " + token);
        httpHeaders.add(ConfigurationService.TENANT, tenant);
        MockServerHttpRequest request = MockServerHttpRequest.get("")
                .headers(httpHeaders).build();
        return MockServerWebExchange.from(request);

**_stackTrace:_**
org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.http.codec.support.DefaultServerCodecConfigurer]: Constructor threw exception; nested exception is java.lang.IllegalAccessError: class javax.xml.stream.FactoryFinder (in unnamed module @0x46468f0) cannot access class jdk.xml.internal.SecuritySupport (in module java.xml) because module java.xml does not export jdk.xml.internal to unnamed module @0x46468f0

	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:225)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	at org.springframework.http.codec.CodecConfigurerFactory.create(CodecConfigurerFactory.java:72)
	at org.springframework.http.codec.ServerCodecConfigurer.create(ServerCodecConfigurer.java:76)
	at org.springframework.mock.web.server.MockServerWebExchange.<init>(MockServerWebExchange.java:44)
	at org.springframework.mock.web.server.MockServerWebExchange.<init>(MockServerWebExchange.java:40)
	at org.springframework.mock.web.server.MockServerWebExchange$Builder.build(MockServerWebExchange.java:134)
	at org.springframework.mock.web.server.MockServerWebExchange.from(MockServerWebExchange.java:60)

**Comment by deveshgoyal2810** [comment]
@pranavgaba11  Did you find the resolution of the issue as I am also facing same issue with almost same stack trace 
`java.lang.IllegalAccessError: failed to access class 
	javax.xml.parsers.FactoryFinder from class javax.xml.parsers.DocumentBuilderFactory (javax.xml.parsers.FactoryFinder is in module java.xml of loader 'bootstrap'; javax.xml.parsers.DocumentBuilderFactory is in unnamed module of loader org.powermock.core.classloader.javassist.JavassistMockClassLoader @3258e912)`
