### ISSUE TITLE
Powermock not working with Open Jdk 11

### ISSUE THREAD

**Issue by Staticsubh** [powermock/powermock#1076]
Hi, 

We are using powermock 2.0.2 along with Easymock and Openjdk 11. The test cases were running smooth until will upgraded to Open jdk 11. We are getting the below exception now :

```
java.lang.ClassFormatError: Nest member class_info_index 39 has bad constant type in class file com/gehcit/cp/cem/filter/LocFilterTest
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:287)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:192)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:77)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:67)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:161)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:48)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:111)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:71)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:34)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:76)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:526)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)

	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

Can anyone hep us resolve this. We also tried upgrading to Javaassist 3.27.0GA jar with junit 4.12. but no help. I am attaching the test file as well.
[LocaFilter_exception.txt](https://github.com/powermock/powermock/files/5355962/LocaFilter_exception.txt)

**Comment by Staticsubh** [comment]
@thekingn0thing @ijuma @matitalatina @lzcjames Can you please help here?

**Comment by lzcjames** [comment]
> @thekingn0thing @ijuma @matitalatina @lzcjames Can you please help here?

Hello, it seems to be an issue with PowerMock library version, reported in PowerMock [Issue 933](https://github.com/powermock/powermock/issues/933) .
Could you check your maven dependencies using mvn dependency:tree for javassist?

**Comment by Staticsubh** [comment]
> > @thekingn0thing @ijuma @matitalatina @lzcjames Can you please help here?
> 
> Hello, it seems to be an issue with PowerMock library version, reported in PowerMock [Issue 933](https://github.com/powermock/powermock/issues/933) .
> Could you check your maven dependencies using mvn dependency:tree for javassist?

Yes We checked the same. 
We are using Javassist 3.27.0GA build with powermock 2.0.2. The issue is still there.

**Comment by Staticsubh** [comment]
> mvn dependency:tree for javassist

This is the output of mv dependency tree:

Copying hamcrest-all-1.3.jar to \SelfDig\Jaavassist\hamcrest-all-1.3.jar
[INFO] Copying jrt-fs.jar to \SelfDig\Jaavassist\tools-11.0.8.jar
[INFO] Copying hamcrest-core-1.3.jar to \SelfDig\Jaavassist\hamcrest-core-1.3.jar
[INFO] Copying junit-4.12.jar to SelfDig\Jaavassist\junit-4.12.jar

We already have all the jars present in our classpath.

**Comment by Staticsubh** [comment]
The issue got fixed. We had to move the file reference above the Redhat Jboss libraries in the classpath to get rid of the error.
Thanks everyone.
