### ISSUE TITLE
Mocking Google GeoAPI DistanceMatrix fails with NullPointerException: Mokito 3.6.0, Powermock 2.0.9, JUnit5, SpringBoot 2.3.5 Failing

### ISSUE THREAD

**Issue by marcellodesales** [powermock/powermock#1078]
# Is this something you can debug and fix?

* I can debug, I see the `null` value, but I can't tell why the property is initialized as `null`
* Followed instructions from https://www.infoworld.com/article/3543268/junit-5-tutorial-part-2-unit-testing-spring-mvc-with-junit-5.html
* Tried similar approach as to using the 2.x API https://stackoverflow.com/questions/35641902/how-can-i-mock-googles-geocoding-api-request-using-mockito-powermock, adjusting for 3.x version
-------------------------------------------------------

# Can you see anything in the logs? Can you debug why this happens?

* The test fails with a `NullPointerException` with the setup 

```java
    DistanceMatrixApiRequest distanceMatrixRequest = PowerMockito.mock(DistanceMatrixApiRequest.class);
```

* `distancematrix.DistanceMatrixServiceTests.testGetDistanceMatrixForAddresses(DistanceMatrixServiceTests.java:87)` is exactly the `await()` method call... But it has been mocked with `when`
`when(distanceMatrixRequest.await()).thenReturn(distanceMatrixResult);`
* The property `config`, from the resulting class of calling `await()` of the `PowerMockito.mock`, is null. 

<img width="1410" alt="Screen Shot 2020-11-04 at 12 14 24 PM" src="https://user-images.githubusercontent.com/131457/98128983-5b902380-1e97-11eb-9034-bca938699b82.png">

```java
java.lang.NullPointerException
	at com.google.maps.PendingResultBase.makeRequest(PendingResultBase.java:80)
	at com.google.maps.PendingResultBase.await(PendingResultBase.java:57)
	at ....distancematrix.DistanceMatrixServiceTests.testGetDistanceMatrixForAddresses(DistanceMatrixServiceTests.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:141)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```

-----------

# Is the ExtendsWith correct? Why's the mock null?

* Then the Test Class is failing... `DistanceMatrixService` is where the call is...
* Tried to implement this in Mokito 3 similar to https://stackoverflow.com/questions/35641902/how-can-i-mock-googles-geocoding-api-request-using-mockito-powermock

```java
package ....service.distancematrix;

import static org.junit.jupiter.api.Assertions.assertSame;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.when;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import com.google.maps.DirectionsApi.RouteRestriction;
import com.google.maps.DistanceMatrixApi;
import com.google.maps.DistanceMatrixApiRequest;
import com.google.maps.GeoApiContext;
import com.google.maps.GeocodingApi;
import com.google.maps.model.Distance;
import com.google.maps.model.DistanceMatrix;
import com.google.maps.model.DistanceMatrixElement;
import com.google.maps.model.DistanceMatrixRow;
import com.google.maps.model.Duration;
import com.google.maps.model.TravelMode;
import ....distancematrix.model.DistanceMatrixAddresses;
import....service.distancematrix.model.DistanceMatrixResult;

// https://stackoverflow.com/questions/63834940/springboot-cant-resolve-runwith-cannot-find-symbol/63835256#63835256
// https://www.baeldung.com/mockito-junit-5-extension
@SpringBootTest(properties = {"....distancematrix.googleMapsApiToken=fake-token"})
@DisplayName("Distance Matrix Service Tests Mocking Google GeoAPI")
public class DistanceMatrixServiceTests {

  private static final String ORIGIN = "Maceio, Alagoas, Brazil";
  private static final String DESTINATION = "Recife, Pernambuco, Brazil";

  @Autowired
  private DistanceMatrixProperties properties;

  @Mock
  private GeoApiContext geoApiContext;


  @InjectMocks
  private DistanceMatrixService service;

  @Test
  @DisplayName("Test Get Distance Matrix Success")
  public void testGetDistanceMatrixForAddresses() throws Exception {
    DistanceMatrixAddresses addresses = new DistanceMatrixAddresses();
    addresses.setDestinationAddress(DESTINATION);
    addresses.setOriginAddress(ORIGIN);

    DistanceMatrixElement element = new DistanceMatrixElement();
    element.distance = new Distance();
    element.distance.inMeters = 300L;
    element.duration = new Duration();
    element.duration.inSeconds = 44L;

    DistanceMatrixRow row = new DistanceMatrixRow();
    row.elements = new DistanceMatrixElement[] {element};

    DistanceMatrix distanceMatrixResult = new DistanceMatrix(
        new String[] {ORIGIN}, new String[]{DESTINATION}, new DistanceMatrixRow[]{row});

    DistanceMatrixApiRequest distanceMatrixRequest = PowerMockito.mock(DistanceMatrixApiRequest.class);
    when(distanceMatrixRequest.origins(ORIGIN)).thenReturn(distanceMatrixRequest);
    when(distanceMatrixRequest.destinations(DESTINATION)).thenReturn(distanceMatrixRequest);
    when(distanceMatrixRequest.mode(TravelMode.DRIVING)).thenReturn(distanceMatrixRequest);
    when(distanceMatrixRequest.avoid(RouteRestriction.TOLLS)).thenReturn(distanceMatrixRequest);
    when(distanceMatrixRequest.language(properties.getLanguage())).thenReturn(distanceMatrixRequest);

    // --------------->>>>>> NULL POINTER EXCEPTION RIGHT HERE ON wait()
    when(distanceMatrixRequest.await()).thenReturn(distanceMatrixResult);

    mockStatic(GeocodingApi.class);

    when(DistanceMatrixApi.newRequest(eq(geoApiContext))).thenReturn(distanceMatrixRequest);

    DistanceMatrixResult calculatedResult = service.getDriveDistance(addresses);

    assertSame(distanceMatrixResult, calculatedResult);
  }

}
```

# Should I be using anything else? Is this question about PowerMock usage?

# What steps will reproduce the problem? What version of the product are you using? 

```gradle
dependencies {
    // Testing Frameworks
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }

    // Mockito
    testImplementation('org.mockito:mockito-core:3.6.0')
    testImplementation('org.mockito:mockito-junit-jupiter:3.6.0')
    testImplementation('org.powermock:powermock-api-mockito2:2.0.9')

}

test {
  useJUnitPlatform()
  ignoreFailures = false
  maxParallelForks = 1
  testLogging {
     showStandardStreams = true
     events("skipped", "failed")
  }
}
```

# Subject to Mock

* The Google Geo API for distance matrix (external API call)

```java
...
...  
  /**
   * The API is very expensive to be built
   */
  private GeoApiContext geoApi;

    // Inside of a Google Guave Cache load method...

          // The calculation from Google
    DistanceMatrix calculationResult;
      DistanceMatrixApiRequest req = DistanceMatrixApi.newRequest(geoApi);

      calculationResult = req.origins(addresses.getOriginAddress())
            .destinations(addresses.getDestinationAddress())
            .mode(TravelMode.DRIVING)
            .avoid(RouteRestriction.TOLLS)
            .language(properties.getLanguage())
            .await();
```

**Comment by deconinckd** [comment]
Following  the thread as I have a similar issue on my test case where it gives a NPE on the await() and makerequest(), tried al kinds of things to make the api mock the await() call but it seems to always going into the funtion.

Simply trying to mock the PlacesApi.placeDetails & PlacesApi.placeAutocomplete which gets the same error as the thread starter

```
@ExtendWith(MockitoExtension.class)
@RunWith(PowerMockRunner.class)
@PrepareForTest({PlacesApi.class, PlaceDetailsRequest.class, PlaceAutocompleteRequest.class})
public class GoogleServiceTest {

@Mock
private GeoApiContext geoApiContext;
	
@Mock
private PlacesApi placesApi;
.....
... @Test ... 
PlaceDetailsRequest placeDetailRequest = mock(PlaceDetailsRequest.class);
//Mockito.lenient().when(placeDetailRequest.placeId(Mockito.anyString())).thenReturn(placeDetailRequest);
when(placeDetailRequest.await()).thenReturn(placeDetailResults);

mockStatic(PlacesApi.class);

when(PlacesApi.placeDetails(Mockito.any(), Mockito.any(), Mockito.any(SessionToken.class))).thenReturn(placeDetailRequest);
	        
Test city place details
Optional<PlaceDetails> placeDetails = googleService.getPlaceById(placeId);
assertTrue(placeDetails.isPresent());

```
result => Caused by: java.lang.NullPointerException
	at com.google.maps.PendingResultBase.makeRequest(PendingResultBase.java:80)
	at com.google.maps.PendingResultBase.await(PendingResultBase.java:57)
	at eu.europa.europarl.mop.service.GoogleServiceTest.cityDetailTestCase(GoogleServiceTest.java:143)
	... 65 more

**Comment by deconinckd** [comment]
For your information, I found the issue and it is because powermock is not compatible with JUnit 5.

Powermock is not working in JUnit 5 so you will need to use JUnit 4 for this. When I changed the runner and the other annotations to JUnit 4 it worked fine.

I also read that mockito version 3.4 and 3.5 also have static method support. Might be worth to look into.

**Comment by deconinckd** [comment]
Apparently in JUnit 5 there is a vintage runner to run it as JUnit 4 under JUnit 5 you could try that as well. For example I made it all work with JUnit 5 by using the JUnit 4 tags & imports and by using the vintage engine. 

e.g.

you need to make sure the vintage is not excluded or add it
<groupId>org.junit.vintage</groupId>
<artifactId>junit-vintage-engine</artifactId> 

```
@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(MockitoJUnitRunner.class)
@PrepareForTest({PlacesApi.class, PlaceDetailsRequest.class, PlaceAutocompleteRequest.class, TimeZoneApi.class})
public class GoogleServiceTest {

        @Mock
	private LocationRepository locationRepository;
	
	@InjectMocks
	private GoogleServiceImpl googleService;
	
	@Mock
	private GeoApiContext geoApiContext;
	
	@Mock
	private PlacesApi placesApi;

        @Before
	public void before() {
		assertEquals(Mockito.mockingDetails(locationRepository).isMock(), true, "the locationrepository should be mocked");
		googleService = new GoogleServiceImpl(geoApiContext);
	}

	@Test // make sure it is the junit 4 one from org.junit.Test
	public void testGetPredictions() {
		
		List<GoogleLocationSuggestion> locationSuggestionList = null;
		try {
			AutocompletePrediction[] predictionsArray = new AutocompletePrediction[1];
			AutocompletePrediction autoPred = new AutocompletePrediction();
			autoPred.description = "test";
			autoPred.placeId = "test place id";
			predictionsArray[0] = autoPred;
			
			PlaceAutocompleteRequest pcr = mock(PlaceAutocompleteRequest.class);
			when(pcr.language(Mockito.anyString())).thenReturn(pcr);
			when(pcr.await()).thenReturn(predictionsArray);
			
			mockStatic(PlacesApi.class);
			
			when(PlacesApi.placeAutocomplete(Mockito.any(), Mockito.anyString(), Mockito.any(SessionToken.class)))
			.thenReturn(pcr);
			
			locationSuggestionList = googleService.getPlacesPredictions("test", Optional.of(PlaceAutocompleteType.CITIES));
			
		} catch (MOPException | ApiException | InterruptedException | IOException e) {
			fail("The google api should not fail");
		}
		
		assertNotNull(locationSuggestionList);
		assertTrue(locationSuggestionList.size()>0);
		assertEquals(locationSuggestionList.get(0).getDescription(), "test");
		assertEquals(locationSuggestionList.get(0).getPlaceId(), "test place id");
	}
```

**Comment by sauarum** [comment]
Had similar issue in my projects so for some active small project we so had to switch away from powermock and use mocikto-inline to mock static methods.

I hope this junit 5 and powermock issue is fixed soon.
