### ISSUE TITLE
java.lang.annotation.AnnotationFormatError: Attempt to create proxy for a non-annotation type.

### ISSUE THREAD

**Issue by 13451433907** [powermock/powermock#1086]
there is a exception when @PrepareEverythingForTest in testClass . because the powermock will add interface PowerMockModified to every class that mocked,include the type annotion.
java.lang.annotation.AnnotationFormatError: Attempt to create proxy for a non-annotation type.

	at sun.reflect.annotation.AnnotationInvocationHandler.<init>(AnnotationInvocationHandler.java:52)
	at sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:306)
	at sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:303)

**Comment by martijndormans** [comment]
I got the same error but with different reflect classes:
```
java.lang.annotation.AnnotationFormatError: Attempt to create proxy for a non-annotation type.
	at java.base/sun.reflect.annotation.AnnotationInvocationHandler.<init>(AnnotationInvocationHandler.java:53)
	at java.base/sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:307)
	at java.base/sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:304)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.reflect.annotation.AnnotationParser.annotationForMap(AnnotationParser.java:304)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:294)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
	at java.base/java.lang.reflect.Field.declaredAnnotations(Field.java:1175)
	at java.base/java.lang.reflect.Field.declaredAnnotations(Field.java:1173)
	at java.base/java.lang.reflect.Field.getAnnotation(Field.java:1142)
	at java.base/java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:274)
	at java.base/java.lang.reflect.AccessibleObject.isAnnotationPresent(AccessibleObject.java:517)
	at org.powermock.reflect.internal.matcherstrategies.FieldAnnotationMatcherStrategy.matches(FieldAnnotationMatcherStrategy.java:37)
```
