### ISSUE TITLE
Powermock with JDK16 fails

### ISSUE THREAD

**Issue by rk99d339** [powermock/powermock#1094]
We running our project with jdk11 powermock 2.09 and junit 4.13.2
Since jdk16 is now official released we tested our software with this. 

Compile is fine but if we run the Junit Test they fails with the following error.

    `java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @1175e2db
    
	    at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	    at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	    at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	    at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	    at org.powermock.reflect.internal.WhiteboxImpl.doGetAllMethods(WhiteboxImpl.java:1508)
	    at org.powermock.reflect.internal.WhiteboxImpl.getAllMethods(WhiteboxImpl.java:1482)
	    at org.powermock.reflect.internal.WhiteboxImpl.findMethodOrThrowException(WhiteboxImpl.java:862)
	    at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:822)
	    at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:805)
	    at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:466)
	    at org.powermock.modules.junit4.common.internal.impl.PowerMockJUnit4RunListener.testFinished(PowerMockJUnit4RunListener.java:55)
	    at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:87)
	    at org.junit.runner.notification.RunNotifier$9.notifyListener(RunNotifier.java:225)
	    at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	    at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:222)
	    at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:53)
	    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
	    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
	    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
	    at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	    at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
	    at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
	    at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	    at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	    at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	    at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	    at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
`

A small Test to reproduce this behavor
`
          import org.junit.Test;
          import org.junit.runner.RunWith;
          import org.powermock.core.classloader.annotations.PowerMockIgnore;
          import org.powermock.modules.junit4.PowerMockRunner;
      
      @RunWith(PowerMockRunner.class)
      @PowerMockIgnore({ "com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "org.w3c.*" })
      public class PowerMockTest {
      
          @Test
          public void test() {
      
          }
      }

`

**Comment by DivideMeByZero** [comment]
Would you please comment on that, developers?

**Comment by TheBusyBiscuit** [comment]
I am able to reproduce this issue as well using the following project:
https://github.com/mcMMO-Dev/mcMMO

I originally (falsely) reported this on the Junit bug tracker:
https://github.com/junit-team/junit5/issues/2648

**Comment by mohit-quo** [comment]
Any resolutions for this? Facing this on openjdk 17, can anyone suggest dependencies for powermock suitable with openjdk 17?

**Comment by rk99d339** [comment]
We upgraded to Junit5, and by that we no longer need Powermock to mock static classes. About 12k tests. Took us about a month of work to test and fix everything. 
But there  a maven plugin which helps you to change all imports and annotations. 
https://docs.openrewrite.org/tutorials/migrate-from-junit-4-to-junit-5
You need only replace Powermock by hand to Junit5 

Our software is now running fine with jdk17. 
This effort was totaly worth it. thx Erni ;-)

Syncerely Rolf

**Comment by Nyamiou** [comment]
Would a small modification like that work?:

```
Index: powermock-reflect/src/main/java/org/powermock/reflect/internal/WhiteboxImpl.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/powermock-reflect/src/main/java/org/powermock/reflect/internal/WhiteboxImpl.java b/powermock-reflect/src/main/java/org/powermock/reflect/internal/WhiteboxImpl.java
--- a/powermock-reflect/src/main/java/org/powermock/reflect/internal/WhiteboxImpl.java	(revision a0be5c4bbeb04f13a6aec2653c1f5663cece1316)
+++ b/powermock-reflect/src/main/java/org/powermock/reflect/internal/WhiteboxImpl.java	(date 1661349367951)
@@ -1505,7 +1505,13 @@
             });
             for (Method method : declaredMethods) {
                 if(!"finalize".equals(method.getName())) {
-                    method.setAccessible(true);
+                    try {
+                        method.setAccessible(true);
+                    } catch (RuntimeException e) {
+                        if (!e.getClass().getName().equals("java.lang.reflect.InaccessibleObjectException")) {
+                            throw e;
+                        }
+                    }
                     methods.add(method);
                 }
             }
```

Or is there something broken by not making those methods accessible?

**Comment by dmlarionov** [comment]
That's solution for users affected by the issue - tune your JVM options, opening classes for access (--add-opens / --add-exports).

Since [Java modularized](https://www.oracle.com/corporate/features/understanding-java-9-modules.html) one module can't just get access to another using reflection.

If you use maven and surefire plugin, please, add to your pom.xml the following:

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        --add-opens java.base/java.lang=ALL-UNNAMED
                        --add-opens java.base/java.time=ALL-UNNAMED
                        --add-opens java.base/java.time.format=ALL-UNNAMED
                        --add-opens java.base/java.util=ALL-UNNAMED
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>

Tune agrLine as you need!
