### ISSUE TITLE
powermock-api-mockito2 does not work with Mockito 4 due to using deprecated API(s)

### ISSUE THREAD

**Issue by m2ger** [powermock/powermock#1109]
Using powermock-api-mockito2 2.0.9.

With mockito 3.12.4 this code works fine:

```java
import org.mockito.Mock;
import org.powermock.modules.testng.PowerMockTestCase;
import org.testng.annotations.Test;

public class SimpleTest extends PowerMockTestCase {

    @Mock
    private SimpleInterface simpleInterface;

    @Test
    public void testSimpleTest() {
        
    }

    interface SimpleInterface {}
}
```

but with the newly released [mockito 4.0.0](https://github.com/mockito/mockito/releases/tag/v4.0.0), the following Exception is thrown:

```
java.lang.NoSuchMethodError: org.mockito.Answers.get()Lorg/mockito/stubbing/Answer;

	at org.powermock.api.extension.listener.AnnotationEnabler.standardInject(AnnotationEnabler.java:85)
	at org.powermock.api.extension.listener.AnnotationEnabler.beforeTestMethod(AnnotationEnabler.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1864)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:715)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:415)
	at org.powermock.modules.testng.PowerMockTestCase.injectMocks(PowerMockTestCase.java:135)
	at org.powermock.modules.testng.PowerMockTestCase.beforePowerMockTestMethod(PowerMockTestCase.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
```

Due to removal of this deprecated method in `org.mockito.Answers`:

```java
    /** @deprecated */
    @Deprecated
    public Answer<Object> get() {
        return this;
    }
```

`org.powermock.api.extension.listener.AnnotationEnabler#standardInject`
```java
                if (answers != null) {
                    mockSettings.defaultAnswer(answers.get());
                }
```

**Comment by prashanthdesu** [comment]
Hi, I am also facing same issue. Is there any way to fix it without downgrading the mockito-core from 4.0.0 to 3.12.4

**Comment by m2ger** [comment]
I know this is not the answer You want to hear, but we upgraded Mockito to 4.0.0 and stopped using PowerMock altogether because Mockito allows to mock static methods since [3.4.0,](https://github.com/mockito/mockito/releases/tag/v3.4.0) which was the only reason we used PowerMock.

**Comment by apal-ebay** [comment]
how does Mockito 4.0.0 support to mock private method?

**Comment by apalcloud** [comment]
how does Mockito 4.0.0 support to mock private method?

**Comment by lucasvc** [comment]
After digging, I have found the merged https://github.com/powermock/powermock/pull/1113 probably solves this issue.

**Comment by larrywest42** [comment]
As lucasvc said (above) in October, the merge of #1113 should fix this issue, but @thekingn0thing stated [there](https://github.com/powermock/powermock/pull/1113#issuecomment-1054646251) back in February, they don't have the infrastructure to do a release.

Merging #1113 back in February 2022 was the [last commit](https://github.com/powermock/powermock/commits/release/2.x) on the default branch, and the last release (2.0.9) was two years ago (November 2020).

As m2ger suggested above, switching to current Mockito seems to be the most viable course of action for those of us needing to mock statics (or constructors) in code that can't be refactored.

**Comment by donnieYeh** [comment]
I suffer from same issue，This problem may arise from the rewriting of the mockito dependency version by parent pom.
In my issue，the parent pom, spring-boot-dependency, specify the mockito version to 4.5.1, but powermock 2.0.9 is acceptable with version 3.3.3 which was rewrited to 4.5.1. After i respecify the version to 3.3.3 it work fine！

**Comment by MominAyesha-13** [comment]
How can i mock a static void method without using powemockito. as  i am also facing the same issue.
