### ISSUE TITLE
Powermockito 2.0.9+Robelectric 4.6.1组合使用, run运行没问题，执行gradle test报错

### ISSUE THREAD

**Issue by chenyan-master** [powermock/powermock#1111]
class org.powermock.api.mockito.invocation.MockitoMethodInvocationControl cannot be cast to class org.powermock.api.mockito.invocation.MockitoMethodInvocationControl (org.powermock.api.mockito.invocation.MockitoMethodInvocationControl is in unnamed module of loader org.powermock.core.classloader.javassist.JavassistMockClassLoader @2c86d526; org.powermock.api.mockito.invocation.MockitoMethodInvocationControl is in unnamed module of loader org.powermock.core.classloader.javassist.JavassistMockClassLoader @399408ba)
java.lang.ClassCastException: class org.powermock.api.mockito.invocation.MockitoMethodInvocationControl cannot be cast to class org.powermock.api.mockito.invocation.MockitoMethodInvocationControl (org.powermock.api.mockito.invocation.MockitoMethodInvocationControl is in unnamed module of loader org.powermock.core.classloader.javassist.JavassistMockClassLoader @2c86d526; org.powermock.api.mockito.invocation.MockitoMethodInvocationControl is in unnamed module of loader org.powermock.core.classloader.javassist.JavassistMockClassLoader @399408ba)
	at org.powermock.api.mockito.mockmaker.PowerMockMaker.getRealMock(PowerMockMaker.java:58)
	at org.powermock.api.mockito.mockmaker.PowerMockMaker.instanceMockHandler(PowerMockMaker.java:54)
	at org.powermock.api.mockito.mockmaker.PowerMockMaker.getHandler(PowerMockMaker.java:49)
	at org.mockito.internal.util.MockUtil.isMock(MockUtil.java:81)
	at org.mockito.internal.util.MockUtil.getMockHandler(MockUtil.java:58)
	at org.mockito.internal.stubbing.answers.InvocationInfo.isVoid(InvocationInfo.java:52)
	at org.mockito.internal.stubbing.answers.Returns.validateFor(Returns.java:32)
	at org.mockito.internal.stubbing.InvocationContainerImpl.addAnswer(InvocationContainerImpl.java:70)
	at org.mockito.internal.stubbing.InvocationContainerImpl.addAnswer(InvocationContainerImpl.java:56)
	at org.mockito.internal.stubbing.OngoingStubbingImpl.thenAnswer(OngoingStubbingImpl.java:32)
	at org.mockito.internal.stubbing.BaseStubbing.thenReturn(BaseStubbing.java:35)
	at com.wps.woa.module.location.utils.LocationUtilTest.getAndSaveMyLocation(LocationUtilTest.kt:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1864)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:825)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:690)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.classloading.AbstractClassloaderExecutor.getResult(AbstractClassloaderExecutor.java:76)
	at org.powermock.classloading.AbstractClassloaderExecutor.invokeWithClassLoader(AbstractClassloaderExecutor.java:64)
	at org.powermock.classloading.AbstractClassloaderExecutor.executeWithClassLoader(AbstractClassloaderExecutor.java:56)
	at org.powermock.classloading.SingleClassloaderExecutor.execute(SingleClassloaderExecutor.java:33)
	at org.powermock.classloading.AbstractClassloaderExecutor.execute(AbstractClassloaderExecutor.java:40)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:75)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by baderBoy** [comment]
@chenyan-master 我也遇到了同样的问题，请问你解决了吗
