### ISSUE TITLE
NoSuchMethodError: 'org.mockito.invocation.InvocationFactory.createInvocation(java.lang.Object, org.mockito.mock.MockCreationSettings, java.lang.reflect.Method, java.util.concurrent.Callable, java.lang.Object[])'

### ISSUE THREAD

**Issue by liweiye-2021** [powermock/powermock#1124]
<dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4</artifactId>
            <version>2.0.0</version>
            <scope>test</scope>

        </dependency>

        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-mockito2</artifactId>
            <version>2.0.0</version>
            <scope>test</scope>
        </dependency>

@RunWith(PowerMockRunner.class)
@PowerMockIgnore({ "javax.management.*" }) 
@PrepareForTest({ TradeDateUtils.class }) 
public class TestOne {

    @Test
    public void test11() throws Throwable {
        PowerMockito.mockStatic(TradeDateUtils.class);
        PowerMockito.when(TradeDateUtils.queryDayTradeOffset(anyString(), anyInt())).thenReturn("2021-12-01");
        Assert.assertEquals("2021-12-02", TradeDateUtils.queryDayTradeOffset("",1));

    }
}

java 17 SDK

java.lang.NoSuchMethodError: 'org.mockito.invocation.Invocation org.mockito.invocation.InvocationFactory.createInvocation(java.lang.Object, org.mockito.mock.MockCreationSettings, java.lang.reflect.Method, java.util.concurrent.Callable, java.lang.Object[])'

	at org.powermock.api.mockito.invocation.InvocationFactory.createInvocation(InvocationFactory.java:41)
	at org.powermock.api.mockito.invocation.MockHandlerAdaptor.createInvocation(MockHandlerAdaptor.java:81)
	at org.powermock.api.mockito.invocation.MockHandlerAdaptor.performIntercept(MockHandlerAdaptor.java:61)
	at org.powermock.api.mockito.invocation.MockitoMethodInvocationControl.invoke(MockitoMethodInvocationControl.java:93)
	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:186)
	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:168)

**Comment by liweiye-2021** [comment]
<dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4</artifactId>
            <version>2.0.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-mockito2</artifactId>
            <version>2.0.0</version>
            <scope>test</scope>
        </dependency>
