### ISSUE TITLE
powermock2.0.2  fail  for NoSuchMethodError InvocationFactory.createInvocation(java.lang.Object, org.mockito.mock.MockCreationSettings, java.lang.reflect.Method, java.util.concurrent.Callable, java.lang.Object[])'

### ISSUE THREAD

**Issue by liweiye-2021** [powermock/powermock#1125]
dependency:

```
<dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4</artifactId>
            <version>2.0.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-mockito2</artifactId>
            <version>2.0.2</version>
            <scope>test</scope>
        </dependency>
```

sample:

```
@RunWith(PowerMockRunner.class)
@PowerMockIgnore({ "javax.management.*","jdk.internal.reflect.*" })
@PrepareForTest({ TradeDateUtils.class })
@SuppressStaticInitializationFor("com.ubssdic.ufos.framework.utils.TradeDateUtils") // 
public class TestOne {


    @Test
    public void test11() throws Throwable {
        PowerMockito.mockStatic(TradeDateUtils.class);
        PowerMockito.when(TradeDateUtils.queryDayTradeOffset(anyString(), anyInt())).thenReturn("2021-12-01");
        Assert.assertEquals("2021-12-01", TradeDateUtils.queryDayTradeOffset("",1));
    }
}
```

Java17

java.lang.NoSuchMethodError: 'org.mockito.invocation.Invocation org.mockito.invocation.InvocationFactory.createInvocation(java.lang.Object, org.mockito.mock.MockCreationSettings, java.lang.reflect.Method, java.util.concurrent.Callable, java.lang.Object[])'

	at org.powermock.api.mockito.invocation.InvocationFactory.createInvocation(InvocationFactory.java:41)
	at org.powermock.api.mockito.invocation.MockHandlerAdaptor.createInvocation(MockHandlerAdaptor.java:81)
	at org.powermock.api.mockito.invocation.MockHandlerAdaptor.performIntercept(MockHandlerAdaptor.java:61)
	at org.powermock.api.mockito.invocation.MockitoMethodInvocationControl.invoke(MockitoMethodInvocationControl.java:93)
	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:186)
	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:168)
	at org.powermock.core.MockGateway.methodCall(MockGateway.java:145)
	at com.weiye.util.TradeDateUtils.queryDayTradeOffset(TradeDateUtils.java)

**Comment by liweiye-2021** [comment]
![image](https://user-images.githubusercontent.com/17706417/153987478-c01f2118-8f06-4424-b25f-b1d3356f0340.png)

![image](https://user-images.githubusercontent.com/17706417/153998177-81c684bd-d8aa-4803-bfc5-d7224059ddda.png)

the method is deprecated in version 3.XX，is removed in version 4.0

**Comment by nmorkar** [comment]
having same issue, any workaround to fix it?

**Comment by nmorkar** [comment]
Seems fix in this PR - https://github.com/powermock/powermock/pull/1113/files
When this PR is expected to merge and release?

**Comment by class101** [comment]
2-3 more years probably ...

**Comment by yassir78** [comment]
Hello , did you find the solution for the error or not ?

**Comment by liweiye-2021** [comment]
No，as [nmorkar](https://github.com/nmorkar)  say，no one  release this PR - https://github.com/powermock/powermock/pull/1113/files

**Comment by yassir78** [comment]
The only solution is to migrate and use mockito inline

**Comment by liweiye-2021** [comment]
Thanks，I will try do it
