### ISSUE TITLE
Reason: javassist.bytecode.InterfaceMethodrefInfo cannot be cast to javassist.bytecode.MethodrefInfo, default interface issue

### ISSUE THREAD

**Issue by xenoterracide** [powermock/powermock#729]
What do you see instead?

```
java.lang.IllegalStateException: Failed to transform class with name com.myapp.OrganizationService. Reason: javassist.bytecode.InterfaceMethodrefInfo cannot be cast to javassist.bytecode.MethodrefInfo

	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:284)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:192)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:77)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:439)
	at sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:420)
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at org.junit.internal.MethodSorter.getDeclaredMethods(MethodSorter.java:52)
	at org.junit.internal.runners.TestClass.getAnnotatedMethods(TestClass.java:45)
	at org.junit.internal.runners.MethodValidator.validateTestMethods(MethodValidator.java:71)
	at org.junit.internal.runners.MethodValidator.validateStaticMethods(MethodValidator.java:44)
	at org.junit.internal.runners.MethodValidator.validateMethodsForDefaultRunner(MethodValidator.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.validate(PowerMockJUnit44RunnerDelegateImpl.java:108)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.<init>(PowerMockJUnit44RunnerDelegateImpl.java:70)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl.<init>(PowerMockJUnit47RunnerDelegateImpl.java:42)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit49RunnerDelegateImpl.<init>(PowerMockJUnit49RunnerDelegateImpl.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:172)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:48)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:111)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:71)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:96)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
Caused by: java.lang.ClassCastException: javassist.bytecode.InterfaceMethodrefInfo cannot be cast to javassist.bytecode.MethodrefInfo
	at javassist.bytecode.ConstPool.getMethodrefType(ConstPool.java:452)
	at javassist.bytecode.stackmap.Tracer.doInvokeMethod(Tracer.java:800)
	at javassist.bytecode.stackmap.Tracer.doOpcode148_201(Tracer.java:597)
	at javassist.bytecode.stackmap.Tracer.doOpcode(Tracer.java:81)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:187)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:164)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:108)
	at javassist.bytecode.MethodInfo.rebuildStackMap(MethodInfo.java:423)
	at javassist.bytecode.MethodInfo.rebuildStackMapIf6(MethodInfo.java:405)
	at javassist.CtBehavior.insertBefore(CtBehavior.java:768)
	at javassist.CtBehavior.insertBefore(CtBehavior.java:734)
	at org.powermock.core.transformers.impl.AbstractMainMockTransformer.modifyMethod(AbstractMainMockTransformer.java:222)
	at org.powermock.core.transformers.impl.AbstractMainMockTransformer.modifyMethod(AbstractMainMockTransformer.java:191)
	at org.powermock.core.transformers.impl.AbstractMainMockTransformer.allowMockingOfStaticAndFinalAndNativeMethods(AbstractMainMockTransformer.java:121)
	at org.powermock.core.transformers.impl.ClassMockTransformer.transformMockClass(ClassMockTransformer.java:56)
	at org.powermock.core.transformers.impl.AbstractMainMockTransformer.transform(AbstractMainMockTransformer.java:62)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:265)
	... 53 more
```

This seems to have been caused by this change in our interface

```
-	public boolean isUnderUserLimit( Long id )
Add a comment to this line
+	public boolean isUnderUserLimit( final Identifiable id )
 	{
-		return organizationDao.isUnderUserLimit( id );
+		return organizationDao.isUnderUserLimit( Identifiable.requireId( id ) );
 	}
```

```
@FunctionalInterface
public interface Identifiable extends Persistable<Long> // Persistable is a Spring Data interface
{

	@Override
	Long getId();

	/**
	 *
	 * @param identifiable identifiable must be not null but the id can be null
	 * @return
	 */
	default boolean sameIdentityAs( final Identifiable identifiable ) {
		return Objects.equals( this.getId(), Objects.requireNonNull( identifiable ).getId() );
	}

	@Override
	@Transient
	default boolean isNew() {
		return getId() == null;
	}

	static List<Long> ids( final Collection<? extends Identifiable> identifiables ) {
		return identifiables.stream()
			.map( Identifiable::getId )
			.filter( Objects::nonNull )
			.distinct()
			.collect( Collectors.toList() );
	}

	static long requireId( final Identifiable identifiable ) {
		if ( identifiable == null || identifiable.getId() == null ) {
			throw new IllegalArgumentException( "must provide an id" );
		}
		return identifiable.getId();
	}
}
```

Here's a dep tree which I think contains all of the relevant uptream dep classes.

```
FO] --- maven-dependency-plugin:2.10:tree (default-cli) @ dex ---
[WARNING] The artifact org.hibernate:hibernate-search:jar:5.5.2.Final has been relocated to org.hibernate:hibernate-search-orm:jar:5.5.2.Final
[WARNING] The artifact org.hibernate:hibernate-search-infinispan:jar:5.5.2.Final has been relocated to org.infinispan:infinispan-directory-provider:jar:8.1.0.Final
[INFO] +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] +- javax.servlet:servlet-api:jar:2.5:provided
[INFO] +- org.bouncycastle:bcprov-jdk16:jar:1.46:compile
[INFO] +- taglibs:standard:jar:1.1.2:compile
[INFO] +- org.javassist:javassist:jar:3.18.1-GA:compile
[INFO] +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.21:compile
[INFO] +- log4j:log4j:jar:1.2.17:compile
[INFO] +- hibernate:hibernate-tools:jar:3.2.3.GA:compile
[INFO] |  +- org.beanshell:bsh:jar:2.0b4:compile
[INFO] |  \- freemarker:freemarker:jar:2.3.8:compile
[INFO] +- org.hibernate:hibernate-entitymanager:jar:5.0.6.Final:compile
[INFO] |  +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO] |  +- dom4j:dom4j:jar:1.6.1:compile
[INFO] |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.0.1.Final:compile
[INFO] |  \- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final:compile
[INFO] +- org.hibernate:hibernate-core:jar:5.0.6.Final:compile
[INFO] |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  \- org.jboss:jandex:jar:2.0.0.Final:compile
[INFO] +- org.hibernate:hibernate-infinispan:jar:5.0.6.Final:compile
[INFO] +- org.hibernate:hibernate-search-orm:jar:5.5.2.Final:compile
[INFO] |  \- org.hibernate:hibernate-search-engine:jar:5.5.2.Final:compile
[INFO] |     +- org.apache.lucene:lucene-core:jar:5.3.1:compile
[INFO] |     +- org.apache.lucene:lucene-backward-codecs:jar:5.3.1:compile
[INFO] |     +- org.apache.lucene:lucene-misc:jar:5.3.1:compile
[INFO] |     +- org.apache.lucene:lucene-analyzers-common:jar:5.3.1:compile
[INFO] |     \- org.apache.lucene:lucene-facet:jar:5.3.1:compile
[INFO] |        \- org.apache.lucene:lucene-queries:jar:5.3.1:compile
[INFO] +- org.hibernate:hibernate-search-serialization-avro:jar:5.5.2.Final:compile
[INFO] |  \- org.apache.avro:avro:jar:1.7.7:compile
[INFO] |     +- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] |     +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[INFO] |     +- com.thoughtworks.paranamer:paranamer:jar:2.3:compile
[INFO] |     \- org.apache.commons:commons-compress:jar:1.4.1:compile
[INFO] +- org.hibernate:hibernate-search-backend-jgroups:jar:5.5.2.Final:compile
[INFO] +- org.infinispan:infinispan-directory-provider:jar:8.1.0.Final:compile
[INFO] |  +- org.infinispan:infinispan-lucene-directory:jar:8.1.0.Final:compile
[INFO] |  +- org.hibernate:hibernate-search-engine:jar:tests:5.5.1.Final:compile
[INFO] |  \- org.infinispan:infinispan-core:jar:8.1.0.Final:compile
[INFO] |     +- org.infinispan:infinispan-commons:jar:8.1.0.Final:compile
[INFO] |     +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.1_spec:jar:1.0.1.Final:compile
[INFO] |     \- org.jboss.marshalling:jboss-marshalling-osgi:jar:1.4.10.Final:compile
[INFO] +- org.hibernate:hibernate-validator:jar:5.2.4.Final:compile
[INFO] +- org.springframework:spring-test:jar:4.2.8.RELEASE:test
[INFO] |  \- org.springframework:spring-core:jar:4.2.8.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-test:jar:4.0.4.RELEASE:test
[INFO] |  +- org.springframework.security:spring-security-core:jar:4.0.4.RELEASE:test
[INFO] |  |  +- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:4.2.8.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:4.2.8.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:4.2.8.RELEASE:compile
[INFO] |  \- org.springframework.security:spring-security-web:jar:4.0.4.RELEASE:test
[INFO] |     \- org.springframework:spring-web:jar:4.2.8.RELEASE:test
[INFO] +- org.springframework.batch:spring-batch-test:jar:3.0.7.RELEASE:test
[INFO] |  +- org.springframework.batch:spring-batch-core:jar:3.0.7.RELEASE:test
[INFO] |  |  +- com.ibm.jbatch:com.ibm.jbatch-tck-spi:jar:1.0:test
[INFO] |  |  |  \- javax.batch:javax.batch-api:jar:1.0.1:test
[INFO] |  |  +- org.codehaus.jettison:jettison:jar:1.2:test
[INFO] |  |  +- org.springframework.batch:spring-batch-infrastructure:jar:3.0.7.RELEASE:test
[INFO] |  |  |  \- org.springframework.retry:spring-retry:jar:1.1.3.RELEASE:test
[INFO] |  |  \- org.springframework:spring-tx:jar:4.2.8.RELEASE:test
[INFO] |  \- org.springframework:spring-jdbc:jar:4.2.8.RELEASE:test
[INFO] +- com.jayway.jsonpath:json-path:jar:2.2.0:test
[INFO] |  \- net.minidev:json-smart:jar:2.2.1:test
[INFO] |     \- net.minidev:accessors-smart:jar:1.1:test
[INFO] +- org.apache.xmlbeans:xmlbeans:jar:2.6.0:compile
[INFO] +- org.codehaus.castor:castor-xml:jar:1.3.3:compile
[INFO] |  +- org.codehaus.castor:castor-core:jar:1.3.3:compile
[INFO] |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  +- stax:stax:jar:1.2.0:compile
[INFO] |  |  \- stax:stax-api:jar:1.0.1:compile
[INFO] |  +- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] |  \- org.springframework:spring-context:jar:4.2.8.RELEASE:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] +- org.hamcrest:hamcrest-integration:jar:1.3:test
[INFO] +- org.jgroups:jgroups:jar:3.6.2.Final:compile
[INFO] +- org.slf4j:jcl-over-slf4j:jar:1.7.21:runtime
[INFO] +- commons-io:commons-io:jar:2.4:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.3.2:compile
[INFO] +- net.sf.opencsv:opencsv:jar:2.0:compile
[INFO] +- org.aspectj:aspectjweaver:jar:1.8.9:compile
[INFO] +- com.thoughtworks.xstream:xstream:jar:1.4.9:compile
[INFO] |  +- xmlpull:xmlpull:jar:1.1.3.1:compile
[INFO] |  \- xpp3:xpp3_min:jar:1.1.4c:compile
[INFO] +- org.jasypt:jasypt:jar:1.9.0:compile
[INFO] +- org.jasypt:jasypt-hibernate4:jar:1.9.0:compile
[INFO] +- org.jasypt:jasypt-spring31:jar:1.9.0:compile
[INFO] +- org.jasypt:jasypt-springsecurity3:jar:1.9.0:compile
[INFO] +- org.apache.httpcomponents:httpasyncclient:jar:4.1.2:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.5:compile
[INFO] |  +- org.apache.httpcomponents:httpcore-nio:jar:4.4.5:compile
[INFO] |  \- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] +- com.lowagie:itext:jar:2.1.7:compile
[INFO] |  +- bouncycastle:bcmail-jdk14:jar:138:compile
[INFO] |  +- bouncycastle:bcprov-jdk14:jar:138:compile
[INFO] |  \- org.bouncycastle:bctsp-jdk14:jar:1.38:compile
[INFO] |     \- org.bouncycastle:bcprov-jdk14:jar:1.38:compile
[INFO] +- org.apache.pdfbox:pdfbox:jar:1.8.12:compile
[INFO] |  +- org.apache.pdfbox:fontbox:jar:1.8.12:compile
[INFO] |  +- org.apache.pdfbox:jempbox:jar:1.8.12:compile
[INFO] |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] +- jaxen:jaxen:jar:1.1.1:compile
[INFO] |  +- jdom:jdom:jar:1.0:compile
[INFO] |  \- xom:xom:jar:1.2.5:compile
[INFO] |     \- xalan:xalan:jar:2.7.0:compile
[INFO] +- xml-apis:xml-apis:jar:1.3.03:compile
[INFO] +- javax.mail:mail:jar:1.4.2:compile
[INFO] |  \- javax.activation:activation:jar:1.1.1:compile
[INFO] +- javax.servlet.jsp.jstl:javax.servlet.jsp.jstl-api:jar:1.2.1:compile
[INFO] +- javax.annotation:jsr250-api:jar:1.0:compile
[INFO] +- org.apache.poi:poi:jar:3.11:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] +- org.apache.poi:poi-ooxml:jar:3.11:compile
[INFO] |  \- org.apache.poi:poi-ooxml-schemas:jar:3.11:compile
[INFO] +- org.easymock:easymock:jar:3.0:test
[INFO] |  \- cglib:cglib-nodep:jar:2.2:test
[INFO] +- org.easymock:easymockclassextension:jar:2.4:test
[INFO] +- org.powermock:powermock-api-easymock:jar:1.6.6:test
[INFO] |  \- org.powermock:powermock-api-support:jar:1.6.6:test
[INFO] |     +- org.powermock:powermock-core:jar:1.6.6:test
[INFO] |     \- org.powermock:powermock-reflect:jar:1.6.6:test
[INFO] |        \- org.objenesis:objenesis:jar:2.1:test
[INFO] +- org.powermock:powermock-module-test-easymock-junit4:jar:1.6.6:test
[INFO] +- org.powermock:powermock-module-junit4:jar:1.6.6:test
[INFO] |  \- org.powermock:powermock-module-junit4-common:jar:1.6.6:test
[INFO] +- com.google.guava:guava:jar:17.0:compile
[INFO] +- com.h2database:h2:jar:1.4.190:test
[INFO] +- com.oracle:ojdbc7:jar:12.1.0.2:runtime
[INFO] +- org.apache.tomcat:tomcat-jasper-el:jar:8.0.37:test
[INFO] |  \- org.apache.tomcat:tomcat-el-api:jar:8.0.37:test
[INFO] +- com.jcraft:jsch:jar:0.1.54:test
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.7:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.6.7:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.7:compile
[INFO] +- com.fasterxml.jackson.module:jackson-module-jsonSchema:jar:2.6.7:compile
[INFO] +- org.ow2.asm:asm:jar:5.0.4:compile
[INFO] +- nl.jqno.equalsverifier:equalsverifier:jar:2.1.7:test
[INFO] \- com.fasterxml:classmate:jar:1.2.0:compile
```

**Comment by thekingnothing** [comment]
It's the issue with Javassist: https://issues.jboss.org/browse/JASSIST-220 and was fixed in version 3.19.0-GA. I see that you are using `org.javassist:javassist:jar:3.18.1-GA:compile`. So, to resolve an issue you just need upgrade Javassist version.

**Comment by xenoterracide** [comment]
but if you look at my dep tree.. `[INFO] +- org.javassist:javassist:jar:3.18.1-GA:compile`

**Comment by thekingnothing** [comment]
@xenoterracide, anyway you need version upper than 3.19. I'd like recommend to upgrade to latest GA version.

**Comment by xenoterracide** [comment]
sorry, I misread my bad. We're using Spring Platform 2.0.8 and will be migrated to Athens  in January, which has 3.20 http://docs.spring.io/platform/docs/Athens-SR1/reference/htmlsingle/, thanks for the help, at least I know it'll work in the future.
