### ISSUE TITLE
unable to test a final class using: testng, mockito, powermock

### ISSUE THREAD

**Issue by jwtodd** [powermock/powermock#746]
i am unable to use powermock to test  final class when using gradle+testng+mockito+powermock.

What steps will reproduce the problem?
* % unzip powermock-final.zip
* % cd powermock-final
* % gradle build

What is the expected output?
* successful test run

What do you see instead?
* "java.lang.IllegalArgumentException: Cannot subclass final class class powermock.MyFinal"

What version of the product are you using?
* 'org.testng:testng:6.9.10'
* 'org.mockito:mockito-core:2.4.0'
* 'org.powermock:powermock-api-mockito2:1.7.0RC2'

On what operating system?
* osx 10.12.13

Please provide any additional information below. 

build.gradle 
```
apply plugin: 'java'
apply plugin: 'maven'


repositories {
  mavenCentral()
}

dependencies {
  testCompile 'org.testng:testng:6.9.10'
  testCompile 'org.mockito:mockito-core:2.4.0'
  testCompile 'org.powermock:powermock-api-mockito2:1.7.0RC2'
}

test {
  useTestNG()

  testLogging {
    exceptionFormat 'full'
  }
}
```

src/main/java/powermock/MyFinal.java
```
package powermock;

final class MyFinal {
}
```
src/test/java/powermock/MyFinalTest.java 
```
package powermock;

import org.powermock.core.classloader.annotations.PrepareForTest;
import org.testng.annotations.Test;
import org.powermock.api.mockito.PowerMockito;

@PrepareForTest(MyFinal.class)
public class MyFinalTest {

  @Test
  public void myFinal() {
    MyFinal myFinal = PowerMockito.mock(MyFinal.class);
  }
}
```

```

Gradle suite > Gradle test > powermock.MyFinalTest.myFinal FAILED
    java.lang.IllegalArgumentException: Cannot subclass final class class powermock.MyFinal
        at org.powermock.api.mockito.repackaged.cglib.proxy.Enhancer.generateClass(Enhancer.java:575)
        at org.powermock.api.mockito.repackaged.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:14)
        at org.powermock.api.mockito.repackaged.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:199)
        at org.powermock.api.mockito.repackaged.cglib.proxy.Enhancer.createHelper(Enhancer.java:547)
        at org.powermock.api.mockito.repackaged.cglib.proxy.Enhancer.createClass(Enhancer.java:487)
        at org.powermock.api.mockito.repackaged.ClassImposterizer.createProxyClass(ClassImposterizer.java:126)
        at org.powermock.api.mockito.repackaged.ClassImposterizer.imposterise(ClassImposterizer.java:68)
        at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMethodInvocationControl(DefaultMockCreator.java:126)
        at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMock(DefaultMockCreator.java:72)
        at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.mock(DefaultMockCreator.java:49)
        at org.powermock.api.mockito.PowerMockito.mock(PowerMockito.java:147)
        at powermock.MyFinalTest.myFinal(MyFinalTest.java:13)
```

[powermock-final.zip](https://github.com/powermock/powermock/files/752828/powermock-final.zip)

**Comment by jwtodd** [comment]
ok this issue looks to be related to testng. swapping in junit4 i was able to get a green test:

* testCompile 'junit:junit:4.12'
* testCompile 'org.mockito:mockito-core:2.4.0'
* testCompile 'org.powermock:powermock-api-mockito2:1.7.0RC2'
* testCompile 'org.powermock:powermock-module-junit4:1.7.0RC2'

**Comment by juherr** [comment]
What could be the issue with TestNG?

**Comment by juherr** [comment]
@jwtodd Did you try to `extends PowerMockTestCase` as recommanded by the documentation? https://github.com/powermock/powermock/wiki/TestNG_usage

**Comment by thekingnothing** [comment]
@jwtodd, 

According to your example  @juherr right. You have to either extends `PowerMockTestCase` or declare 
```
@ObjectFactory
    public IObjectFactory getObjectFactory() {
        return new org.powermock.modules.testng.PowerMockObjectFactory();
    }
```

**Comment by jwtodd** [comment]
ok will look into this.

it would be optimal to use testng.

thx!

**Comment by jwtodd** [comment]
ok extending PowerMockTestCase worked for me ... YES!

but declaring @ObjectFactory failed as follows:

```
java.lang.ExceptionInInitializerError
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
	at org.mockito.internal.configuration.injection.scanner.MockScanner.isMockOrSpy(MockScanner.java:83)
	at org.mockito.internal.configuration.injection.scanner.MockScanner.preparedMock(MockScanner.java:71)
	at org.mockito.internal.configuration.injection.scanner.MockScanner.scan(MockScanner.java:59)
	at org.mockito.internal.configuration.injection.scanner.MockScanner.addPreparedMocks(MockScanner.java:45)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.injectMocks(InjectingAnnotationEngine.java:82)
	at org.powermock.api.mockito.internal.configuration.PowerMockitoInjectingAnnotationEngine.process(PowerMockitoInjectingAnnotationEngine.java:36)
	at org.powermock.api.extension.listener.AnnotationEnabler.injectSpiesAndInjectToSetters(AnnotationEnabler.java:61)
	at org.powermock.api.extension.listener.AnnotationEnabler.beforeTestMethod(AnnotationEnabler.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1846)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:700)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:415)
	at org.powermock.modules.testng.internal.PowerMockTestNGMethodHandler.injectMocksUsingAnnotationEnabler(PowerMockTestNGMethodHandler.java:76)
	at org.powermock.modules.testng.internal.PowerMockTestNGMethodHandler.invoke(PowerMockTestNGMethodHandler.java:48)
	at powermock.MyFinalTest_$$_jvst217_0.myFinal(MyFinalTest_$$_jvst217_0.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@12aba8be
	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:86)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:40)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:18)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:17)
	... 42 more
Caused by: java.lang.ClassCastException: Cannot cast org.powermock.api.mockito.internal.mockmaker.PowerMockMaker to org.mockito.plugins.MockMaker
	at java.lang.Class.cast(Class.java:3369)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:82)
	... 45 more
```
