### ISSUE TITLE
version 1.7.0RC2 IllegalAccessError

### ISSUE THREAD

**Issue by AhmedHORMAL** [powermock/powermock#753]
I use powermockito for mocking private method.

My test class has following annotations : 

`@RunWith( PowerMockRunner.class )
@PrepareForTest( DocumentsService.class )`

My Test method has following code:

	@Test
	public void shouldGenerateOnePDF() throws Exception {

		final ZipToSend zipToSend = buildZipToSend("Content", "00P26000002", MediaType.PDF);
		final DocumentsService spy = PowerMockito.spy(new DocumentsService());

		PowerMockito.doNothing().when(spy, MemberMatcher.method(DocumentsService.class, "generateIndexXMLDocumentFromAgregat", String.class, Agregat.class)).withArguments(Mockito.anyString(), Mockito.any(Agregat.class));

		spy.generateZipFromZipToSend(zipToSend, TEST_DIR_PATH, TEST_DIR_NAME);
		Assert.assertTrue(new File(TEST_DIR_PATH + "/" + TEST_DIR_NAME).exists());

	}`

My test pass with 1.6.6 but not with 1.7.0RC2
Here is the stack trace of the error:

`java.lang.IllegalAccessError: tried to access method org.mockito.internal.stubbing.answers.DoesNothing.<init>()V from class org.powermock.api.mockito.PowerMockito
	at org.powermock.api.mockito.PowerMockito.doNothing(PowerMockito.java:743)
	at fr.myPackage.shouldGenerateOnePDF(DocumentsServiceTest.java:219)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:294)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.assertj.core.api.JUnitSoftAssertions$1.evaluate(JUnitSoftAssertions.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:282)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:202)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:144)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:118)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)`

**Comment by thekingnothing** [comment]
Which version of mockito do you use?

**Comment by AhmedHORMAL** [comment]
I use version 2.7.5 of mockito !

**Comment by thekingnothing** [comment]
Thank you for reporting the issue. I'll look into. @gstamac, maybe you will have a time to check the issue.

**Comment by emmaLP** [comment]
The problem occurs because you cannot directly instantiate DoesNothing class. The constructor is set to private. This would need to change to call the static method to get an instance.

The following method currently looks like this: 
```
public static PowerMockitoStubber doNothing() {
    return POWERMOCKITO_CORE.doAnswer(new DoesNothing());
}
```
but it should be changed to:
```
public static PowerMockitoStubber doNothing() {
    return POWERMOCKITO_CORE.doAnswer(DoesNothing.doesNothing());
}
```

**Comment by thekingnothing** [comment]
@emmaLP, thank you for investigating the issue. 

It will be amazing if you have a time to provide a pull request with changes.

**Comment by emmaLP** [comment]
Pull request: #758

**Comment by thekingnothing** [comment]
@emmaLP, thank you a lot for help! I've merged your pull request.

**Comment by emmaLP** [comment]
Do you have an ETA of when this will be released?

**Comment by thekingnothing** [comment]
I'll release it on Sunday.

Best regrads,
Arthur Zagretdinov



On 2 Mar 2017, at 08:51, emmaLP <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have an ETA of when this will be released?

**Comment by thekingnothing** [comment]
@emmaLP, I've just dropped PowerMock 1.7.0.RC4 release.

**Comment by hazems** [comment]
@thekingnothing You are a life saver.
