### ISSUE TITLE
IllegalAccessError on spy-object in switch(enumValue) block

### ISSUE THREAD

**Issue by sirbralex** [powermock/powermock#768]
There is IllegalAccessError while calling method with switch(enumValue) block on spy-object.
But if we replace switch block with if clause, it'll work.

```java 
import android.test.suitebuilder.annotation.SmallTest;

import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PowerMockIgnore;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.rule.PowerMockRule;
import org.robolectric.RobolectricTestRunner;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

@RunWith(RobolectricTestRunner.class)
@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*", "*.*"})
@PrepareForTest(ShiftManager.class)
@SmallTest
public class ShiftManagerTest {

    @Rule
    public PowerMockRule rule = new PowerMockRule();

    enum AnyEnum {
        VAL_1,
        VAL_2;
    }

    static class AnyClass {
        public AnyEnum getValue() {
            return AnyEnum.VAL_1;
        }
    }

    static class TestSwitch {

        private AnyClass getAnyClass() {
            return null;
        }

        public void funcWithSwitch() {
            AnyClass val = getAnyClass();
            switch (val.getValue()) {

            }
        }
    }

    @Test
    public void testSwitch() throws Exception {

        AnyClass val = mock(AnyClass.class);
        when(val.getValue()).thenReturn(AnyEnum.VAL_2);


        TestSwitch spy = PowerMockito.spy(new TestSwitch());
        PowerMockito.doReturn(val).when(spy, "getAnyClass");
        spy.funcWithSwitch();
    }
}
```
Stacktrace:
```
java.lang.IllegalAccessError: tried to access class com.example.ShiftManagerTest$1 from class com.example.ShiftManagerTest$TestSwitch

	at com.example.ShiftManagerTest$TestSwitch.funcWithSwitch(ShiftManagerTest.java:63)
	at com.example.ShiftManagerTest.testSwitch(ShiftManagerTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1819)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:801)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:666)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.classloading.AbstractClassloaderExecutor.getResult(AbstractClassloaderExecutor.java:69)
	at org.powermock.classloading.AbstractClassloaderExecutor.executeWithClassLoader(AbstractClassloaderExecutor.java:59)
	at org.powermock.classloading.SingleClassloaderExecutor.execute(SingleClassloaderExecutor.java:67)
	at org.powermock.classloading.AbstractClassloaderExecutor.execute(AbstractClassloaderExecutor.java:43)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:75)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by thekingnothing** [comment]
PowerMock uses custom class loader to be able to modified class when it is required.  PowerMockRule with xstream reloads all objects with PowerMock Cla`sLoader by serialising to XML deserialising. So then you run test with this rule classes are loaded twice usually. But not for enums. 

When class should not be instrumented (class is not mentioned in `@PrepareForTest`) it is deferred and loaded by another class loader. But if a class loaded by another class loader it cannot get access to package private fields or classes.  As result: `java.lang.IllegalAccessError: tried to access class` 

You may fixed it by making enum public or force PowerMock to load enum and class with one class loader by adding enum to `@PrepareForTest`.
