### ISSUE TITLE
java.lang.IllegalStateException: Failed to transform class with name com.epiqsystems.jdx.protocols.ftpserver.ServerSession. Reason: javassist.bytecode.StringInfo cannot be cast to javassist.bytecode.ClassInfo

### ISSUE THREAD

**Issue by wodencafe** [powermock/powermock#778]
Hi all,

we are using the latest powermock, with the following 4 modules:

**org.powermock.powermock-api-easymock (1.7.0RC4)
org.powermock.powermock-module-junit4 (1.7.0RC4)
org.powermock.powermock-classloading-xstream (1.7.0RC4)
org.easymock.easymock (3.4)**

We receive the following error when running our Unit Tests:

```
java.lang.IllegalStateException: Failed to transform class with name com.epiqsystems.jdx.protocols.ftpserver.ServerSession. Reason: javassist.bytecode.StringInfo cannot be cast to javassist.bytecode.ClassInfo
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:284)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:192)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:77)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:439)
	at sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:420)
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at org.junit.internal.MethodSorter.getDeclaredMethods(MethodSorter.java:52)
	at org.junit.internal.runners.TestClass.getAnnotatedMethods(TestClass.java:45)
	at org.junit.internal.runners.MethodValidator.validateTestMethods(MethodValidator.java:71)
	at org.junit.internal.runners.MethodValidator.validateStaticMethods(MethodValidator.java:44)
	at org.junit.internal.runners.MethodValidator.validateMethodsForDefaultRunner(MethodValidator.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.validate(PowerMockJUnit44RunnerDelegateImpl.java:108)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.<init>(PowerMockJUnit44RunnerDelegateImpl.java:70)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl.<init>(PowerMockJUnit47RunnerDelegateImpl.java:42)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit49RunnerDelegateImpl.<init>(PowerMockJUnit49RunnerDelegateImpl.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:172)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:48)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:108)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:71)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassCastException: javassist.bytecode.StringInfo cannot be cast to javassist.bytecode.ClassInfo
	at javassist.bytecode.ConstPool.getClassInfo(ConstPool.java:245)
	at javassist.bytecode.stackmap.Tracer.doOpcode148_201(Tracer.java:605)
	at javassist.bytecode.stackmap.Tracer.doOpcode(Tracer.java:81)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:187)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:164)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:108)
	at javassist.bytecode.MethodInfo.rebuildStackMap(MethodInfo.java:456)
	at javassist.bytecode.MethodInfo.rebuildStackMapIf6(MethodInfo.java:438)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:113)
	at javassist.CtClassType.instrument(CtClassType.java:1465)
	at org.powermock.core.transformers.impl.ClassMockTransformer.transformMockClass(ClassMockTransformer.java:65)
	at org.powermock.core.transformers.impl.AbstractMainMockTransformer.transform(AbstractMainMockTransformer.java:62)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:265)
	... 56 more

```

This looks like it might be a Powermock or Javassist bug, so I wanted to run it by you guys and see what you think about the stack trace.

Do you think this is a Powermock / Javassist problem?

Thank you for the assistance.

**Comment by wodencafe** [comment]
UPDATE: This happens as a result of one particular method in a class.

If I comment out the contents of this method, it doesn't happen.

If I leave the contents of this method intact, I get the above Exception.

**Comment by thekingnothing** [comment]
It could be an issue of both: PowerMock and Javassist  

PowerMock replaces all call to constructor, by calling `MockGateway` to check if constructor call should be mocked or not. So, it changes [`constant_pool`](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.4)

Javassist accounts for re-calculating constant pool after modifying. Javasist also compiles code to byte code and validate code. Javassist fails during processing a constructor call to a class. It tries to get information about class, but I don't know why, in constant pool at the position of class store string information. 

It could an issue with recalculating constant pool or incorrect editing constructor call by PowerMock (for example call of constructor of the String). Without code which reproduce the issue with isolation it's hard to say where issue should be fixed.

**Comment by wodencafe** [comment]
Hi @thekingnothing, thanks for the info :)

I'll try to replicate this in a test project on Monday, and if I am successful, I will post it here.

I was able to work around this by giving the huge method some much-needed refactoring.

Woden Cafe

**Comment by thekingnothing** [comment]
@wodencafe, if you was able to reproduce an issue, please, create an issue with example.
