### ISSUE TITLE
IllegalStateException: Failed to transform class with name backend.model.posting.PostingTest. Reason: before ()V in backend.model.posting.PostingTest: inconsistent stack height -1

### ISSUE THREAD

**Issue by florianschmidt1994** [powermock/powermock#779]
Hey Guys, 
I see an IllegalStateException when running one particular test.

**What steps will reproduce the problem?**
The following code fails each time it is run

_Testcase:_
```kotlin
package backend.model.posting

import backend.controller.exceptions.ConflictException
import backend.model.location.Location
import backend.model.user.UserAccount
import org.junit.Before
import org.junit.Ignore
import org.junit.Test
import org.junit.runner.RunWith
import org.powermock.api.mockito.PowerMockito
import org.powermock.api.mockito.PowerMockito.mock
import org.powermock.core.classloader.annotations.PrepareForTest
import org.powermock.modules.junit4.PowerMockRunner
import java.time.LocalDateTime
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith

@RunWith(PowerMockRunner::class)
@PrepareForTest(Location::class, UserAccount::class)
class PostingTest {

    private lateinit var now: LocalDateTime
    private lateinit var later: LocalDateTime
    private lateinit var someLocation: Location
    private lateinit var creator: UserAccount
    private lateinit var posting: Posting


    @Before
    fun before() {
        now = LocalDateTime.now()
        later = now.plusMinutes(10)
        someLocation = mock(Location::class.java)
        creator = mock(UserAccount::class.java)
        posting = Posting("Lalala", LocalDateTime.MAX, someLocation, creator, mutableListOf())
    }

    @Test
    fun like() {
        posting.like(later, creator)
        assertEquals(posting.likes.count(), 1)
    }

    @Test
    fun multipleLikes() {

        val other = mock(UserAccount::class.java)

        PowerMockito.`when`(creator.id).thenReturn(1)
        PowerMockito.`when`(other.id).thenReturn(2)

        posting.like(later, creator)
        posting.like(later, other)

        assertEquals(posting.likes.count(), 2)
    }

    fun cantLikeTwice() {

        PowerMockito.`when`(creator.id).thenReturn(1)

        posting.like(later, creator)

        assertFailsWith<ConflictException> {
            posting.like(later, creator)
        }
    }

    @Test
    fun unlike() {
        posting.like(later, creator)
        posting.unlike(creator)
    }

    @Test
    fun cantUnlikeNotLiked() {
        assertFailsWith<ConflictException> {
            posting.unlike(creator)
        }
    }

    @Test
    @Ignore("Posting::hasLikesBy needs to be refactored first")
    fun hasLikesBy() {

    }

}
```

_Class under Test_:
```kt
package backend.model.posting

import backend.controller.exceptions.BadRequestException
import backend.controller.exceptions.ConflictException
import backend.controller.exceptions.NotFoundException
import backend.model.BasicEntity
import backend.model.challenges.Challenge
import backend.model.location.Location
import backend.model.media.Media
import backend.model.user.UserAccount
import java.time.LocalDateTime
import java.util.*
import java.util.regex.Matcher
import java.util.regex.Pattern
import javax.persistence.*
import javax.persistence.CascadeType.PERSIST

@Entity
class Posting : BasicEntity {

    private constructor() : super()

    @Column(columnDefinition = "TEXT")
    var text: String? = null

    @ElementCollection
    var hashtags: List<Hashtag> = ArrayList()

    lateinit var date: LocalDateTime

    @OneToOne(cascade = arrayOf(PERSIST))
    var location: Location? = null

    @OneToOne(cascade = arrayOf(PERSIST))
    var challenge: Challenge? = null

    @ManyToOne
    var user: UserAccount? = null

    @OneToMany(cascade = arrayOf(CascadeType.ALL))
    var media: MutableList<Media> = arrayListOf()

    @OneToMany(cascade = arrayOf(CascadeType.ALL), orphanRemoval = true)
    var comments: MutableList<Comment> = arrayListOf()

    @OneToMany(cascade = arrayOf(CascadeType.ALL), orphanRemoval = true)
    @JoinTable(
            joinColumns = arrayOf(JoinColumn(name = "posting_id", referencedColumnName = "id")),
            inverseJoinColumns = arrayOf(JoinColumn(name = "like_id", referencedColumnName = "id"))
    )
    var likes: MutableSet<Like> = hashSetOf()

    @Transient
    var hasLiked = false

    constructor(text: String?, date: LocalDateTime, location: Location?, user: UserAccount, media: MutableList<Media>) : this() {
        this.text = text
        this.date = date
        this.location = location
        this.user = user
        this.media = media
        if (text != null) this.hashtags = extractHashtags(text)
    }

    private fun extractHashtags(text: String): List<Hashtag> {
        val pattern: Pattern = Pattern.compile("#([^\\s]*)")
        val matcher: Matcher = pattern.matcher(text)

        val hashtags = ArrayList<Hashtag>()

        while (matcher.find()) {
            val hashtag = matcher.group(1)
            hashtags.add(Hashtag(hashtag))
        }

        return hashtags
    }

    fun like(createdAt: LocalDateTime, user: UserAccount): Like {
        val like = Like(createdAt, user)

        if (this.isLikedBy(user)) {
            throw ConflictException("User ${user.id} has already liked this posting!")
        } else {
            this.likes.add(like)
        }

        return like
    }

    fun unlike(user: UserAccount) {
        if (this.isLikedBy(user)) {
            val like = findLikeByUser(user)
            this.likes.remove(like)
        } else {
            throw ConflictException("Can't unlike because user ${user.id} has not liked posting ${this.id}")
        }
    }

    private fun findLikeByUser(user: UserAccount): Like? {
        return this.likes
                .filter { it.user?.id == user.id } // TODO: use equals here somehow?
                .firstOrNull()
    }

    private fun isLikedBy(user: UserAccount): Boolean {
        return findLikeByUser(user) != null
    }


    @PreRemove
    fun preRemove() {
        this.likes.clear()
        this.comments.clear()
        this.media.clear()
        this.challenge = null
        this.user = null
    }

    // TODO: Refactor this!
    fun hasLikesBy(userId: Long?): Posting {
        if (userId != null) {
            this.hasLiked = this.likes.any { it.user?.id == userId }
        }
        return this
    }

    private fun findCommentById(commentId: Long): Comment? {
        return this.comments.filter { it.id == commentId }.firstOrNull()
    }

    fun removeComment(commentId: Long) {

        this.findCommentById(commentId)?.let {
            this.comments.remove(it)
            return
        }

        throw NotFoundException("Comment with id $commentId not found at posting $id")
    }

    fun addComment(from: UserAccount, at: LocalDateTime, withText: String): Comment {

        if (withText.trim().isEmpty()) {
            throw BadRequestException("Empty comments are not allowed")
        }

        val comment = Comment(withText, at, from)
        this.comments.add(comment)
        return comment
    }
}
```
**What is the expected output?**
All tests run without exceptions

**What  I see instead**
Stacktrace:
```
java.lang.IllegalStateException: Failed to transform class with name backend.model.posting.PostingTest. Reason: before ()V in backend.model.posting.PostingTest: inconsistent stack height -1

	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:283)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:192)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:71)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:161)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:48)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:113)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:71)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: javassist.CannotCompileException: before ()V in backend.model.posting.PostingTest: inconsistent stack height -1
	at javassist.expr.ExprEditor.doit(ExprEditor.java:117)
	at javassist.CtClassType.instrument(CtClassType.java:1465)
	at org.powermock.core.transformers.impl.ClassMockTransformer.transformMockClass(ClassMockTransformer.java:65)
	at org.powermock.core.transformers.impl.AbstractMainMockTransformer.transform(AbstractMainMockTransformer.java:247)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:264)
	... 25 more
Caused by: javassist.bytecode.BadBytecode: before ()V in backend.model.posting.PostingTest: inconsistent stack height -1
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:111)
	at javassist.bytecode.MethodInfo.rebuildStackMap(MethodInfo.java:456)
	at javassist.bytecode.MethodInfo.rebuildStackMapIf6(MethodInfo.java:438)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:113)
	... 29 more
Caused by: javassist.bytecode.BadBytecode: inconsistent stack height -1
	at javassist.bytecode.stackmap.Tracer.doOpcode(Tracer.java:84)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:187)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:164)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:108)
	... 32 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at javassist.bytecode.stackmap.Tracer.doASTORE(Tracer.java:425)
	at javassist.bytecode.stackmap.Tracer.doOpcode54_95(Tracer.java:342)
	at javassist.bytecode.stackmap.Tracer.doOpcode(Tracer.java:76)
	... 57 more

```

**What version of the product are you using?**
1.6.5'

**On what operating system?**
MacOS Sierra (10.12.3)

**Please provide any additional information below.** 
We are using PowerMock with Kotlin in a Spring Boot Project. This is a unit test without any spring context running. 

We additionally use the kotlin-spring plugin which makes kotlin classes open at compile time (https://kotlinlang.org/docs/reference/compiler-plugins.html)

The error seems to be triggered by the line `posting = Posting("Lalala", LocalDateTime.MAX, someLocation, creator, mutableListOf())` in the `before` function. Without this line, the error does not occur but my tests fail as expected instead (because posting is not initialised)

**Comment by thekingnothing** [comment]
I'm not familiar with Kotlin, but as I understand, this code is calling a constructor of `Posting`  
`posting = Posting("Lalala", LocalDateTime.MAX, someLocation, creator, mutableListOf())`

PowerMock modifies this constructor call to calling `MockGateway` to check if call is mocked or not. 

It could an issue with how PowerMock edits call or issue with Javassist and Kotlin. 

As workaround I may suggest to extract this code to helper class and call static method of helper class to get instance of  `Postingz

**Comment by florianschmidt1994** [comment]
Thanks for the tip, the following did work:

``` 
class PostingTest {
    
    ...

    @Before
    fun before() {
        now = LocalDateTime.now()
        later = now.plusMinutes(10)
        someLocation = mock(Location::class.java)
        creator = mock(UserAccount::class.java)
        posting = getPostingInstance("Lalala", LocalDateTime.MAX, someLocation, creator, mutableListOf())
    }

    ...

    // Equivalent to Java static methods   
    companion object {
            fun getPostingInstance(description: String,
                                   localDateTime: LocalDateTime,
                                   location: Location,
                                   creator: UserAccount,
                                   media: MutableList<Media>): Posting {
                return Posting(description, localDateTime, location, creator, media)
            }
        }

    ...

}
```

This issue happened only after upgrading from Kotlin 1.0.2 to 1.1.1, the same code did work flawlessly with Kotlin 1.0.2

**Comment by max-kammerer** [comment]
Minimal sample to reproduce problem:
```
package bug

import org.junit.Test
import org.junit.runner.RunWith
import org.powermock.modules.junit4.PowerMockRunner

@RunWith(value = PowerMockRunner::class)
class A {
    @Test
    fun test1() {
        Foo(
                try {"1" } catch (e: Exception) {"2"}
        )

    }
}
class Foo(prop: Any)
```

'test1' method bytecode :
```   // access flags 0x11
  public final test1()V
  @Lorg/junit/Test;()
    TRYCATCHBLOCK L0 L1 L2 java/lang/Exception
   L3
    LINENUMBER 11 L3
    NEW bug/Foo  //instance creation
    DUP
   L4
    LINENUMBER 12 L4
   L5
    ASTORE 4 //stack spilling before try/catch
    ASTORE 3
   L0
    NOP
    ALOAD 3 //stack restore
    ALOAD 4
    LDC "1"
   L6
    ASTORE 1
   L1
    GOTO L7
   L2
    ASTORE 2
    ALOAD 3 //stack restore
    ALOAD 4
   L8
    LDC "2"
   L9
    ASTORE 1
   L7
    ALOAD 1
   L10
    LINENUMBER 11 L10
    INVOKESPECIAL bug/Foo.<init> (Ljava/lang/Object;)V //constuctor call
    POP
   L11
    LINENUMBER 15 L11
    RETURN
   L12
    LOCALVARIABLE e Ljava/lang/Exception; L8 L7 2
    LOCALVARIABLE this Lbug/A; L3 L12 0
    MAXSTACK = 3
    MAXLOCALS = 5
```

**Comment by jckoenen** [comment]
Hey guys, 
I stumbled across another source of this IllegalArgumentException. If this is not the right place to post it, I'm sorry 😅 

A java data class with a map parameter:
```
public class DataObject {
    private final Map<String, String> aMap;
    private final String aString;


    public DataObject(final Map<String, String> inAMap, final String inAString) {
        aMap = inAMap;
        aString = inAString;
    }
} 
```

The test written in kotlin:
```import org.junit.Test
import org.junit.runner.RunWith
import org.powermock.modules.junit4.PowerMockRunner

@RunWith(PowerMockRunner::class)
class CrashTest {
    @Test
    fun crashes() {
        //remove next line to make the test work
        val data = DataObject(mapOf(), "bar")
    }

    @Test
    fun works() {
        val data = DataObject(emptyMap(), "bar")
    }
}
```

Kotlin Bytecode:
```// ================com/company/list/data/CrashTest.class =================
// class version 50.0 (50)
// access flags 0x31
public final class com/company/list/data/CrashTest {


  @Lorg/junit/runner/RunWith;(value=org.powermock.modules.junit4.PowerMockRunner.class)

  // access flags 0x11
  public final crashes()V
  @Lorg/junit/Test;()
   L0
    LINENUMBER 12 L0
    NEW com/company/list/data/DataObject
    DUP
    ASTORE 3
    ASTORE 2
   L1
    INVOKESTATIC kotlin/collections/MapsKt.emptyMap ()Ljava/util/Map;
   L2
    ASTORE 4
    ALOAD 2
    ALOAD 3
    ALOAD 4
   L3
    LINENUMBER 12 L3
    LDC "bar"
    INVOKESPECIAL com/company/list/data/DataObject.<init> (Ljava/util/Map;Ljava/lang/String;)V
    ASTORE 1
   L4
    LINENUMBER 13 L4
    RETURN
   L5
    LOCALVARIABLE data Lcom/company/list/data/DataObject; L4 L5 1
    LOCALVARIABLE this Lcom/company/list/data/CrashTest; L0 L5 0
    MAXSTACK = 4
    MAXLOCALS = 5

  // access flags 0x11
  public final works()V
  @Lorg/junit/Test;()
   L0
    LINENUMBER 17 L0
    NEW com/company/list/data/DataObject
    DUP
    INVOKESTATIC kotlin/collections/MapsKt.emptyMap ()Ljava/util/Map;
    LDC "bar"
    INVOKESPECIAL com/company/list/data/DataObject.<init> (Ljava/util/Map;Ljava/lang/String;)V
    ASTORE 1
   L1
    LINENUMBER 18 L1
    RETURN
   L2
    LOCALVARIABLE data Lcom/company/list/data/DataObject; L1 L2 1
    LOCALVARIABLE this Lcom/company/list/data/CrashTest; L0 L2 0
    MAXSTACK = 4
    MAXLOCALS = 2

  // access flags 0x1
  public <init>()V
   L0
    LINENUMBER 8 L0
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
    RETURN
   L1
    LOCALVARIABLE this Lcom/company/list/data/CrashTest; L0 L1 0
    MAXSTACK = 1
    MAXLOCALS = 1

  @Lkotlin/Metadata;(mv={1, 1, 6}, bv={1, 0, 1}, k=1, d1={"\u0000\u0014\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\u0008\u0002\n\u0002\u0010\u0002\n\u0002\u0008\u0002\u0008\u0007\u0018\u00002\u00020\u0001B\u0005\u00a2\u0006\u0002\u0010\u0002J\u0008\u0010\u0003\u001a\u00020\u0004H\u0007J\u0008\u0010\u0005\u001a\u00020\u0004H\u0007\u00a8\u0006\u0006"}, d2={"Lcom/company/list/data/CrashTest;", "", "()V", "crashes", "", "works", "test sources for module list"})
  // compiled from: CrashTest.kt
  // debug info: SMAP
CrashTest.kt
Kotlin
*S Kotlin
*F
+ 1 CrashTest.kt
com/company/list/data/CrashTest
*L
1#1,19:1
*E

}
```
The crash's stacktrace:
```

java.lang.IllegalStateException: Failed to transform class with name com.company.list.data.CrashTest. Reason: crashes ()V in com.company.list.data.CrashTest: inconsistent stack height -1

	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:296)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:204)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:89)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:79)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:161)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:48)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:108)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:71)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:36)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: javassist.CannotCompileException: crashes ()V in com.company.list.data.CrashTest: inconsistent stack height -1
	at javassist.expr.ExprEditor.doit(ExprEditor.java:117)
	at javassist.CtClassType.instrument(CtClassType.java:1465)
	at org.powermock.core.transformers.impl.ClassMockTransformer.transformMockClass(ClassMockTransformer.java:65)
	at org.powermock.core.transformers.impl.AbstractMainMockTransformer.transform(AbstractMainMockTransformer.java:62)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:277)
	... 31 more
Caused by: javassist.bytecode.BadBytecode: crashes ()V in com.company.list.data.CrashTest: inconsistent stack height -1
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:111)
	at javassist.bytecode.MethodInfo.rebuildStackMap(MethodInfo.java:456)
	at javassist.bytecode.MethodInfo.rebuildStackMapIf6(MethodInfo.java:438)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:113)
	... 35 more
Caused by: javassist.bytecode.BadBytecode: inconsistent stack height -1
	at javassist.bytecode.stackmap.Tracer.doOpcode(Tracer.java:84)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:187)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:164)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:108)
	... 38 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at javassist.bytecode.stackmap.Tracer.doASTORE(Tracer.java:425)
	at javassist.bytecode.stackmap.Tracer.doOpcode54_95(Tracer.java:342)
	at javassist.bytecode.stackmap.Tracer.doOpcode(Tracer.java:76)
	... 44 more


Process finished with exit code 255
```

I'm using PowerMock 1.7.0, Kotlin 1.1.3, JUnit 4.12 on MacOs 10.11.6 with java 1.8u92. I hope
you could gain any additional information.

**Comment by rs146** [comment]
I have a similar issue too.

I have a Kotlin class that I am mocking with PowerMockito:
```
class MetadataUtility {
    // set variables etc.

   // this is the function that causes the problem
    fun getMetadataResponse(): MetadataResponse? {
        if (metaDataMap.containsKey(currentPage)) {
            return metaDataMap[currentPage]
        } else {
            return MetadataResponse(mapOf(), mapOf())
        }
    }
}
```

The `MetadataResponse` object is written in Java:

```
public class MetadataResponse {

    private Map<String, String> dfpMetadataList = new HashMap<>();

    private Map<String, String> metadataList = new HashMap<>();

    public  MetadataResponse(Map<String, String> dfpMetadataList, Map<String, String> metadataList) {
        this.dfpMetadataList = dfpMetadataList;
        this.metadataList = metadataList;
    }

    public Map<String, String> getDfpMetadataList() {
        return dfpMetadataList;
    }

    public Map<String, String> getMetadataList() {
        return metadataList;
    }
}
```

And in my test code I am doing the following:

```
@PrepareForTest(MetadataUtility.class)
public class TheTest {
    @Rule
    public PowerMockRule rule = new PowerMockRule();
   
    @Before
    public void setUp() {
       MetadataUtility mockMetadataUtility = PowerMockito.mock(MetadataUtility.class);
    }
}
```

As soon as we attempt to mock the `MetadataUtility` class using PowerMockito, we get the same exception:

`java.lang.IllegalStateException: Reason: getMetadataResponse ()MetadataResponse; in 
 MetadataUtility: inconsistent stack height -1`

**Comment by florianschmidt1994** [comment]
There is a kotlin slack channel where the maintainers (a.k.a jetbrains) seem to be fairly active, maybe we should be crossposting this there?
I am currently not very involved in this problem anymore, maybe someone of you guys might want to try this?

**Comment by thekingn0thing** [comment]
It will be create to collaborate with Kotlin and resolve all issues.

@florianschmidt1994, Do you have a link to a chat? Or even better, maybe you somebody whom you can invite to a thread to discuss the issue?

As I remember, someone contacted me about Kotlin. They wanted to build a Kotlin testing framework upon the Mockito and PowerMock.

I think, from PowerMock side first should be migrating from Javassist to ByteBuddy with ASM to have more complete control over byte-code modification.

Best regrads,
Arthur Zagretdinov

On 25 Jul 2017, at 02:31, Florian Schmidt <notifications@github.com<mailto:notifications@github.com>> wrote:


There is a kotlin slack channel where the maintainers (a.k.a jetbrains) seem to be fairly active, maybe we should be crossposting this there?
I am currently not very involved in this problem anymore, maybe someone of you guys might want to try this?

**Comment by florianschmidt1994** [comment]
You can join the slack on http://slack.kotlinlang.org/, and I also already posted a backlink to this issue in their #general channel. Unfortunately I don't have a specific person in mind to discuss this with

**Comment by andersonvom** [comment]
Not sure if this will help, but here are some more scenarios that succeed/fail:

**Bytecode of Foo.kt**: https://pastebin.com/s4T3qTkF  
**Error log**: https://pastebin.com/fxLZzyg1

**Foo.kt**
```kotlin
package com.example

data class Foo(
        val bar: List<Int>
)
```

**FooTest.kt**
```kotlin
package com.example.usecases

import com.example.Foo
import org.junit.Test
import org.junit.runner.RunWith
import org.powermock.modules.junit4.PowerMockRunner

@RunWith(PowerMockRunner::class)
class FooTest {
    @Test
    fun shouldWork() {
        // This succeeds
        val bar = listOf<Int>()
        Foo(bar)

        // This succeeds
        Foo(emptyList())

        // *** This will fail :( ***
        //Foo(listOf())
    }
}
```

**Comment by francos** [comment]
I am having this same issue, turns out adding a value to the empty list (which I was creating through `mutableListOf()`) made it work as @andersonvom mentioned above. However, `mutableListOf<Foo>()` still failed in my case.

**Comment by andersonvom** [comment]
I recently saw the same error happen again when interacting with `String?.orEmpty()` (e.g. `myObj.name.orEmpty()`). One common pattern I saw is that both `.orEmpty()` and `listOf()` are annotated with `@kotlin.internal.InlineOnly`. Hopefully this helps.

**Comment by erickok** [comment]
I experience(d) the same failure. In my case it was due to the usage of Kotlin's `.apply {}`. Note that this function is also marked `@kotlin.internal.InlineOnly`.

**Comment by AlonsoPaulino** [comment]
Is there any update on this? :( am still facing the same error using Kotlin & Powermockito for unit tests.

**Comment by EbonJaeger** [comment]
I'm experiencing this issue also. Any news or workarounds, by chance?

**Comment by AlonsoPaulino** [comment]
@Gnat008 I don't know if this can be helpful, but at least in my case I fixed the issue by removing all .apply {} calls within any constructor. For example, in this case:
ClassA(parameterA().apply{ // doSomething() } )
I just changed that by:
val a = parameterA().apply {
   // doSomething()
}
ClassA(a)
and then the issue just disappeared.

**Comment by EbonJaeger** [comment]
I'm afraid I don't have any `apply {}` calls. :/

**Comment by max-kammerer** [comment]
Seems workaround with Kotlin compiler option '-Xnormalize-constructor-calls=enable' could be used

**Comment by EbonJaeger** [comment]
@max-kammerer That seems to have worked

**Comment by arronvera** [comment]
Is there any solution to solve this?
added     testImplementation 'org.javassist:javassist:3.19.0-GA', is not working.
When I added specific class in PrepareForTest, it will reproduce this issue.
