### ISSUE TITLE
Android:PowerMock work in “test” folder but not work in “androidTest” folder

### ISSUE THREAD

**Issue by alexei28** [powermock/powermock#780]
I want to test 2 static methods in Android app. So I use PowerMock for this.

I write 2 tests. One unit test and one instrumented unit test.

My android build.gradle:

```

dependencies {

        androidTestCompile "org.mockito:mockito-android:2.7.21"

        androidTestCompile "org.powermock:powermock-api-mockito:1.6.6"

        androidTestCompile 'org.powermock:powermock-module-junit4:1.6.6'

        testCompile 'junit:junit:4.12'

        testCompile 'org.powermock:powermock-api-mockito:1.6.6'

        testCompile 'org.powermock:powermock-module-junit4:1.6.6'

}

```

1. Unit test is in folder: **app/src/test/java/com/mycompany/StringUtilTest.java**

Here code:

```
        @RunWith(PowerMockRunner.class)
        @PrepareForTest(StringUtil.class)
        public class StringUtilTest {
        
            @Test
            public void isCorrectEmailStub() {
                // mock all the static methods in a class called "StringUtil"
                mockStatic(StringUtil.class);
                String INCORRECT_EMAIL_TO_CHECK = "incorrect_email_some.com";                
       when(StringUtil.isCorrectEmail(INCORRECT_EMAIL_TO_CHECK)).thenReturn(true);
                assertThat(StringUtil.isCorrectEmail(INCORRECT_EMAIL_TO_CHECK), is(true));
            }
        }

```

And it work fine. OK.

2. Instrumented unit test is in folder: **app/src/androidTest/java/com/mycompany/StringUtilInstrumentedTest.java**

Here code:

```
        @RunWith(PowerMockRunner.class)
    @PrepareForTest(StringUtil.class)
    public class StringUtilInstrumentedTest {
        private static String TAG;
        private Context context;
    
        @Before
        public void init() {
            TAG = StringUtilInstrumentedTest.class.getName();
            context = InstrumentationRegistry.getTargetContext();
        }
    
        @Test
        public void decliningAge() {
            // mock all the static methods in a class called "StringUtil"
            mockStatic(StringUtil.class);
            // use Mockito to set up your expectation
            String expected = "first";
            when(StringUtil.decliningAge(context, 1)).thenReturn(expected);
            assertThat(StringUtil.decliningAge(context, 1), is(expected));
        }
    }

```

But when I run this test I get error:

```
java.lang.ClassNotFoundException: com.mycompany.StringUtilInstrumentedTest
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:324)
at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:161)
at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:48)
at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:111)
at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:71)
at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:34)
at java.lang.reflect.Constructor.newInstance(Native Method)
at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
at android.support.test.internal.runner.junit4.AndroidAnnotatedBuilder.runnerForClass(AndroidAnnotatedBuilder.java:77)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
at org.junit.runner.Computer.getRunner(Computer.java:40)
at org.junit.runner.Computer$1.runnerForClass(Computer.java:31)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
at org.junit.runners.Suite.<init>(Suite.java:81)
at org.junit.runner.Computer.getSuite(Computer.java:28)
at android.support.test.internal.runner.TestRequestBuilder.classes(TestRequestBuilder.java:789)
at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:753)
at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:354)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:260)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
Caused by: java.lang.IllegalStateException: Failed to transform class with name com.mycompany.StringUtilInstrumentedTest. Reason: com.mycompany.StringUtilInstrumentedTest
at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:284)
at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:192)
at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:77)
at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:67)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
... 26 more
Caused by: javassist.NotFoundException: com.mycompany.StringUtilInstrumentedTest
at javassist.ClassPool.get(ClassPool.java:452)
at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:262)
... 30 more

```

**Comment by thekingnothing** [comment]
@alexei28, as I understand it's a duplicate for #776 with a bit more information, so please comment original issue instead creating a new issue.
