### ISSUE TITLE
When mocking protected and show error:MethodNotFoundException

### ISSUE THREAD

**Issue by yujishe** [powermock/powermock#797]
I do JUnit test , mock protected mothod when the show shows an exception.Made me confused it is that I mock another protected method and  run was successful. Here's my code.

```

   public class ClassProtected {
	protected void DateToJSon(String date){
		System.out.println("Date to JSON "+date);
	}
	
	protected String foo() {
        String someValue = null;
        return someValue;
    }
}

public class ClassInvoic extends ClassProtected {

	public String actionMethod() {
		String str = "dfsfsfds";
		this.DateToJSon(str);
		return "success";
	}

	public String boo() {
		String fooString = this.foo();
		return fooString;
	}
}

```

```
@RunWith(PowerMockRunner.class)
@PrepareForTest({ClassInvoic.class,ClassProtected.class})
public class ClassInvoicTest {

	@Test
	public void testActionMethod() throws Exception {
		ClassInvoic spy = PowerMockito.spy(new ClassInvoic());
		PowerMockito.doNothing().when(spy, "DateToJSon");
		String result = spy.actionMethod();
		Assert.assertEquals("success", result);
	}
	
	@Test
    public void testBoo() throws Exception {
		ClassInvoic child = PowerMockito.spy(new ClassInvoic());
        PowerMockito.when(child, "foo").thenReturn("mockValue");
        String boo = child.boo();
        Assert.assertEquals(null, boo);
    }

}
```

When I run the testActionMethod method alone, the result went wrong and did not pass. But when I run another test, it succeeds. Here is the error message:

```

org.powermock.reflect.exceptions.MethodNotFoundException: No method found with name 'DateToJSon[]' with parameter types: [ <none> ] in class powermockDemo.ClassInvoic.
	at org.powermock.reflect.internal.WhiteboxImpl.throwExceptionIfMethodWasNotFound(WhiteboxImpl.java:1110)
	at org.powermock.reflect.internal.WhiteboxImpl.findMethodOrThrowException(WhiteboxImpl.java:903)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:798)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:666)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.api.mockito.internal.expectation.PowerMockitoStubberImpl.when(PowerMockitoStubberImpl.java:97)
	at powermockDemo.test.ClassInvoicTest.testActionMethod(ClassInvoicTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:316)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:87)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:300)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:288)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:208)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:121)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:123)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

**Comment by thekingnothing** [comment]
`PowerMockito.doNothing().when(spy, "DateToJSon");` 
Here you are using `<T> void when(T mock, String methodToExpect, Object... arguments) throws Exception;`. As you may see method has 3 arguments. When you do not pass 3rd arguments as in your case then PowerMock looks for method with name `methodToExpect` but without arguments. 

In you case `protected void DateToJSon(String date)` has one parameter. So PowerMock cannot find a method and throws exception. To fix it you need add argument.

**Comment by ghost** [comment]
Please help me to resolved error: https://stackoverflow.com/questions/52052648/org-powermock-reflect-exceptions-methodnotfoundexception-no-method-found-with-n
