### ISSUE TITLE
A question on PowerMock setup

### ISSUE THREAD

**Issue by wshao518** [powermock/powermock#800]
`Hi` there,

We are trying to run some Spring Boot based unit test and running into an issue. We are trying to reuse the Spring Test Context, since it’s expensive to be created. Spring uses a static cache to save the test contexts and will reuse it when it matches the criteria. Here is how the code looks like:

```java
public class DefaultCacheAwareContextLoaderDelegate implements CacheAwareContextLoaderDelegate {

   private static final Log logger = LogFactory.getLog(DefaultCacheAwareContextLoaderDelegate.class);

   /**
    * Default static cache of Spring application contexts.
    */
   static final ContextCache defaultContextCache = new DefaultContextCache();
   …
}
```

On the other hand I am trying to use PowerMock to delegate to SpringRunner and here is how I put it:

```java
@RunWith(PowerMockRunner.class)
@PowerMockIgnore({"javax.management.*"})
@PowerMockRunnerDelegate(SpringRunner.class)
@PrepareForTest({A.class, B.class})
@SpringBootTest(webEnvironment = MOCK, classes = TestWebApplication.class)
public abstract class JUnitTest {
	…
}
```

But this setup will always error out on the second test class when the first test will load and complete successfully. So I debug into the test frameworks and found that the **_defaultContextCache_** is being recreated when the second test class is being setup by PowerMock delegate to **_SpringRunner(TestClassInstance)_**. Now I am suspecting that PowerMock is using a different ClassLoader for a different test class. I am using the latest 1.7 RC04. I am wondering if anyone knows how to avoid this error, or there is a better way to set it up? Thanks!

Regards

Weili

**Comment by thekingnothing** [comment]
> Now I am suspecting that PowerMock is using a different ClassLoader for a different test class.
Yes, you are right. PowerMock creates a new ClassLoader for each TestChunk. TestChunk it's either a test class with `@PrepareForTest`or a test method with `@PrepareForTest`. 

You can try to add `DefaultCacheAwareContextLoaderDelegate` to `@PowerMockIgnore`. In this case the`DefaultCacheAwareContextLoaderDelegate` is loaded to system class loader. So, it will not be re-created.

**Comment by zhanjiejun** [comment]
I have tried to add DefaultCacheAwareContextLoaderDelegate to @PowerMockIgnore.
```
@PowerMockIgnore({ "javax.management.*", "org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate" })
```
But when i run the test case:
```
java.lang.IllegalStateException: Could not load CacheAwareContextLoaderDelegate [class org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate]
	at org.springframework.test.context.BootstrapUtils.createCacheAwareContextLoaderDelegate(BootstrapUtils.java:101)
	at org.springframework.test.context.BootstrapUtils.createBootstrapContext(BootstrapUtils.java:70)
	at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:105)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTestContextManager(SpringJUnit4ClassRunner.java:152)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.<init>(SpringJUnit4ClassRunner.java:143)
	at org.springframework.test.context.junit4.SpringRunner.<init>(SpringRunner.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.powermock.reflect.internal.WhiteboxImpl.createInstance(WhiteboxImpl.java:1408)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeConstructor(WhiteboxImpl.java:1256)
	at org.powermock.reflect.Whitebox.invokeConstructor(Whitebox.java:497)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$1.call(DelegatingPowerMockRunner.java:101)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$1.call(DelegatingPowerMockRunner.java:97)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.withContextClassLoader(DelegatingPowerMockRunner.java:132)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.createDelegate(DelegatingPowerMockRunner.java:96)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.<init>(DelegatingPowerMockRunner.java:64)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:172)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:48)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:108)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:71)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:36)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalArgumentException: class org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate is not assignable to interface org.springframework.test.context.CacheAwareContextLoaderDelegate
	at org.springframework.util.Assert.assignableCheckFailed(Assert.java:407)
	at org.springframework.util.Assert.isAssignable(Assert.java:357)
	at org.springframework.util.Assert.isAssignable(Assert.java:369)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:124)
	at org.springframework.test.context.BootstrapUtils.createCacheAwareContextLoaderDelegate(BootstrapUtils.java:98)
	... 44 more


```

**Comment by wshao518** [comment]
You cannot, because it screws up the entire dependency tree. I played around it and finally gave up. For me, I ended up with loading the test context multiple times, which doesn't seem to be very slow.

**Comment by zhanjiejun** [comment]
All right...thanks for your reply^^
