### ISSUE TITLE
java.lang.IllegalStateException: Extension API internal error: org.powermock.api.extension.reporter.MockingFrameworkReporterFactoryImpl could not be located in classpath.

### ISSUE THREAD

**Issue by gaponte1985** [powermock/powermock#813]
Hi,

I am getting a java.lang.IllegalStateException: Extension API internal error: org.powermock.api.extension.reporter.MockingFrameworkReporterFactoryImpl could not be located in classpath.
 
When I try this: 

@RunWith(PowerMockRunner.class )
@PrepareForTest (Cucumber.class) 
@PowerMockRunnerDelegate(DataProviderRunner.class) 
// this is a data provider that allow interact with Junit. https://github.com/TNG/junit-dataprovider. 

objc[2044]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java (0x10ea6d4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10fabe4e0). One of the two will be used. Which one is undefined.
java.lang.IllegalStateException: Extension API internal error: org.powermock.api.extension.reporter.MockingFrameworkReporterFactoryImpl could not be located in classpath.
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.getFrameworkReporterFactory(AbstractTestSuiteChunkerImpl.java:185)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.getMockingFrameworkReporter(JUnit4TestSuiteChunkerImpl.java:140)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:119)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

I can see that the dataprovider is trying to run, but the cucumber is not. all anotation I have in my dataprovider class 

On my decency I have 

 <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4</artifactId>
            <version>1.6.6</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-easymock</artifactId>
            <version>1.6.6</version>
            <scope>test</scope>
        </dependency>

**Comment by thekingnothing** [comment]
It's very strange, because the class `MockingFrameworkReporterFactoryImpl` locates in the `powermock-api-easymock ` module. Could you check is the class really located in jar?

**Comment by gaponte1985** [comment]
I reload the pom file and the jar appear but know I getting the follow error:

objc[15832]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java (0x10ea144c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10eadc4e0). One of the two will be used. Which one is undefined.

java.lang.VerifyError: Stack map does not match the one at exception handler 141
Exception Details:
  Location:
    org/fluentlenium/adapter/FluentAdapter.<init>()V @141: astore
  Reason:
    Type uninitializedThis (current frame, locals[0]) is not assignable to 'org/fluentlenium/adapter/FluentAdapter' (stack map, locals[0])
  Current Frame:
    bci: @131
    flags: { flagThisUninit }
    locals: { uninitializedThis, uninitializedThis, 'org/fluentlenium/adapter/DefaultFluentControlContainer', 'java/lang/Object', 'java/lang/Object' }
    stack: { 'java/lang/Throwable' }
  Stackmap Frame:
    bci: @141
    flags: { }
    locals: { 'org/fluentlenium/adapter/FluentAdapter', 'org/fluentlenium/adapter/FluentAdapter', 'org/fluentlenium/adapter/DefaultFluentControlContainer', 'java/lang/Object', 'java/lang/Object' }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0x0000000: 2a00 0000 0001 4c01 4d13 0016 b800 1c03
    0x0000010: bd00 0413 001e b800 22b8 0028 4e2d b200
    0x0000020: 2ca5 002f 2dc1 002e 9900 20b8 0034 1300
    0x0000030: 16b8 001c 1204 01b6 003a b600 3e01 b600
    0x0000040: 42c0 0011 4da7 0008 2dc0 0011 4da7 000b
    0x0000050: bb00 1159 b700 444d 2c4d 4c13 0046 b800
    0x0000060: 4904 bd00 0459 032c 5313 004b b800 22b8
    0x0000070: 004e 3a04 1904 b200 2ca5 000a 2ab7 004f
    0x0000080: a700 0a2b 2cb7 0051 0157 a700 0f3a 0701
    0x0000090: 3a06 2ab8 0057 1907 bf01 3a06 2ab8 0057
    0x00000a0: b1                                     
  Exception Handler Table:
    bci [128, 141] => handler: 141
  Stackmap Table:
    full_frame(@72,{UninitializedThis,Null,Null,Object[#4]},{UninitializedThis})
    full_frame(@77,{UninitializedThis,Null,Object[#17],Object[#4]},{UninitializedThis})
    full_frame(@80,{UninitializedThis,Null,Null,Object[#4]},{UninitializedThis})
    full_frame(@88,{UninitializedThis,Null,Object[#17],Object[#4]},{UninitializedThis})
    full_frame(@131,{UninitializedThis,UninitializedThis,Object[#17],Object[#4],Object[#4]},{})
    full_frame(@138,{Object[#2],Object[#2],Object[#17],Object[#4],Object[#4]},{})
    same_locals_1_stack_item_frame(@141,Object[#19])
    full_frame(@153,{Object[#2],Object[#2],Object[#17],Object[#4],Object[#4]},{})


	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructors(Class.java:1651)
	at org.junit.runners.model.TestClass.<init>(TestClass.java:47)
	at org.junit.runners.ParentRunner.createTestClass(ParentRunner.java:88)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:83)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
	at com.tngtech.java.junit.dataprovider.DataProviderRunner.<init>(DataProviderRunner.java:77)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.powermock.reflect.internal.WhiteboxImpl.createInstance(WhiteboxImpl.java:1408)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeConstructor(WhiteboxImpl.java:1256)
	at org.powermock.reflect.Whitebox.invokeConstructor(Whitebox.java:497)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$1.call(DelegatingPowerMockRunner.java:102)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$1.call(DelegatingPowerMockRunner.java:98)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.withContextClassLoader(DelegatingPowerMockRunner.java:133)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.createDelegate(DelegatingPowerMockRunner.java:97)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.<init>(DelegatingPowerMockRunner.java:65)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:172)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:48)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:108)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:71)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255




I am using this annotation not sure if is correct. 

@RunWith(PowerMockRunner.class )
@PowerMockRunnerDelegate(DataProviderRunner.class)
@PrepareForTest(Cucumber.class)

**Comment by thekingnothing** [comment]
1) Are you sure that you need `Cucumber.class` prepared for test? 
2) Try to add `org.fluentlenium.adapter` package to `@PowerMockIgnore`. 
3) Please, check version of javassist.

**Comment by gaponte1985** [comment]
1. Yes I think so, I  need to run a  runnerclass of cucumber.
2. I dont know what you meant with this
3. <version>3.12.1.GA</version>
