### ISSUE TITLE
VerifyError when using nested constructors in test classes

### ISSUE THREAD

**Issue by lennartfricke** [powermock/powermock#822]
Hello, 
the following example fails to run:

```java
  @RunWith(PowerMockRunner.class)
  public class Example {
  	public Example() {
  		this("fail");
  	}
  	
  	public Example(String test)  {
  		
  	}
  	
      @Test public void test() {
  
      }
  }
```

with this Stacktrace

```
java.lang.VerifyError: Stack map does not match the one at exception handler 53
Exception Details:
  Location:
    Example.<init>()V @53: astore
  Reason:
    Type uninitializedThis (current frame, locals[0]) is not assignable to 'Example' (stack map, locals[0])
  Current Frame:
    bci: @43
    flags: { flagThisUninit }
    locals: { uninitializedThis, uninitializedThis, 'java/lang/String', top, 'java/lang/Object' }
    stack: { 'java/lang/Throwable' }
  Stackmap Frame:
    bci: @53
    flags: { }
    locals: { 'Example', 'Example', 'java/lang/String', top, 'java/lang/Object' }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0x0000000: 2a12 154d 4c12 16b8 001c 04bd 0004 5903
    0x0000010: 2c53 121e b800 22b8 0028 3a04 1904 b200
    0x0000020: 2ca5 000a 2ab7 002e a700 0a2b 2cb7 0030
    0x0000030: 0157 a700 0f3a 0701 3a06 2ab8 0036 1907
    0x0000040: bf01 3a06 2ab8 0036 b1                 
  Exception Handler Table:
    bci [40, 53] => handler: 53
  Stackmap Table:
    full_frame(@43,{UninitializedThis,UninitializedThis,Object[#18],Top,Object[#4]},{})
    full_frame(@50,{Object[#2],Object[#2],Object[#18],Top,Object[#4]},{})
    same_locals_1_stack_item_frame(@53,Object[#11])
    full_frame(@65,{Object[#2],Object[#2],Object[#18],Top,Object[#4]},{})

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.getTestMethods(PowerMockJUnit44RunnerDelegateImpl.java:109)
```

I'm not proficient enough in java internals to get to the cause of this error.

I test against java 1.6.0_45, 1.7.0_80, 1.8.0_66 and 1.8.0_131, they all throw a VerifyError.

**Comment by thekingn0thing** [comment]
What version of PowerMock and Javassist did you use?

**Comment by lennartfricke** [comment]
powermock 1.7.0 & javaassist 3.21.0-GA

**Comment by pjBooms** [comment]
FYI: here is explanation what is going on:

"this" can be used in exception handler at bci 53 that is expected to be initialized (a constructor was called on it). The (exception) control can go from basic block at bci 43 to the handler. However "this" is still not initialized at 43 basic block (constructor was not called on it).
So definetely PowerMock inserted an incorrect try/catch block to the constructor.
