### ISSUE TITLE
Not able run Powermock test cases in Android Studio 3.0 with gradle version 3.0.1

### ISSUE THREAD

**Issue by androcreator** [powermock/powermock#899]
Hi, We have written around 1000 test cases with powermockito in our code base.
The issue is when ever we are using Android Studio 2.3.3 with Gradle 2.2.0 all our test cases were working. But When we moved to Android Studio 3.0 with gradle 3.0.1 all the test cases were failing with diffetent logs.

Is this something you can debug and fix?
        Yes I can debug my test cases but before fixing all the test cases which which will take more manual work. But we want to know why POWERMOCKITO test cases are failing in Android Studio 3.

we are using dependency as follows:
    testImplementation "org.mockito:mockito-core:2.0.5-beta"
    testImplementation("org.powermock:powermock-api-mockito2:1.6.6") 
    testImplementation("org.powermock:powermock-module-junit4-rule:1.6.6") 
    testImplementation("org.powermock:powermock-module-junit4:1.6.6") 
    testImplementation("org.powermock:powermock-classloading-xstream:1.6.6") 

What Exception we are getting:
     Most of the test cases are failing  Caused by: java.lang.RuntimeException: Stub!(Again its like powermockito is not able to find android implementation of  files like HandlerThread.java, ContentValues.java,TextUtils.java....etc).

For Example :
java.lang.RuntimeException: Stub!
at android.text.TextUtils.isEmpty(TextUtils.java:48)

java.lang.RuntimeException: Stub!
at android.os.Bundle.<init>(Bundle.java:5)

Which is working fine in Android Studio 2.3. Same is failing in Android Studio 3.0

What steps will reproduce the problem?
     Just Import you existing project(Project should have PowerMockito testcases ) in to Android Studio 3.0 and upgrade your Gradle version to 3.0.1 Added the following dependency in you project level build.gradle file 'com.android.tools.build:gradle:3.0.1'.

What is the expected output?
            All test cases should pass as it is working in Android Studio 2.3. I feel there are braking changes with Android studio upgrade.

What do you see instead?
          We are seeing all powermock test case were failing

Kindly Please help me to fix these issues, and have spent more that 20 days to fix these but am not getting proper documentation for this issues.

**Comment by SrishtiRoy** [comment]
is this issue solved

**Comment by androcreator** [comment]
We fixed al the testcases.. not sure this issue is resolved in Android 3.0
