### ISSUE TITLE
Power mock is not working with JDK 9, Getting initializationError(PowermockTest): java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by michaelpog** [powermock/powermock#901]
Hi I have a test project that uses Powermock
https://github.com/michaelpog/powermocktest
When I try to build this project with maven on JDK 8, it builds and runs the unit tests just fine.

However when I run it with JDK 9, I'm getting this failure
```
initializationError(PowermockTest)  Time elapsed: 0.006 sec  <<< ERROR!
org.objenesis.ObjenesisException: java.lang.reflect.InvocationTargetException
        at org.objenesis.instantiator.sun.SunReflectionFactoryHelper.newConstructorForSerialization(SunReflectionFactoryHelper.java:54)
        at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.<init>(SunReflectionFactoryInstantiator.java:41)
        at org.objenesis.strategy.StdInstantiatorStrategy.newInstantiatorOf(StdInstantiatorStrategy.java:67)
        at org.objenesis.ObjenesisBase.getInstantiatorOf(ObjenesisBase.java:94)
        at org.powermock.reflect.internal.WhiteboxImpl.newInstance(WhiteboxImpl.java:259)
        at org.powermock.reflect.Whitebox.newInstance(Whitebox.java:139)
        at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.getPowerMockTestListenersLoadedByASpecificClassLoader(AbstractTestSuiteChunkerImpl.java:95)
        at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:174)
        at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:48)
        at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:108)
        at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:71)
        at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:36)
        at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:34)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
        at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:250)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.objenesis.instantiator.sun.SunReflectionFactoryHelper.newConstructorForSerialization(SunReflectionFactoryHelper.java:44)
        ... 34 more
Caused by: java.lang.IllegalAccessError: class jdk.internal.reflect.ConstructorAccessorImpl loaded by org/powermock/core/classloader/MockClassLoader cannot access jdk/internal/reflect superclass jdk.internal.reflect.MagicAccessorImpl
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
        at org.powermock.core.classloader.MockClassLoader.loadUnmockedClass(MockClassLoader.java:262)
        at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:206)
        at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:89)
        at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:79)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
        at org.powermock.core.classloader.MockClassLoader.loadUnmockedClass(MockClassLoader.java:262)
        at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:206)
        at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:89)
        at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:79)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        at java.base/jdk.internal.misc.Unsafe.defineClass0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.defineClass(Unsafe.java:1173)
        at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
        at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:400)
        at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
        at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:112)
        at java.base/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:434)
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:404)
        at jdk.unsupported/sun.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:103)
        ... 39 more


Results :

Tests in error: 
  initializationError(PowermockTest): java.lang.reflect.InvocationTargetException
````

Please see the exact steps to reproduce in this reproducer
https://github.com/michaelpog/powermocktest
Thank you

**Comment by michaelpog** [comment]
@thekingnothing I was wondering if Powermock is undergoing any development to support JDK 9+?
I noticed that issues don't get a lot of responses on Github. Should I ask this question in a different forum?
Thank you.

**Comment by thekingn0thing** [comment]
Hi,

There is some sort of supporting JKD 9 in beta versions of PowerMock 2.0. I’m not going to implement supporting Java 9 or 10 in the PowerMock 1.x

Right now the project is in frozen state because I do not have enough time. I hope I will be able to return back to project soon.

Best Regards,
Arthur Zagretdinov

On 19 Apr 2018, at 22:50, michaelpog <notifications@github.com<mailto:notifications@github.com>> wrote:


@thekingnothing<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthekingnothing&data=02%7C01%7C%7C50eb5f341b9244531bff08d5a63f823a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636597714046457219&sdata=012yCPfr%2Ft%2BdCECOmCmP5T%2FdnfLc2N6OQo%2Ft8ukDCkc%3D&reserved=0> I was wondering if Powermock is undergoing any development to support JDK 9+?
Thank you

**Comment by markkolich** [comment]
@michaelpog did you try with powermock `2.0.0-beta.5` and mockito2 `2.18.0`?

I had a similar issue (nearly identical stack trace) and the following worked for me:

```xml
<dependency>
  <groupId>org.mockito</groupId>
  <artifactId>mockito-core</artifactId>
  <version>2.18.0</version>
</dependency>

<dependency>
  <groupId>org.powermock</groupId>
  <artifactId>powermock-api-mockito2</artifactId>
  <version>2.0.0-beta.5</version>
</dependency>
<dependency>
  <groupId>org.powermock</groupId>
  <artifactId>powermock-module-junit4</artifactId>
  <version>2.0.0-beta.5</version>
</dependency>
```

**Comment by saif-software-developer** [comment]
The Tests started failing after I switched to Java **10**, it seems like PoerMock is trying to access some classes but it does not have access to. By the way, I tried to use the dependencies below but that did not solve the issue. 

> Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.973 sec <<< FAILURE! - in com.Test
> initializationError(com.Test)  Time elapsed: 0.007 sec  <<< ERROR!
> org.objenesis.ObjenesisException: java.lang.reflect.InvocationTargetException
> Caused by: java.lang.reflect.InvocationTargetException
> Caused by: java.lang.IllegalAccessError: class jdk.internal.reflect.ConstructorAccessorImpl loaded by org/powermock/core/classloader/MockClassLoader cannot access jdk/internal/reflect superclass jdk.internal.reflect.MagicAccessorImpl

```
<dependencies>
	<dependency>
		<groupId>org.powermock</groupId>
		<artifactId>powermock-module-junit4</artifactId>
		<version>1.7.4</version>
	</dependency>
	<dependency>
		<groupId>org.powermock</groupId>
		<artifactId>powermock-core</artifactId>
		<version>1.7.4</version>
	</dependency>
	<dependency>
		<groupId>org.mockito</groupId>
		<artifactId>mockito-core</artifactId>
		<version>2.18.3</version>
	</dependency>
	<dependency>
		<groupId>org.powermock</groupId>
		<artifactId>powermock-api-mockito2</artifactId>
		<version>1.7.4</version>
		<exclusions>
			<exclusion>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-all</artifactId>
			</exclusion>
		</exclusions>
	</dependency>
</dependencies>
```

**Comment by jayanth-ganganahalli** [comment]
@markkolich 
I tried with the same dependencies, but no luck yet :( still same build issue.

NOTE: I am using OpenJDK 10.1 to build my project.

**Comment by PolinaBevad** [comment]
Have the same issue on PowerMock version 2.0.0-beta.5 on Java 10.0.1 with exception while mocking static methods. 
PowerMock version 2.0.0-beta.5 working only if I also add new versions of net.bytebuddy libraries. So my dependencies are:
```
testCompile 'org.powermock:powermock-api-mockito2:2.0.0-beta.5'
testCompile 'org.powermock:powermock-module-testng:2.0.0-beta.5'
testCompile 'net.bytebuddy:byte-buddy:1.8.3'
testCompile 'net.bytebuddy:byte-buddy-agent:1.8.3'
```
Maybe it will help someone. 
With this two additional dependencies exception dissapear and tests are passed, but I still have a warning in the log:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.powermock.reflect.internal.WhiteboxImpl (file:/home/vardict/.gradle/caches/modules-2/files-2.1/org.powermock/powermock-reflect/2.0.0-beta.5/4ea415348f15620783a1f26343d6732adfa86bc8/powermock-reflect-2.0.0-beta.5.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.powermock.reflect.internal.WhiteboxImpl
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
Hope it will be fixed soon...

**Comment by rusefi** [comment]
@PolinaBevad have you tried under java 9?

I believe there is an issue that powermock java version detection mechanism does not handle java 10 yet.

https://github.com/powermock/powermock/issues/887 maybe?

**Comment by agawish** [comment]
I have the same problem as @PolinaBevad with OpenJDK11

**Comment by praveenksingh** [comment]
> I have the same problem as @PolinaBevad with OpenJDK11

Were you able to solve this ?

**Comment by achandnanimt** [comment]
Anybody found the solution yet? I have the same issue with Java11

**Comment by Mosheer-Ahmad** [comment]
When I upgraded to Jdk 11, I got this exception and a couple of other exceptions. 
I gathered work arounds from multiple pages and finally worked from me. Do these three steps:

- As mentioned in this page, update power mockito version to 2.0.0-beta.5 and mockito version to 2.18.0 (yes both of them. I used 2.0.2 for power mockito and 2.18.0 for mockito). 


- On top of each test class that uses power mockito, add the following annotation: 
@PowerMockIgnore({"javax.management.*", "com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "org.w3c.dom.*",  "com.sun.org.apache.xalan.*", "javax.activation.*"})

If you have a base class that all your test classes extends, you'll only need to change that base class only! For example: 

@RunWith(PowerMockRunner.class)
@PowerMockIgnore({"javax.management.*", "com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "org.w3c.dom.*",
        "com.sun.org.apache.xalan.*", "javax.activation.*"})
public class PowerMockitoBaseRunner {
}


- Add javassist dependency, version 3.24.1-GA: 
 as mentioned here: https://github.com/powermock/powermock/issues/933

<dependency>
	<groupId>org.javassist</groupId>
	<artifactId>javassist</artifactId>
	<version>3.24.1-GA</version>
	<scope>test</scope>
</dependency>



Those three steps together worked for me and all tests are passing now!

**Comment by DJViking** [comment]
I tried getting our API to build with Java 11. The API has not been migrated to Java modules.

Using the latest Powermock 2.0.2 and Mockito 2.23.0.
The three step approach, why use old releases of powermock and mockito?


First we get an IllegalAccessError that seems to be a problem stemming from Log4j

```java
    java.lang.IllegalAccessError: class javax.xml.parsers.FactoryFinder (in unnamed module @0x47305429) cannot access class jdk.xml.internal.SecuritySupport (in module java.xml) because module java.xml does not export jdk.xml.internal to unnamed module @0x47305429
        at javax.xml.parsers.FactoryFinder.<clinit>(FactoryFinder.java:69)
        at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:140)
        at org.apache.logging.log4j.core.config.xml.XmlConfiguration.newDocumentBuilder(XmlConfiguration.java:191)
        at org.apache.logging.log4j.core.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:92)
        at org.apache.logging.log4j.core.config.xml.XmlConfigurationFactory.getConfiguration(XmlConfigurationFactory.java:46)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:453)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:381)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:260)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:615)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:636)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:231)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:581)
        at no.company.api.listener.ConnectionListener.<clinit>(ConnectionListener.java:12)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at javassist.runtime.Desc.getClassObject(Desc.java:42)
        at javassist.runtime.Desc.getClassType(Desc.java:151)
        at javassist.runtime.Desc.getType(Desc.java:121)
        at javassist.runtime.Desc.getType(Desc.java:77)
```

Second we get a lot of NoClassDefFound for our own classes.

```java
no.company.api.MyApiTestTest > validateConnectionUpdate FAILED
    java.lang.NoClassDefFoundError: Could not initialize class no.company.api.MyApi
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at javassist.runtime.Desc.getClassObject(Desc.java:42)
        at javassist.runtime.Desc.getClassType(Desc.java:151)
        at javassist.runtime.Desc.getType(Desc.java:121)
        at javassist.runtime.Desc.getType(Desc.java:77)
        at no.company.api.MyApiTest.init(MyApiTest.java:50)
```

  
All other tests that does not use Powermock was able to run without problems.

**Comment by Mosheer-Ahmad** [comment]
I first used the beta version of power mockito as mentioned in previous comments here, but then changed that to 2.0.2 for power mockito and 2.18.0 for mockito. 
Open the power mockito tests that are failing and make sure each test has the following @PowerMockIgnore. I think this should solve (java.lang.IllegalAccessError: class **javax.xml**.parsers.FactoryFinder .......)

@PowerMockIgnore({"javax.management.", "com.sun.org.apache.xerces.", **"javax.xml."**, "org.xml.", "org.w3c.dom.",
"com.sun.org.apache.xalan.", "javax.activation.*"})

Not sure about the other exception.

**Comment by DJViking** [comment]
First PowerMockIgnore did not work for me.

When I added wildcard for each ignore then it worked.
```java
@PowerMockIgnore({ "javax.management.*", "com.sun.org.apache.xerces.*", "javax.xml.*",
        "org.xml.*", "org.w3c.dom.*", "com.sun.org.apache.xalan.*", "javax.activation.*" })
```

It also got rid of all the java.lang.NoClassDefFoundError.

**Comment by xerx593** [comment]
good to see you active again, @thekingnothing! a gentle reminder of this issue (:+1: ) and a cross ref to stackoverflow: https://stackoverflow.com/q/50456726/592355

**Comment by lhmzhou** [comment]
You can also configure the annotation globally. More information provided [here](https://github.com/powermock/powermock/wiki/PowerMock-Configuration).

**Comment by Timzhouyes** [comment]
> 

hello DJViking, could I know the reason why if ignore those packages then this can be solved? Thanks so much for helping!
