### ISSUE TITLE
java.lang.NoSuchMethodError: org.mockito.internal.creation.MockSettingsImpl.getName()Ljava/lang/String; 	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.toInstanceName(DefaultMockCreator.java:149)

### ISSUE THREAD

**Issue by Forever-Sun** [powermock/powermock#919]
when I use powermock 1.7.1 with maven， the pom.xml is
`
<dependency>
			<groupId>org.powermock</groupId>
			<artifactId>powermock-module-junit4</artifactId>
			<version>1.7.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.powermock</groupId>
			<artifactId>powermock-api-mockito2</artifactId>
			<version>1.7.1</version>
			<scope>test</scope>
		</dependency>
`
the mockito version is 2.8.9.
when i run with junit4，there is the error:
java.lang.NoSuchMethodError: org.mockito.internal.creation.MockSettingsImpl.getName()Ljava/lang/String; 	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.toInstanceName(DefaultMockCreator.java:149)

I see the class DefaultMockCreator, method toInstanceName, line 149:
`
String settingName = ((MockSettingsImpl<?>) mockSettings).getName();
`
but in the mockito 2.8.9, the class MockSettingsImpl had no method named 'getName()', it has a method named 'getMockName()'.

**Comment by Forever-Sun** [comment]
this is my jar dependency Conflict。
