### ISSUE TITLE
Mixed primitive and boxed parameters stubbing issue

### ISSUE THREAD

**Issue by tonydlo** [powermock/powermock#921]
As requested in the forum, opening a defect for this.

**Summary**
Something doesn't seem to match properly with a Boxed and primitive Long and int respectively for a public (or protected) method. However, the exact same public method with **both** boxed types work. And the same mixed method works when it is **private**.

**What steps will reproduce the problem?**
Unit under test
```
package com.example;

public class PrimitiveAndBoxedStubbing {

	public void cannotStubThisPublicMethod(Long param2, int param1) {
	}

	public void canStubThisPublicMethod(Long param2, Integer param1) {
	}

	private void canStubThisPrivateMethod(Long param2, int param1) {
	}

}
```

Test cases
```
package com.example;

import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.validateMockitoUsage;

import org.junit.After;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

@RunWith(PowerMockRunner.class)
public class PrimitiveAndBoxedStubbingTest {
	private PrimitiveAndBoxedStubbing t;

	@Test
	@PrepareForTest({ PrimitiveAndBoxedStubbing.class })
	public void cannotStubThisPublicMethodTest() throws Exception {
		t = PowerMockito.spy(new PrimitiveAndBoxedStubbing());
		PowerMockito.doNothing().when(t, "cannotStubThisPublicMethod", anyLong(), anyInt());
	}

	@Test
	@PrepareForTest({ PrimitiveAndBoxedStubbing.class })
	public void canStubThisPublicMethodTest() throws Exception {
		t = PowerMockito.spy(new PrimitiveAndBoxedStubbing());
		PowerMockito.doNothing().when(t, "canStubThisPublicMethod", anyLong(), anyInt());
	}

	@Test
	@PrepareForTest({ PrimitiveAndBoxedStubbing.class })
	public void canStubThisPrivateMethodTest() throws Exception {
		t = PowerMockito.spy(new PrimitiveAndBoxedStubbing());
		PowerMockito.doNothing().when(t, "canStubThisPrivateMethod", anyLong(), anyInt());
	}

	@After
	public void tearDown() {
		validateMockitoUsage();
	}
}

```

**What is the expected output?**
All test cases to pass.

**What do you see instead?**
The test `cannotStubThisPublicMethodTest` fails with:
```
org.powermock.reflect.exceptions.MethodNotFoundException: No methods matching the name(s) cannotStubThisPublicMethod were found in the class hierarchy of class com.example.PrimitiveAndBoxedStubbing$MockitoMock$45603822.
	at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1783)
	at org.powermock.reflect.internal.WhiteboxImpl.getBestMethodCandidate(WhiteboxImpl.java:993)
	at org.powermock.reflect.internal.WhiteboxImpl.findMethodOrThrowException(WhiteboxImpl.java:870)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:807)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:675)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.api.mockito.internal.expectation.PowerMockitoStubberImpl.when(PowerMockitoStubberImpl.java:95)
	at com.example.PrimitiveAndBoxedStubbingTest.cannotStubThisPublicMethodTest(PrimitiveAndBoxedStubbingTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

**What version of the product are you using?** 
I'm using Java 1.8 with PowerMockito 1.7.4 and its Mockito transitive dependency (2.8.9) through Gradle: 'org.powermock:powermock-api-mockito2:1.7.4'.

**Comment by wgslucky** [comment]
You can try put @PrepareForTest on  PrimitiveAndBoxedStubbingTest class and not method
