### ISSUE TITLE
@RunWith(PowerMockRunner.class)  lead ClassCastException  when use org.apache.zookeeper.ClientCnxn 

### ISSUE THREAD

**Issue by okhiwell** [powermock/powermock#922]
when use @RunWith(PowerMockRunner.class) before Test class:
I got the Message below when I use org.apache.zookeeper.ClientCnxn to get document from solr

10:34:35.028 [main] DEBUG org.apache.zookeeper.ClientCnxn - zookeeper.disableAutoWatchReset is false
10:34:35.063 [main] INFO org.apache.solr.common.cloud.ConnectionManager - Waiting for client to connect to ZooKeeper
10:34:35.070 [main-SendThread(172.14.104.105:2181)] WARN org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.lang.ClassCastException: class sun.security.provider.ConfigFile
	at java.lang.Class.asSubclass(Class.java:3404)
	at javax.security.auth.login.Configuration$2.run(Configuration.java:254)
	at javax.security.auth.login.Configuration$2.run(Configuration.java:247)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:246)
	at org.apache.zookeeper.client.ZooKeeperSaslClient.<init>(ZooKeeperSaslClient.java:119)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:949)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1003)
10:34:35.175 [main-SendThread(172.14.104.103:2181)] WARN org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.lang.ClassCastException: class sun.security.provider.ConfigFile
	at java.lang.Class.asSubclass(Class.java:3404)
	at javax.security.auth.login.Configuration$2.run(Configuration.java:254)
	at javax.security.auth.login.Configuration$2.run(Configuration.java:247)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:246)
	at org.apache.zookeeper.client.ZooKeeperSaslClient.<init>(ZooKeeperSaslClient.java:119)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:949)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1003)
10:34:35.275 [main-SendThread(172.14.104.101:2181)] WARN org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.lang.ClassCastException: class sun.security.provider.ConfigFile

-------------------------------------------------------
when I remove the  @RunWith(PowerMockRunner.class)  It runs ok!

**Comment by amir-shalem** [comment]
Can be the same issue as https://github.com/FasterXML/jackson-modules-base/issues/53 ?
Can you check whether powermock version `1.7.0RC4` works for you, but `1.7.0` fails?

**Comment by okhiwell** [comment]
still have the same problem

**Comment by mahesh-kandpal** [comment]
Hi, I found the same problem with Mac.class from javax.crypto package. I have used it only for a single test, but it tries to initialize for all test methods.
java.lang.ClassCastException: com.sun.crypto.provider.HmacCore$HmacSHA256 cannot be cast to javax.crypto.MacSpi
	at javax.crypto.Mac.chooseProvider(Mac.java:344)
	at javax.crypto.Mac.init(Mac.java:410)
	...
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:88)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:86)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:33)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:45)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

**Comment by yueki1993** [comment]
@mahesh-kandpal 
https://github.com/powermock/powermock/issues/294#issuecomment-124345964
Adding annotation `@PowerMockIgnore({"javax.crypto.*"})` might solve your problem.

**Comment by qq570575562** [comment]
转自: http://blog.sina.com.cn/s/blog_791e34210102y2d3.html 

jdk8中设置环境变量会导致zookeeper 3.4.6读取配置信息失败。因为zk3.4.6对1.7支持好些。把环境jdk改成1.7就好了。
如下问题，zk client报错。

WARN [org.apache.zookeeper.ClientCnxn] - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect java.lang.ClassCastException: class sun.security.provider.ConfigFile at java.lang.Class.asSubclass(Class.java:3391) at javax.security.auth.login.Configuration$2.run(Configuration.java:254) at javax.security.auth.login.Configuration$2.run(Configuration.java:247) at java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.login.Configuration.getConfiguration(Configuration.java:246) at org.apache.zookeeper.client.ZooKeeperSaslClient.(ZooKeeperSaslClient.java:113) at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:949) at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1003)

**Comment by shalk** [comment]
I met the same problem and solve it by add this line
```
@PowerMockIgnore({"javax.security.*" })
```
----
I tried other values, but only `"javax.security.*"` works for me
```
@PowerMockIgnore({"javax.crypto.*", "javax.security.*", "sun.security.*"})
```
Maybe `@RunWith(PowerMockRunner.class)` conflict with zookeeper 3.4.8
Part of my dependency tree is as follow:
```
com.101tec:zkclient:jar:0.9:compile
 \- org.apache.zookeeper:zookeeper:jar:3.4.8:compile

 org.powermock:powermock-module-junit4:jar:1.7.4:test
 \- org.powermock:powermock-module-junit4-common:jar:1.7.4:test
    +- org.powermock:powermock-reflect:jar:1.7.4:test
    \- org.powermock:powermock-core:jar:1.7.4:test
 org.powermock:powermock-api-mockito:jar:1.7.4:test
 +- org.powermock:powermock-api-mockito-common:jar:1.7.4:test
 \- org.mockito:mockito-core:jar:1.10.19:test
```
