### ISSUE TITLE
Issue using PowerMockObjectFactory explicitly within a `@Factory` method

### ISSUE THREAD

**Issue by Pr0methean** [powermock/powermock#925]
I have a TestNG test class that inherits `@PrepareForTest` and whose constructor takes a parameter. I could previously instantiate it using this method:
```
  @Factory public static Object[] getInstances() throws NoSuchAlgorithmException {
    int[] desiredSeedSizes = {16, 17, 32, 33, 48};
    int maxSize = Cipher.getMaxAllowedKeyLength("AES") / 8
        + AesCounterRandom.COUNTER_SIZE_BYTES;
    List<AesCounterRandomTest> instances = new ArrayList<>(5);
    for (int size : desiredSeedSizes) {
      if (size > maxSize) {
        break;
      } else {
        instances.add(new AesCounterRandomTest(size));
      }
    }
    return instances.toArray();
  }
```
But then I get "cannot be mocked because final class" errors, as though the `@PrepareForTest` annotation weren't present. I'm trying to fix this by using a PowerMockObjectFactory explicitly:
```
  @Factory public static Object[] getInstances()
      throws NoSuchAlgorithmException, NoSuchMethodException {
    Constructor constructor = AesCounterRandomTest.class.getConstructor(int.class);
    PowerMockObjectFactory factory = new PowerMockObjectFactory();
    int[] desiredSeedSizes = {16, 17, 32, 33, 48};
    int maxSize = Cipher.getMaxAllowedKeyLength("AES") / 8
        + AesCounterRandom.COUNTER_SIZE_BYTES;
    List<Object> instances = new ArrayList<>(5);
    for (int size : desiredSeedSizes) {
      if (size > maxSize) {
        break;
      } else {
        System.out.println("Creating instance for size " + size);
        instances.add(factory.newInstance(constructor, size));
      }
    }
    assertFalse(instances.isEmpty());
    return instances.toArray();
  }
```
But this gives:
```
The factory method class io.github.pr0methean.betterrandom.prng.AesCounterRandomTest.getInstances() threw an exception
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
The factory method class io.github.pr0methean.betterrandom.prng.AesCounterRandomTest.getInstances() threw an exception
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:658)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:978)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```
Why isn't this working? If it isn't the proper use of PowerMockObjectFactory, then is there a way to have the `@Factory` method itself use the PowerMock classloader?

**Comment by Pr0methean** [comment]
I've also tried using the old code but making getInstances() an instance method, with a parameterless constructor to create the bootstrap instance. But this gives:
```
Mismatch between instance/method classes:class io.github.pr0methean.betterrandom.prng.AesCounterRandomTest class io.github.pr0methean.betterrandom.prng.AesCounterRandomTest
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:658)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:978)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.apache.maven.plugin.surefire.SurefireHelper.throwException(SurefireHelper.java:235)
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:112)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:354)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1008)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
```
