### ISSUE TITLE
JVM crash when using Java Agent, with Jacoco offline instrumentation

### ISSUE THREAD

**Issue by Pr0methean** [powermock/powermock#926]
While trying to work around #925, I enabled the PowerMock Java Agent per the instructions at https://github.com/powermock/powermock/wiki/PowerMockAgent, except that 1.7.4 was globally replaced with a property that's currently 2.0.0-beta5 (to match the version of the other components of PowerMock I use). I got the following:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project BetterRandom: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\projects\betterrandom\betterrandom\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] Expecting a stackmap frame at branch target 50
[ERROR] Exception Details:
[ERROR] Location:
[ERROR] io/github/pr0methean/betterrandom/seed/AbstractSeedGeneratorTest.$jacocoInit()[Z @4: ifnonnull
[ERROR] Reason:
[ERROR] Expected stackmap frame at this location.
[ERROR] Bytecode:
[ERROR] 0x0000000: b200 2659 c700 2e57 b200 2c06 bd00 1a59
[ERROR] 0x0000010: 0314 002d b800 3453 5904 1235 5359 0505
[ERROR] 0x0000020: b800 3a53 5ab6 003e 5703 32c0 003f 59b3
[ERROR] 0x0000030: 0026 b0
[ERROR] 
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Expecting a stackmap frame at branch target 50
[ERROR] Exception Details:
[ERROR] Location:
[ERROR] io/github/pr0methean/betterrandom/seed/AbstractSeedGeneratorTest.$jacocoInit()[Z @4: ifnonnull
[ERROR] Reason:
[ERROR] Expected stackmap frame at this location.
[ERROR] Bytecode:
[ERROR] 0x0000000: b200 2659 c700 2e57 b200 2c06 bd00 1a59
[ERROR] 0x0000010: 0314 002d b800 3453 5904 1235 5359 0505
[ERROR] 0x0000020: b800 3a53 5ab6 003e 5703 32c0 003f 59b3
[ERROR] 0x0000030: 0026 b0
[ERROR] 
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:658)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:978)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
```
I'm on HotSpot 1.8.0_162-b12.

NB: AbstractSeedGeneratorTest does not have `@PrepareForTest`, but one of its concrete subclasses does.

**Comment by Vampire** [comment]
Probably fixed by #1043
