### ISSUE TITLE
Problem using powermock with robolectric

### ISSUE THREAD

**Issue by rabsr** [powermock/powermock#931]
In Android , I am trying to use Powermock and robolectric together. The documentation tells two ways of doing it. But, I am getting errror with both the approaches.

### Build.gradle
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.robolectric:robolectric:3.8'
    testImplementation "org.robolectric:shadows-multidex:3.0"
    testImplementation "org.powermock:powermock-api-mockito:1.6.6"
    testImplementation "org.powermock:powermock-classloading-xstream:1.6.6"
    testImplementation "org.powermock:powermock-classloading-base:1.6.6"
    testImplementation "org.powermock:powermock-module-junit4:1.6.6"
    testImplementation "org.powermock:powermock-module-junit4-rule:1.6.6"

}
````

### Approach 1:
```
@RunWith(PowerMockRunner.class)
@Config(constants = BuildConfig.class, application = ApplicationMock.class)
@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
@PrepareForTest(ABService.class)
@PowerMockRunnerDelegate(RobolectricTestRunner.class)
public class LoginActivityTest {

    @Test
    public void onClick() throws Exception {
        LoginActivity loginActivity = Robolectric.buildActivity(LoginActivity.class).get();
        PowerMockito.mockStatic(ABService.class);
    }
}
```

Getting the below exception:
```
org.powermock.api.mockito.ClassNotPreparedException: 
The class com.app.service.ABService not prepared for test.
To prepare this class, add class to the '@PrepareForTest' annotation.
In case if you don't use this annotation, add the annotation on class or  method level. 


	at org.powermock.api.mockito.expectation.reporter.MockitoPowerMockReporter.classNotPrepared(MockitoPowerMockReporter.java:32)
	at org.powermock.api.mockito.internal.mockcreation.MockTypeValidatorFactory$DefaultMockTypeValidator.validate(MockTypeValidatorFactory.java:38)
	at org.powermock.api.mockito.internal.mockcreation.AbstractMockCreator.validateType(AbstractMockCreator.java:10)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMock(DefaultMockCreator.java:56)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.mock(DefaultMockCreator.java:46)
	at org.powermock.api.mockito.PowerMockito.mockStatic(PowerMockito.java:71)
	at com.app.activity.LoginActivityTest.onClick(LoginActivityTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$2.call(DelegatingPowerMockRunner.java:148)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$2.call(DelegatingPowerMockRunner.java:140)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.withContextClassLoader(DelegatingPowerMockRunner.java:131)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.run(DelegatingPowerMockRunner.java:140)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

### Approach 2:
```
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, application = ApplicationMock.class)
@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
@PrepareForTest(ABService.class)
public class LoginActivityTest {

    @Rule
    public PowerMockRule rule = new PowerMockRule();

    @Test
    public void onClick() throws Exception {
        LoginActivity loginActivity = Robolectric.buildActivity(LoginActivity.class).get();
        PowerMockito.mockStatic(ABService.class);
    }
}
```

Getting below error:

```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/app/activity/BaseActivity.onActivityResult(IILandroid/content/Intent;)V @22: invokevirtual
  Reason:
    Type 'com/app/activity/BaseActivity' (current frame, stack[1]) is not assignable to 'android/content/Context'
  Current Frame:
    bci: @22
    flags: { }
    locals: { 'com/app/activity/BaseActivity', integer, integer, 'android/content/Intent', 'com/google/android/gms/common/GoogleApiAvailability' }
    stack: { 'com/google/android/gms/common/GoogleApiAvailability', 'com/app/activity/BaseActivity' }
  Bytecode:
    0x0000000: 2a1b 1c2d b700 ad1b 1103 e8a0 0033 b800
    0x0000010: af3a 0419 042a b600 b036 0515 059a 0021
    0x0000020: 2ab8 00b1 b600 b29e 0017 2ab8 00b3 3a06
    0x0000030: 12b5 b800 b63a 0719 0619 07b6 00b7 b1  
  Stackmap Table:
    same_frame(@62)


	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:340)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:84)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:80)
	at com.app.activity.LoginActivityTest.onClick(LoginActivityTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1819)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:801)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:666)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.classloading.AbstractClassloaderExecutor.getResult(AbstractClassloaderExecutor.java:69)
	at org.powermock.classloading.AbstractClassloaderExecutor.executeWithClassLoader(AbstractClassloaderExecutor.java:59)
	at org.powermock.classloading.SingleClassloaderExecutor.execute(SingleClassloaderExecutor.java:67)
	at org.powermock.classloading.AbstractClassloaderExecutor.execute(AbstractClassloaderExecutor.java:43)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:75)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

```

I am following both the approaches in correct way. Can you please tell me what is wrong?

**Comment by halilozercan** [comment]
I'm experiencing the same issue. Any updates on this one?

**Comment by astamato** [comment]
Same!

**Comment by mikehardy** [comment]
If you follow the documentation, but use Robolectric 4.0 you also get a problem - neither of the two documented methods work unfortunately. I got closest (I felt) with approach 1 above, but I also received the "class not prepared" exception. I ended up refactoring so I didn't need the static there and it was testable - which is better code really - but it would be nice if this worked since it is a large legacy code base and I was hoping to put coverage in place before doing the refactor.

**Comment by thesultanster** [comment]
Same Issue! and it's 2019 now

**Comment by AstralStorm** [comment]
Indeed, and you cannot even use the rule with Robolectric 4.2.1 or 4.3 and delegate runners because things break! (It works in 4.0.2. It also works without a delegate runner.)

**Comment by Joseph82** [comment]
Did anybody figure out a possible solution to this problem?

**Comment by ppamorim** [comment]
Also having the a similar issue. Reported at #996.

**Comment by fabianocostaalvarenga** [comment]
Same problem!

**Comment by zj8331182** [comment]
same problem!

**Comment by fqyuan** [comment]
Similar problem when annotated with @Runwith(AndroidJunit4.class), powerMock throws excetpion, when annotated with @Runwith(PowerMockRunner.class) Robolectric throws Exception

**Comment by mikehardy** [comment]
@fqyuan note that mockito allows static mocking now. Example https://github.com/ankidroid/Anki-Android/pull/6682/commits/61106bacfbd061f15564d9ca7340010007213f48

**Comment by fqyuan** [comment]
> @fqyuan note that mockito allows static mocking now. Example [ankidroid/Anki-Android@61106ba](https://github.com/ankidroid/Anki-Android/commit/61106bacfbd061f15564d9ca7340010007213f48)

Thanks for your response, that's great feature

**Comment by ZSmallX** [comment]
You can try below:

```Java
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, application = ApplicationMock.class)
@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
@PrepareForTest(ABService.class)
public class LoginActivityTest {

    @Rule
    public PowerMockRule rule = new PowerMockRule();

    @Before
    public void setUp() throws Exception {
         // let current test thread using Robolectric's SandboxClassLoader.
         Thread.currentThread().setContextClassLoader(Context.class.getClassLoader());
    }

    @Test
    public void onClick() throws Exception {
        LoginActivity loginActivity = Robolectric.buildActivity(LoginActivity.class).get();
        PowerMockito.mockStatic(ABService.class);
    }
}
```

It works for me when I found 2 mock frameworks have their own ClassLoader, and they are isolated from each other.
Mock framework always changes thread ContextClassLoader and recovers it to the original one after test finished.
While JUnit is generally running in single thread and in an isolated Test JVM for Gradle.

Therefore, my ugly solution is:
1. Specify RobolectricTestRunner, make it as the base ClassLoader in testing.
2. Add PowerMockRule, make it handle @PrepareForTest classes.
3. Set ContextClassLoader to Robolectric's SandboxClassLoader in @Before method, make test case run with RobolectricTestRunner again.

References:
https://github.com/junit-team/junit5/issues/1799

**Comment by ZSmallX** [comment]
Further more, a base test class which simply composes Robolectric and PowerMock may be very helpful.
And most annotations can be prepared at this time, for those annotations are @Inherited, which means those can be inherited by subClass.

Here's my code in kotlin:

```Kotlin
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [Build.VERSION_CODES.P], application = Application::class, manifest = Config.NONE)
@PowerMockIgnore(
        "org.mockito.*", "org.robolectric.*", "org.powermock.*",
        "android.*", "androidx.*"
)
open class BaseRobolectricTest {
    @get: Rule
    var rule = PowerMockRule()

    @Before
    fun setup() {
        Thread.currentThread().contextClassLoader = Context::class.java.classLoader
    }

    @Test
    fun makeSureClassLoader() {
        assertTrue(Thread.currentThread().contextClassLoader == Context::class.java.classLoader)
    }
}
```

**Comment by mikehardy** [comment]
Interesting - I actually purged powermock now that mockito can do static mocks https://github.com/mockito/mockito/blob/release/3.x/doc/release-notes/official.md#340 - one less dependency, less hairy testing...

**Comment by aa5279aa** [comment]
> Same problem!
Is it finally resolved?
