### ISSUE TITLE
WhenNew within a static method not working

### ISSUE THREAD

**Issue by ecsedigergo** [powermock/powermock#947]
Tring to mock a constructor call which is called in a static class:

I prepared the test class with
``` java

public class DelegateCreator{
	public static TestCaller CreateCallerWithMStatic(TestMocked m) {
		return new TestCaller(m);
	}
	public TestCaller CreateCallerWithM(TestMocked m) {
		return new TestCaller(m);
	}
}
@RunWith(PowerMockRunner.class)
@PrepareForTest(DelegateCreator.class)
@PowerMockRunnerDelegate(Parameterized.class)
public class TestPrivate {

	@Before
	public void setUp() throws Exception {
		PowerMockito.mockStatic(Static.class); ........
        }
        @Test
	public void testCtor() throws Exception {
		PowerMockito.mockStatic(DelegateCreator.class);
		PowerMockito.whenNew(TestCaller.class).withAnyArguments().thenThrow(new IOException());
                // It is throwing IOException when instantiating here
                // DelegateCreator d = new DelegateCreator();
                // d.CreateCallerWithM(w);
                // It is not throwing IOException
		DelegateCreator.CreateCallerWithMStatic(w);
		
		PowerMockito.verifyNew(TestCaller.class).withArguments(TestMocked.class);
	}
}
```

In order to help us to clarify issue can you answer the following question:

What steps will reproduce the problem?
see code sample in the above defined env with versions
What is the expected output?
```java.lang.AssertionError: Wanted but not invoked privateMethod.TestCaller(
    class privateMethod.TestMocked
);
Actually, there were zero interactions with this mock.
	at org.powermock.api.mockito.internal.invocation.InvocationControlAssertionError.throwAssertionErrorForNewSubstitutionFailure(InvocationControlAssertionError.java:93)
	at org.powermock.api.mockito.internal.verification.DefaultConstructorArgumentsVerfication.invokeSubstitute(DefaultConstructorArgumentsVerfication.java:51)
	at org.powermock.api.mockito.internal.verification.DefaultConstructorArgumentsVerfication.withArguments(DefaultConstructorArgumentsVerfication.java:44)
	at privateMethod.TestPrivate.testCtor(TestPrivate.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:88)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:294)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:127)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:282)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:86)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:207)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:146)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:33)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:45)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:106)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```
What version of the product are you using? 
Using Junit5 jupiter (5.3.1) and vintage with PowerMock 2.0.0-beta.5 and Mockito2

**Comment by panosgit** [comment]
@ecsedigergo which java version do you use? is it openjdk 11 ?

**Comment by ecsedigergo** [comment]
no, it is javaSE 1.8.0_121 (jdk)
I attach the test related configuration pom.xml:
`<?xml version="1.0" encoding="UTF-8"?>

    <properties>
        <java.version>1.8</java.version>
        <junit.version>4.12</junit.version>
		<junit.jupiter.version>5.3.1</junit.jupiter.version>
		<junit.vintage.version>5.3.1</junit.vintage.version>
		<junit.platform.version>1.3.1</junit.platform.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>2.23.0</version>
            <scope>test</scope>
        </dependency>

		<dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-core</artifactId>
            <version>1.7.1</version>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-mockito2</artifactId>
            <version>1.7.1</version>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4</artifactId>
            <version>1.7.1</version>
        </dependency>
        
        <dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>${junit.jupiter.version}</version>
		</dependency>
		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
			<version>${junit.vintage.version}</version>
		</dependency>
    </dependencies>
`

**Comment by viv32ek** [comment]
Is this resolved? Facing a similar issue, in a static method the whenNew doesn't work

**Comment by Techtony96** [comment]
I am also facing this issue. Do we have any confirmation that this is indeed a bug, or is some special configuration required? I have made sure to use the PrepareForTest annotation, specified the mock/spy to return when new is called, and I even tried using PowerMockito.mockStatic to no avail.
