### ISSUE TITLE
PowerMock breaks on Java 7 after upgrading 2.0.0-beta5 to 2.0.0

### ISSUE THREAD

**Issue by Pr0methean** [powermock/powermock#968]
After updating powermock-core, powermock-module-testng and powermock-api-mockito2 from 2.0.0-beta5 to 2.0.0, I get:

```
[ERROR] An error occurred while instantiating class io.github.pr0methean.betterrandom.prng.Cmwc4096RandomTest: javassist/NotFoundException : Unsupported major.minor version 52.0
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:658)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:978)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:854)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:606)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```
This upgrade worked fine on Java 8, 9, 10 and 11 on a slightly different code base.

**Comment by Pr0methean** [comment]
Closing since I was wrong about this being irreproducible on newer Java.

**Comment by Pr0methean** [comment]
Reopening: the newer-Java issue was a separate one.

**Comment by Tibor17** [comment]
@Pr0methean 
No issue!
The `2.0.0` is Java 1.8.

**Comment by Pr0methean** [comment]
If newer versions won't support JDK 7, then I'll have to use `2.0.0-beta5` on the Java 7 branch for the rest of that branch's life (which may have more than a year left, since Android API 23 and below can't be supported without it).

**Comment by dkowzan** [comment]
If support to JDK 7 is dropped could it be clearly stated in release notes then? I was also cough by surprise by this change.

**Comment by sergeykul7** [comment]
Is there a reason why you dropped Java 7 support between a beta5 and a released version?

**Comment by thekingn0thing** [comment]
PowerMock still aimed at the Java 1.6 and is being built with source and target flags 1.6. However, PowerMock also tries to support the latest version of java, to do it versions of some libraries were upgraded to the latest (especially the main libraries on which PowerMock uses for bytecode modification). 
Due to the reason that on Travis available only  jdk8 and higher I was not able to spot that new version of Javassist drop supporting java < 1.8. 
You can still use PowerMock with JDK 1.6 and 1.7, however, you need to specify explicitly version of javassit that works with your JDK. 
I have just tried the 3.22.0-GA version to run `powermock-example` project under jdk1.7.0_80 - all test passed and there is no  `Unsupported major.minor version` error.
