### ISSUE TITLE
spring-boot can't load  applicationContext

### ISSUE THREAD

**Issue by wzc903011** [powermock/powermock#990]
ClassNotFoundException: com.xx.RepositoryApplicationContext

demo code as：
@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(SpringJUnit4ClassRunner.class)
@PowerMockIgnore("javax.management.*")
@PrepareForTest({Environment.class})
@ContextConfiguration(classes = RepositoryApplicationContext.class, loader = AnnotationConfigContextLoader.class)
public class  PowerMockBaseRepositoryTest {}

@Configuration
@EnableAutoConfiguration
@EnableTransactionManagement
@EnableAspectJAutoProxy(proxyTargetClass = true)
@ComponentScan(value = "com.xx")
@Import(value = {
        CommonApplicationContext.class
})
public class RepositoryApplicationContext {}

error：
Caused by: java.lang.ClassNotFoundException: com.xx.RepositoryApplicationContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:178)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:70)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:251)
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:285)
	... 44 more

**Comment by Tibor17** [comment]
We do not have such problems with Java EE and it is always simple - less annotations than this.
Soon you will switch to Jakarta EE but now you can use MicroProfile on the top of EE 8.0.
