### ISSUE TITLE
Spy TooManyActualInvocations

### ISSUE THREAD

**Issue by alexzyp** [powermock/powermock#999]
What steps will reproduce the problem?
```java
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mockito;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import java.util.ArrayList;
import java.util.List;

@RunWith(PowerMockRunner.class)
@PrepareForTest(SpyTest.SpyExample.class)
public class SpyTest {
    @Test
    public void test() throws Exception {
        ArrayList<Integer> list = PowerMockito.spy(new ArrayList<Integer>());
        PowerMockito.whenNew(ArrayList.class).withNoArguments().thenReturn(list);

        SpyExample spyExample = new SpyExample();
        spyExample.add();

        Mockito.verify(list).add(1);
    }

    public static class SpyExample {
        public void add() {
            List<Integer> list = new ArrayList<Integer>();
            list.add(1);
        }
    }
}
```

What is the expected output?
Test passes

What do you see instead?
```
org.mockito.exceptions.verification.TooManyActualInvocations: 
arrayList.add(1);
Wanted 1 time:
-> at com.example.test.SpyTest.test(SpyTest.java:24)
But was 2 times:
-> at com.example.test.SpyTest$SpyExample.add(SpyTest.java:30)
-> at com.example.test.SpyTest$SpyExample.add(SpyTest.java:30)
```

What version of the product are you using? 
```
<properties>
    <powermock.version>2.0.2</powermock.version>
</properties>
<dependencies>
   <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-module-junit4</artifactId>
      <version>${powermock.version}</version>
      <scope>test</scope>
   </dependency>
   <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-api-mockito2</artifactId>
      <version>${powermock.version}</version>
      <scope>test</scope>
   </dependency>
</dependencies>
```

**Comment by alexzyp** [comment]
This one will reproduce the problem, too.
```
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mockito;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.modules.junit4.PowerMockRunner;

import java.util.ArrayList;

@RunWith(PowerMockRunner.class)
public class SpyTest2 {
    @Test
    public void test() throws Exception {
        ArrayList<Integer> list = PowerMockito.spy(new ArrayList<Integer>());
        list.add(1);
        Mockito.verify(list).add(1);
    }
}
```

**Comment by alexzyp** [comment]
This one is OK.
```
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mockito;
import org.mockito.junit.MockitoJUnitRunner;

import java.util.ArrayList;

@RunWith(MockitoJUnitRunner.class)
public class SpyTest3 {
    @Test
    public void test() throws Exception {
        ArrayList<Integer> list = Mockito.spy(new ArrayList<Integer>());
        list.add(1);
        Mockito.verify(list).add(1);
    }
}
```

**Comment by hamid-nazari** [comment]
I can confirm similar issue

```

import static org.mockito.Mockito.verify;

import java.util.LinkedList;
import java.util.List;

import org.mockito.Mockito;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.testng.PowerMockTestCase;
import org.testng.annotations.Test;

import static org.assertj.core.api.Assertions.assertThat;

@PrepareForTest({List.class, LinkedList.class})
public class PowerMockTests extends PowerMockTestCase
{
	@Test
	public void testPowerMockitoSpyFailure() throws Exception
	{
		// Simple Mockito
		List<String> list1 = new LinkedList<>();
		list1 = Mockito.spy(list1);
		list1.clear();
		verify(list1).clear();

		// PowerMockito, fails
		List<String> list2 = new LinkedList<>();
		list2 = PowerMockito.spy(list2);
		list2.clear();
		verify(list2).clear();
	}

	@Test
	public void testPowerMockitoSpyWeirdBehavior() throws Exception
	{
		// PowerMockito, passes
		List<String> list2 = new LinkedList<>();
		list2 = PowerMockito.spy(list2);
		list2.hashCode();
		list2.clear();
		verify(list2).clear();

		// PowerMockito, fails again!
		List<String> list3 = new LinkedList<>();
		list3 = PowerMockito.spy(list3);
		list3.hashCode();
		list3.hashCode();
		list3.clear();
		verify(list3).clear();
	}
}
```
